/**
 * Copyright (c) Microsoft. All rights reserved.
 * This code is licensed under the MIT License (MIT).
 * THIS CODE IS PROVIDED *AS IS* WITHOUT WARRANTY OF
 * ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING ANY
 * IMPLIED WARRANTIES OF FITNESS FOR A PARTICULAR
 * PURPOSE, MERCHANTABILITY, OR NON-INFRINGEMENT.
 *
 * Advanced Technology Group (ATG)
 *
 * AUTO-GENERATED by zstdgpu_srt_tool.exe. DO NOT EDIT.
 * Source of truth: zstdgpu_srt_decl.h
 */

#ifndef ZSTDGPU_SRT_GENERATED_ComputeDestSequenceOffsets_H
#define ZSTDGPU_SRT_GENERATED_ComputeDestSequenceOffsets_H

#ifdef __hlsl_dx_compiler

ZSTDGPU_RW_BUFFER(uint32_t)         ZstdInOutDestSequenceOffsets    : register(u0);
ZSTDGPU_RO_BUFFER(zstdgpu_Counters) ZstdInCounters                  : register(t0);
ZSTDGPU_RO_BUFFER(uint32_t)         ZstdInBlockDestOffs             : register(t1);
ZSTDGPU_RO_BUFFER(uint32_t)         ZstdInDecompressedSequenceMLen  : register(t2);
ZSTDGPU_RO_BUFFER(uint32_t)         ZstdInPerSeqStreamSeqStart      : register(t3);
ZSTDGPU_RO_BUFFER(uint32_t)         ZstdInSeqStreamToBlockId        : register(t4);

typedef struct zstdgpu_ComputeDestSequenceOffsets_Consts
{
    uint32_t    tgOffset;
    uint32_t    workItemCount;
} zstdgpu_ComputeDestSequenceOffsets_Consts;

ConstantBuffer<zstdgpu_ComputeDestSequenceOffsets_Consts> ZstdConstants_ComputeDestSequenceOffsets : register(b0);

#define ZSTDGPU_SRT_RS_ComputeDestSequenceOffsets "UAV(u0)" ", SRV(t0)" ", SRV(t1)" ", SRV(t2)" ", SRV(t3)" ", SRV(t4)" ", RootConstants(b0, num32BitConstants=2)"

static void zstdgpu_Srt_Fill(ZSTDGPU_PARAM_INOUT(zstdgpu_ComputeDestSequenceOffsets_SRT) srt)
{
    srt.inoutDestSequenceOffsets    = ZstdInOutDestSequenceOffsets;
    srt.inCounters                  = ZstdInCounters;
    srt.inBlockDestOffs             = ZstdInBlockDestOffs;
    srt.inDecompressedSequenceMLen  = ZstdInDecompressedSequenceMLen;
    srt.inPerSeqStreamSeqStart      = ZstdInPerSeqStreamSeqStart;
    srt.inSeqStreamToBlockId        = ZstdInSeqStreamToBlockId;
    srt.tgOffset                    = ZstdConstants_ComputeDestSequenceOffsets.tgOffset;
    srt.workItemCount               = ZstdConstants_ComputeDestSequenceOffsets.workItemCount;
}

#else

static void zstdgpu_Srt_Fill(zstdgpu_ComputeDestSequenceOffsets_SRT &srt, const zstdgpu_ResourceDataCpu &cpuRes,
                             uint32_t     tgOffset,
                             uint32_t     workItemCount)
{
    srt.inoutDestSequenceOffsets    = cpuRes.DestSequenceOffsets;
    srt.inCounters                  = cpuRes.Counters;
    srt.inBlockDestOffs             = cpuRes.BlockDestOffs;
    srt.inDecompressedSequenceMLen  = cpuRes.DecompressedSequenceMLen;
    srt.inPerSeqStreamSeqStart      = cpuRes.PerSeqStreamSeqStart;
    srt.inSeqStreamToBlockId        = cpuRes.SeqStreamToBlockId;
    srt.tgOffset                    = tgOffset;
    srt.workItemCount               = workItemCount;
}

#endif

#endif /* ZSTDGPU_SRT_GENERATED_ComputeDestSequenceOffsets_H */
