/**
 * Copyright (c) Microsoft. All rights reserved.
 * This code is licensed under the MIT License (MIT).
 * THIS CODE IS PROVIDED *AS IS* WITHOUT WARRANTY OF
 * ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING ANY
 * IMPLIED WARRANTIES OF FITNESS FOR A PARTICULAR
 * PURPOSE, MERCHANTABILITY, OR NON-INFRINGEMENT.
 *
 * Advanced Technology Group (ATG)
 *
 * AUTO-GENERATED by zstdgpu_srt_tool.exe. DO NOT EDIT.
 * Source of truth: zstdgpu_srt_decl.h
 */

#ifndef ZSTDGPU_SRT_GENERATED_RS_BIND_GROUP_HuffmanWeights_H
#define ZSTDGPU_SRT_GENERATED_RS_BIND_GROUP_HuffmanWeights_H

#ifdef __hlsl_dx_compiler

#define ZSTDGPU_SRT_RS_BIND_GROUP_HuffmanWeights "DescriptorTable(SRV(t0, space=5, numDescriptors=2))"

ZSTDGPU_RO_TYPED_BUFFER(uint32_t, uint8_t)  ZstdInDecompressedHuffmanWeights        : register(t0, space5);
ZSTDGPU_RO_TYPED_BUFFER(uint32_t, uint8_t)  ZstdInDecompressedHuffmanWeightCount    : register(t1, space5);

template<typename T>
static void zstdgpu_Srt_FillBindGroup_HuffmanWeights(ZSTDGPU_PARAM_INOUT(T) srt)
{
    srt.inDecompressedHuffmanWeights        = ZstdInDecompressedHuffmanWeights;
    srt.inDecompressedHuffmanWeightCount    = ZstdInDecompressedHuffmanWeightCount;
}

#else

template<typename T>
static void zstdgpu_Srt_FillBindGroup_HuffmanWeights(T &srt, const zstdgpu_ResourceDataCpu &cpuRes)
{
    srt.inDecompressedHuffmanWeights        = cpuRes.DecompressedHuffmanWeights;
    srt.inDecompressedHuffmanWeightCount    = cpuRes.DecompressedHuffmanWeightCount;
}

#endif /* #ifdef __hlsl_dx_compiler */
#endif /* ZSTDGPU_SRT_GENERATED_RS_BIND_GROUP_HuffmanWeights_H */
