/**
 * Copyright (c) Microsoft. All rights reserved.
 * This code is licensed under the MIT License (MIT).
 * THIS CODE IS PROVIDED *AS IS* WITHOUT WARRANTY OF
 * ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING ANY
 * IMPLIED WARRANTIES OF FITNESS FOR A PARTICULAR
 * PURPOSE, MERCHANTABILITY, OR NON-INFRINGEMENT.
 *
 * Advanced Technology Group (ATG)
 *
 * AUTO-GENERATED by zstdgpu_srt_tool.exe. DO NOT EDIT.
 * Source of truth: zstdgpu_srt_decl.h
 */

#ifndef ZSTDGPU_SRT_GENERATED_MemsetMemcpy_H
#define ZSTDGPU_SRT_GENERATED_MemsetMemcpy_H

#include "ZstdGpuSrt_BindGroup_FrameOutput.h"

#ifdef __hlsl_dx_compiler

ZSTDGPU_RO_BUFFER(zstdgpu_Counters)         ZstdInCounters              : register(t0);
ZSTDGPU_RO_BUFFER(uint32_t)                 ZstdInCompressedData        : register(t1);
ZSTDGPU_RO_BUFFER(uint32_t)                 ZstdInBlockDestOffs         : register(t2);
ZSTDGPU_RO_BUFFER(uint32_t)                 ZstdInBlockSizePrefixTyped  : register(t3);
ZSTDGPU_RO_BUFFER(zstdgpu_OffsetAndSize)    ZstdInBlocksRefsTyped       : register(t4);
ZSTDGPU_RO_BUFFER(uint32_t)                 ZstdInGlobalBlockIndexTyped : register(t5);

typedef struct zstdgpu_MemsetMemcpy_Consts
{
    uint32_t    tgOffset;
    uint32_t    workItemCount;
    uint32_t    flags;
} zstdgpu_MemsetMemcpy_Consts;

ConstantBuffer<zstdgpu_MemsetMemcpy_Consts> ZstdConstants_MemsetMemcpy : register(b0);

#define ZSTDGPU_SRT_RS_MemsetMemcpy ZSTDGPU_SRT_RS_BIND_GROUP_FrameOutput ", SRV(t0)" ", SRV(t1)" ", SRV(t2)" ", SRV(t3)" ", SRV(t4)" ", SRV(t5)" ", RootConstants(b0, num32BitConstants=3)"

static void zstdgpu_Srt_Fill(ZSTDGPU_PARAM_INOUT(zstdgpu_MemsetMemcpy_SRT) srt)
{
    zstdgpu_Srt_FillBindGroup_FrameOutput(srt);

    srt.inCounters              = ZstdInCounters;
    srt.inCompressedData        = ZstdInCompressedData;
    srt.inBlockDestOffs         = ZstdInBlockDestOffs;
    srt.inBlockSizePrefixTyped  = ZstdInBlockSizePrefixTyped;
    srt.inBlocksRefsTyped       = ZstdInBlocksRefsTyped;
    srt.inGlobalBlockIndexTyped = ZstdInGlobalBlockIndexTyped;
    srt.tgOffset                = ZstdConstants_MemsetMemcpy.tgOffset;
    srt.workItemCount           = ZstdConstants_MemsetMemcpy.workItemCount;
    srt.flags                   = ZstdConstants_MemsetMemcpy.flags;
}

#else

static void zstdgpu_Srt_Fill(zstdgpu_MemsetMemcpy_SRT &srt, const zstdgpu_ResourceDataCpu &cpuRes,
                             ZSTDGPU_RO_BUFFER(zstdgpu_Counters)          inCounters,
                             ZSTDGPU_RO_BUFFER(uint32_t)                  inCompressedData,
                             ZSTDGPU_RO_BUFFER(uint32_t)                  inBlockDestOffs,
                             ZSTDGPU_RO_BUFFER(uint32_t)                  inBlockSizePrefixTyped,
                             ZSTDGPU_RO_BUFFER(zstdgpu_OffsetAndSize)     inBlocksRefsTyped,
                             ZSTDGPU_RO_BUFFER(uint32_t)                  inGlobalBlockIndexTyped,
                             uint32_t                                     tgOffset,
                             uint32_t                                     workItemCount,
                             uint32_t                                     flags)
{
    zstdgpu_Srt_FillBindGroup_FrameOutput(srt, cpuRes);

    srt.inCounters              = inCounters;
    srt.inCompressedData        = inCompressedData;
    srt.inBlockDestOffs         = inBlockDestOffs;
    srt.inBlockSizePrefixTyped  = inBlockSizePrefixTyped;
    srt.inBlocksRefsTyped       = inBlocksRefsTyped;
    srt.inGlobalBlockIndexTyped = inGlobalBlockIndexTyped;
    srt.tgOffset                = tgOffset;
    srt.workItemCount           = workItemCount;
    srt.flags                   = flags;
}

static void zstdgpu_Srt_Fill_MemcpyRAW(zstdgpu_MemsetMemcpy_SRT &srt, const zstdgpu_ResourceDataCpu &cpuRes, uint32_t tgOffset, uint32_t workItemCount, uint32_t flags)
{
    zstdgpu_Srt_Fill(srt, cpuRes, cpuRes.Counters, cpuRes.CompressedData, cpuRes.BlockDestOffs, cpuRes.RawBlockSizePrefix, cpuRes.BlocksRAWRefs, cpuRes.GlobalBlockIndexPerRawBlock, tgOffset, workItemCount, flags);
}

static void zstdgpu_Srt_Fill_MemsetRLE(zstdgpu_MemsetMemcpy_SRT &srt, const zstdgpu_ResourceDataCpu &cpuRes, uint32_t tgOffset, uint32_t workItemCount, uint32_t flags)
{
    zstdgpu_Srt_Fill(srt, cpuRes, cpuRes.Counters, cpuRes.CompressedData, cpuRes.BlockDestOffs, cpuRes.RleBlockSizePrefix, cpuRes.BlocksRLERefs, cpuRes.GlobalBlockIndexPerRleBlock, tgOffset, workItemCount, flags);
}

#endif

#endif /* ZSTDGPU_SRT_GENERATED_MemsetMemcpy_H */
