/**
 * Copyright (c) Microsoft. All rights reserved.
 * This code is licensed under the MIT License (MIT).
 * THIS CODE IS PROVIDED *AS IS* WITHOUT WARRANTY OF
 * ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING ANY
 * IMPLIED WARRANTIES OF FITNESS FOR A PARTICULAR
 * PURPOSE, MERCHANTABILITY, OR NON-INFRINGEMENT.
 *
 * Advanced Technology Group (ATG)
 *
 * AUTO-GENERATED by zstdgpu_srt_tool.exe. DO NOT EDIT.
 * Source of truth: zstdgpu_srt_decl.h
 */

#ifndef ZSTDGPU_SRT_GENERATED_ComputePrefixSum_H
#define ZSTDGPU_SRT_GENERATED_ComputePrefixSum_H

#ifdef __hlsl_dx_compiler

ZSTDGPU_RO_BUFFER(uint32_t)         ZstdInHufWIdToHufLitId                      : register(t0);
ZSTDGPU_RO_BUFFER(uint32_t)         ZstdInHufLitIdToLitStreamId                 : register(t1);
ZSTDGPU_RW_BUFFER(uint32_t)         ZstdInOutLitGroupEndPerHuffmanTable         : register(u0);
ZSTDGPU_RW_BUFFER_GLC(uint32_t)     ZstdInOutLitGroupEndPerHuffmanTableLookback : register(u1);
ZSTDGPU_RW_BUFFER(zstdgpu_Counters) ZstdInOutCounters                           : register(u2);

typedef struct zstdgpu_ComputePrefixSum_Consts
{
    uint32_t    tgOffset;
    uint32_t    workItemCount;
    uint32_t    literalsPerGroup;
} zstdgpu_ComputePrefixSum_Consts;

ConstantBuffer<zstdgpu_ComputePrefixSum_Consts> ZstdConstants_ComputePrefixSum : register(b0);

#define ZSTDGPU_SRT_RS_ComputePrefixSum "SRV(t0)" ", SRV(t1)" ", UAV(u0)" ", UAV(u1)" ", UAV(u2)" ", RootConstants(b0, num32BitConstants=3)"

static void zstdgpu_Srt_Fill(ZSTDGPU_PARAM_INOUT(zstdgpu_ComputePrefixSum_SRT) srt)
{
    srt.inHufWIdToHufLitId                      = ZstdInHufWIdToHufLitId;
    srt.inHufLitIdToLitStreamId                 = ZstdInHufLitIdToLitStreamId;
    srt.inoutLitGroupEndPerHuffmanTable         = ZstdInOutLitGroupEndPerHuffmanTable;
    srt.inoutLitGroupEndPerHuffmanTableLookback = ZstdInOutLitGroupEndPerHuffmanTableLookback;
    srt.inoutCounters                           = ZstdInOutCounters;
    srt.tgOffset                                = ZstdConstants_ComputePrefixSum.tgOffset;
    srt.workItemCount                           = ZstdConstants_ComputePrefixSum.workItemCount;
    srt.literalsPerGroup                        = ZstdConstants_ComputePrefixSum.literalsPerGroup;
}

#else

static void zstdgpu_Srt_Fill(zstdgpu_ComputePrefixSum_SRT &srt, const zstdgpu_ResourceDataCpu &cpuRes,
                             uint32_t     tgOffset,
                             uint32_t     workItemCount,
                             uint32_t     literalsPerGroup)
{
    srt.inHufWIdToHufLitId                      = cpuRes.HufWIdToHufLitId;
    srt.inHufLitIdToLitStreamId                 = cpuRes.HufLitIdToLitStreamId;
    srt.inoutLitGroupEndPerHuffmanTable         = cpuRes.LitGroupEndPerHuffmanTable;
    srt.inoutLitGroupEndPerHuffmanTableLookback = cpuRes.LitGroupEndPerHuffmanTableLookback;
    srt.inoutCounters                           = cpuRes.Counters;
    srt.tgOffset                                = tgOffset;
    srt.workItemCount                           = workItemCount;
    srt.literalsPerGroup                        = literalsPerGroup;
}

#endif

#endif /* ZSTDGPU_SRT_GENERATED_ComputePrefixSum_H */
