/**
 * Copyright (c) Microsoft. All rights reserved.
 * This code is licensed under the MIT License (MIT).
 * THIS CODE IS PROVIDED *AS IS* WITHOUT WARRANTY OF
 * ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING ANY
 * IMPLIED WARRANTIES OF FITNESS FOR A PARTICULAR
 * PURPOSE, MERCHANTABILITY, OR NON-INFRINGEMENT.
 *
 * Advanced Technology Group (ATG)
 *
 * AUTO-GENERATED by zstdgpu_srt_tool.exe. DO NOT EDIT.
 * Source of truth: zstdgpu_srt_decl.h
 */

#ifndef ZSTDGPU_SRT_GENERATED_RS_BIND_GROUP_SequenceOutputs_H
#define ZSTDGPU_SRT_GENERATED_RS_BIND_GROUP_SequenceOutputs_H

#ifdef __hlsl_dx_compiler

#define ZSTDGPU_SRT_RS_BIND_GROUP_SequenceOutputs "DescriptorTable(UAV(u0, space=8, numDescriptors=7))"

ZSTDGPU_RW_BUFFER(uint32_t) ZstdInOutDecompressedSequenceLLen   : register(u0, space8);
ZSTDGPU_RW_BUFFER(uint32_t) ZstdInOutDecompressedSequenceMLen   : register(u1, space8);
ZSTDGPU_RW_BUFFER(uint32_t) ZstdInOutDecompressedSequenceOffs   : register(u2, space8);
ZSTDGPU_RW_BUFFER(uint32_t) ZstdInOutBlockSizePrefix            : register(u3, space8);
ZSTDGPU_RW_BUFFER(uint32_t) ZstdInOutPerSeqStreamFinalOffset1   : register(u4, space8);
ZSTDGPU_RW_BUFFER(uint32_t) ZstdInOutPerSeqStreamFinalOffset2   : register(u5, space8);
ZSTDGPU_RW_BUFFER(uint32_t) ZstdInOutPerSeqStreamFinalOffset3   : register(u6, space8);

template<typename T>
static void zstdgpu_Srt_FillBindGroup_SequenceOutputs(ZSTDGPU_PARAM_INOUT(T) srt)
{
    srt.inoutDecompressedSequenceLLen   = ZstdInOutDecompressedSequenceLLen;
    srt.inoutDecompressedSequenceMLen   = ZstdInOutDecompressedSequenceMLen;
    srt.inoutDecompressedSequenceOffs   = ZstdInOutDecompressedSequenceOffs;
    srt.inoutBlockSizePrefix            = ZstdInOutBlockSizePrefix;
    srt.inoutPerSeqStreamFinalOffset1   = ZstdInOutPerSeqStreamFinalOffset1;
    srt.inoutPerSeqStreamFinalOffset2   = ZstdInOutPerSeqStreamFinalOffset2;
    srt.inoutPerSeqStreamFinalOffset3   = ZstdInOutPerSeqStreamFinalOffset3;
}

#else

template<typename T>
static void zstdgpu_Srt_FillBindGroup_SequenceOutputs(T &srt, const zstdgpu_ResourceDataCpu &cpuRes)
{
    srt.inoutDecompressedSequenceLLen   = cpuRes.DecompressedSequenceLLen;
    srt.inoutDecompressedSequenceMLen   = cpuRes.DecompressedSequenceMLen;
    srt.inoutDecompressedSequenceOffs   = cpuRes.DecompressedSequenceOffs;
    srt.inoutBlockSizePrefix            = cpuRes.BlockSizePrefix;
    srt.inoutPerSeqStreamFinalOffset1   = cpuRes.PerSeqStreamFinalOffset1;
    srt.inoutPerSeqStreamFinalOffset2   = cpuRes.PerSeqStreamFinalOffset2;
    srt.inoutPerSeqStreamFinalOffset3   = cpuRes.PerSeqStreamFinalOffset3;
}

#endif /* #ifdef __hlsl_dx_compiler */
#endif /* ZSTDGPU_SRT_GENERATED_RS_BIND_GROUP_SequenceOutputs_H */
