/**
 * Copyright (c) Microsoft. All rights reserved.
 * This code is licensed under the MIT License (MIT).
 * THIS CODE IS PROVIDED *AS IS* WITHOUT WARRANTY OF
 * ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING ANY
 * IMPLIED WARRANTIES OF FITNESS FOR A PARTICULAR
 * PURPOSE, MERCHANTABILITY, OR NON-INFRINGEMENT.
 *
 * Advanced Technology Group (ATG)
 *
 * AUTO-GENERATED by zstdgpu_srt_tool.exe. DO NOT EDIT.
 * Source of truth: zstdgpu_srt_decl.h
 */

#ifndef ZSTDGPU_SRT_GENERATED_InitFseTable_H
#define ZSTDGPU_SRT_GENERATED_InitFseTable_H

#include "ZstdGpuSrt_BindGroup_FseProbsRead.h"

#ifdef __hlsl_dx_compiler

ZSTDGPU_RW_BUFFER(uint32_t)         ZstdInOutFseElems   : register(u0);
ZSTDGPU_RO_BUFFER(zstdgpu_FseInfo)  ZstdInFseInfos      : register(t0);
ZSTDGPU_RO_BUFFER(zstdgpu_Counters) ZstdInCounters      : register(t1);

typedef struct zstdgpu_InitFseTable_Consts
{
    uint32_t    tgOffset;
    uint32_t    workItemCount;
    uint32_t    tableType;
} zstdgpu_InitFseTable_Consts;

ConstantBuffer<zstdgpu_InitFseTable_Consts> ZstdConstants_InitFseTable : register(b0);

#define ZSTDGPU_SRT_RS_InitFseTable ZSTDGPU_SRT_RS_BIND_GROUP_FseProbsRead ", UAV(u0)" ", SRV(t0)" ", SRV(t1)" ", RootConstants(b0, num32BitConstants=3)"

static void zstdgpu_Srt_Fill(ZSTDGPU_PARAM_INOUT(zstdgpu_InitFseTable_SRT) srt)
{
    zstdgpu_Srt_FillBindGroup_FseProbsRead(srt);

    srt.inoutFseElems   = ZstdInOutFseElems;
    srt.inFseInfos      = ZstdInFseInfos;
    srt.inCounters      = ZstdInCounters;
    srt.tgOffset        = ZstdConstants_InitFseTable.tgOffset;
    srt.workItemCount   = ZstdConstants_InitFseTable.workItemCount;
    srt.tableType       = ZstdConstants_InitFseTable.tableType;
}

#else

static void zstdgpu_Srt_Fill(zstdgpu_InitFseTable_SRT &srt, const zstdgpu_ResourceDataCpu &cpuRes,
                             uint32_t     tgOffset,
                             uint32_t     workItemCount,
                             uint32_t     tableType)
{
    zstdgpu_Srt_FillBindGroup_FseProbsRead(srt, cpuRes);

    srt.inoutFseElems   = cpuRes.FseElems;
    srt.inFseInfos      = cpuRes.FseInfos;
    srt.inCounters      = cpuRes.Counters;
    srt.tgOffset        = tgOffset;
    srt.workItemCount   = workItemCount;
    srt.tableType       = tableType;
}

#endif

static void zstdgpu_Srt_FillInline(ZSTDGPU_PARAM_INOUT(zstdgpu_InitFseTable_SRT) srt, uint32_t tableStartIndex, uint32_t tableDataStart, uint32_t tableDataCount)
{
    srt.tableStartIndex                                 = tableStartIndex;
    srt.tableDataStart                                  = tableDataStart;
    srt.tableDataCount                                  = tableDataCount;
}

#endif /* ZSTDGPU_SRT_GENERATED_InitFseTable_H */
