/**
 * Copyright (c) Microsoft. All rights reserved.
 * This code is licensed under the MIT License (MIT).
 * THIS CODE IS PROVIDED *AS IS* WITHOUT WARRANTY OF
 * ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING ANY
 * IMPLIED WARRANTIES OF FITNESS FOR A PARTICULAR
 * PURPOSE, MERCHANTABILITY, OR NON-INFRINGEMENT.
 *
 * Advanced Technology Group (ATG)
 *
 * AUTO-GENERATED by zstdgpu_srt_tool.exe. DO NOT EDIT.
 * Source of truth: zstdgpu_srt_decl.h
 */

#ifndef ZSTDGPU_SRT_GENERATED_UpdateDispatchArgs_H
#define ZSTDGPU_SRT_GENERATED_UpdateDispatchArgs_H

#ifdef __hlsl_dx_compiler

ZSTDGPU_RW_BUFFER(zstdgpu_Counters) ZstdInOutCounters       : register(u0);
ZSTDGPU_RW_BUFFER(uint32_t)         ZstdInOutDispatchArgs   : register(u1);
ZSTDGPU_RW_BUFFER(uint32_t)         ZstdInOutDispatchCnts   : register(u2);
ZSTDGPU_RW_BUFFER(uint32_t)         ZstdInOutPredicate      : register(u3);

typedef struct zstdgpu_UpdateDispatchArgs_Consts
{
    uint32_t    decompressSequences_StreamsPerTG;
    uint32_t    stage;
    uint32_t    cmpBlockCountMax;
    uint32_t    rawBlockCountMax;
    uint32_t    rleBlockCountMax;
    uint32_t    litByteCountMax;
    uint32_t    seqElemCountMax;
} zstdgpu_UpdateDispatchArgs_Consts;

ConstantBuffer<zstdgpu_UpdateDispatchArgs_Consts> ZstdConstants_UpdateDispatchArgs : register(b0);

#define ZSTDGPU_SRT_RS_UpdateDispatchArgs "UAV(u0)" ", UAV(u1)" ", UAV(u2)" ", UAV(u3)" ", RootConstants(b0, num32BitConstants=7)"

static void zstdgpu_Srt_Fill(ZSTDGPU_PARAM_INOUT(zstdgpu_UpdateDispatchArgs_SRT) srt)
{
    srt.inoutCounters                       = ZstdInOutCounters;
    srt.inoutDispatchArgs                   = ZstdInOutDispatchArgs;
    srt.inoutDispatchCnts                   = ZstdInOutDispatchCnts;
    srt.inoutPredicate                      = ZstdInOutPredicate;
    srt.decompressSequences_StreamsPerTG    = ZstdConstants_UpdateDispatchArgs.decompressSequences_StreamsPerTG;
    srt.stage                               = ZstdConstants_UpdateDispatchArgs.stage;
    srt.cmpBlockCountMax                    = ZstdConstants_UpdateDispatchArgs.cmpBlockCountMax;
    srt.rawBlockCountMax                    = ZstdConstants_UpdateDispatchArgs.rawBlockCountMax;
    srt.rleBlockCountMax                    = ZstdConstants_UpdateDispatchArgs.rleBlockCountMax;
    srt.litByteCountMax                     = ZstdConstants_UpdateDispatchArgs.litByteCountMax;
    srt.seqElemCountMax                     = ZstdConstants_UpdateDispatchArgs.seqElemCountMax;
}

#else

static void zstdgpu_Srt_Fill(zstdgpu_UpdateDispatchArgs_SRT &srt, const zstdgpu_ResourceDataCpu &cpuRes,
                             uint32_t     decompressSequences_StreamsPerTG,
                             uint32_t     stage,
                             uint32_t     cmpBlockCountMax,
                             uint32_t     rawBlockCountMax,
                             uint32_t     rleBlockCountMax,
                             uint32_t     litByteCountMax,
                             uint32_t     seqElemCountMax)
{
    srt.inoutCounters                       = cpuRes.Counters;
    srt.inoutDispatchArgs                   = cpuRes.DispatchArgs;
    srt.inoutDispatchCnts                   = cpuRes.DispatchCnts;
    srt.inoutPredicate                      = cpuRes.Predicate;
    srt.decompressSequences_StreamsPerTG    = decompressSequences_StreamsPerTG;
    srt.stage                               = stage;
    srt.cmpBlockCountMax                    = cmpBlockCountMax;
    srt.rawBlockCountMax                    = rawBlockCountMax;
    srt.rleBlockCountMax                    = rleBlockCountMax;
    srt.litByteCountMax                     = litByteCountMax;
    srt.seqElemCountMax                     = seqElemCountMax;
}

#endif

#endif /* ZSTDGPU_SRT_GENERATED_UpdateDispatchArgs_H */
