/**
 * Copyright (c) Microsoft. All rights reserved.
 * This code is licensed under the MIT License (MIT).
 * THIS CODE IS PROVIDED *AS IS* WITHOUT WARRANTY OF
 * ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING ANY
 * IMPLIED WARRANTIES OF FITNESS FOR A PARTICULAR
 * PURPOSE, MERCHANTABILITY, OR NON-INFRINGEMENT.
 *
 * Advanced Technology Group (ATG)
 *
 * AUTO-GENERATED by zstdgpu_srt_tool.exe. DO NOT EDIT.
 * Source of truth: zstdgpu_srt_decl.h
 */

#ifndef ZSTDGPU_SRT_GENERATED_RS_BIND_GROUP_HuffmanTableWrite_H
#define ZSTDGPU_SRT_GENERATED_RS_BIND_GROUP_HuffmanTableWrite_H

#ifdef __hlsl_dx_compiler

#define ZSTDGPU_SRT_RS_BIND_GROUP_HuffmanTableWrite "DescriptorTable(UAV(u0, space=7, numDescriptors=3))"

ZSTDGPU_RW_BUFFER(uint32_t) ZstdInOutHuffmanTableInfo           : register(u0, space7);
ZSTDGPU_RW_BUFFER(uint32_t) ZstdInOutHuffmanTableCodeAndSymbol  : register(u1, space7);
ZSTDGPU_RW_BUFFER(uint32_t) ZstdInOutHuffmanTableRankIndex      : register(u2, space7);

template<typename T>
static void zstdgpu_Srt_FillBindGroup_HuffmanTableWrite(ZSTDGPU_PARAM_INOUT(T) srt)
{
    srt.inoutHuffmanTableInfo           = ZstdInOutHuffmanTableInfo;
    srt.inoutHuffmanTableCodeAndSymbol  = ZstdInOutHuffmanTableCodeAndSymbol;
    srt.inoutHuffmanTableRankIndex      = ZstdInOutHuffmanTableRankIndex;
}

#else

template<typename T>
static void zstdgpu_Srt_FillBindGroup_HuffmanTableWrite(T &srt, const zstdgpu_ResourceDataCpu &cpuRes)
{
    srt.inoutHuffmanTableInfo           = cpuRes.HuffmanTableInfo;
    srt.inoutHuffmanTableCodeAndSymbol  = cpuRes.HuffmanTableCodeAndSymbol;
    srt.inoutHuffmanTableRankIndex      = cpuRes.HuffmanTableRankIndex;
}

#endif /* #ifdef __hlsl_dx_compiler */
#endif /* ZSTDGPU_SRT_GENERATED_RS_BIND_GROUP_HuffmanTableWrite_H */
