/**
 * Copyright (c) Microsoft. All rights reserved.
 * This code is licensed under the MIT License (MIT).
 * THIS CODE IS PROVIDED *AS IS* WITHOUT WARRANTY OF
 * ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING ANY
 * IMPLIED WARRANTIES OF FITNESS FOR A PARTICULAR
 * PURPOSE, MERCHANTABILITY, OR NON-INFRINGEMENT.
 *
 * Advanced Technology Group (ATG)
 *
 * AUTO-GENERATED by zstdgpu_srt_tool.exe. DO NOT EDIT.
 * Source of truth: zstdgpu_srt_decl.h
 */

#ifndef ZSTDGPU_SRT_GENERATED_FinaliseSequenceOffsets_H
#define ZSTDGPU_SRT_GENERATED_FinaliseSequenceOffsets_H

#ifdef __hlsl_dx_compiler

ZSTDGPU_RW_BUFFER(uint32_t)         ZstdInOutDecompressedSequenceOffs   : register(u0);
ZSTDGPU_RO_BUFFER(zstdgpu_Counters) ZstdInCounters                      : register(t0);
ZSTDGPU_RO_BUFFER(uint32_t)         ZstdInPerSeqStreamFinalOffset1      : register(t1);
ZSTDGPU_RO_BUFFER(uint32_t)         ZstdInPerSeqStreamFinalOffset2      : register(t2);
ZSTDGPU_RO_BUFFER(uint32_t)         ZstdInPerSeqStreamFinalOffset3      : register(t3);
ZSTDGPU_RO_BUFFER(uint32_t)         ZstdInPerSeqStreamSeqStart          : register(t4);
ZSTDGPU_RO_BUFFER(uint32_t)         ZstdInPerFrameBlockCountAll         : register(t5);
ZSTDGPU_RO_BUFFER(uint32_t)         ZstdInPerFrameSeqStreamMinIdx       : register(t6);
ZSTDGPU_RO_BUFFER(uint32_t)         ZstdInSeqStreamToBlockId            : register(t7);

typedef struct zstdgpu_FinaliseSequenceOffsets_Consts
{
    uint32_t    tgOffset;
    uint32_t    workItemCount;
} zstdgpu_FinaliseSequenceOffsets_Consts;

ConstantBuffer<zstdgpu_FinaliseSequenceOffsets_Consts> ZstdConstants_FinaliseSequenceOffsets : register(b0);

#define ZSTDGPU_SRT_RS_FinaliseSequenceOffsets "UAV(u0)" ", SRV(t0)" ", SRV(t1)" ", SRV(t2)" ", SRV(t3)" ", SRV(t4)" ", SRV(t5)" ", SRV(t6)" ", SRV(t7)" ", RootConstants(b0, num32BitConstants=2)"

static void zstdgpu_Srt_Fill(ZSTDGPU_PARAM_INOUT(zstdgpu_FinaliseSequenceOffsets_SRT) srt)
{
    srt.inoutDecompressedSequenceOffs   = ZstdInOutDecompressedSequenceOffs;
    srt.inCounters                      = ZstdInCounters;
    srt.inPerSeqStreamFinalOffset1      = ZstdInPerSeqStreamFinalOffset1;
    srt.inPerSeqStreamFinalOffset2      = ZstdInPerSeqStreamFinalOffset2;
    srt.inPerSeqStreamFinalOffset3      = ZstdInPerSeqStreamFinalOffset3;
    srt.inPerSeqStreamSeqStart          = ZstdInPerSeqStreamSeqStart;
    srt.inPerFrameBlockCountAll         = ZstdInPerFrameBlockCountAll;
    srt.inPerFrameSeqStreamMinIdx       = ZstdInPerFrameSeqStreamMinIdx;
    srt.inSeqStreamToBlockId            = ZstdInSeqStreamToBlockId;
    srt.tgOffset                        = ZstdConstants_FinaliseSequenceOffsets.tgOffset;
    srt.workItemCount                   = ZstdConstants_FinaliseSequenceOffsets.workItemCount;
}

#else

static void zstdgpu_Srt_Fill(zstdgpu_FinaliseSequenceOffsets_SRT &srt, const zstdgpu_ResourceDataCpu &cpuRes,
                             uint32_t     tgOffset,
                             uint32_t     workItemCount)
{
    srt.inoutDecompressedSequenceOffs   = cpuRes.DecompressedSequenceOffs;
    srt.inCounters                      = cpuRes.Counters;
    srt.inPerSeqStreamFinalOffset1      = cpuRes.PerSeqStreamFinalOffset1;
    srt.inPerSeqStreamFinalOffset2      = cpuRes.PerSeqStreamFinalOffset2;
    srt.inPerSeqStreamFinalOffset3      = cpuRes.PerSeqStreamFinalOffset3;
    srt.inPerSeqStreamSeqStart          = cpuRes.PerSeqStreamSeqStart;
    srt.inPerFrameBlockCountAll         = cpuRes.PerFrameBlockCountAll;
    srt.inPerFrameSeqStreamMinIdx       = cpuRes.PerFrameSeqStreamMinIdx;
    srt.inSeqStreamToBlockId            = cpuRes.SeqStreamToBlockId;
    srt.tgOffset                        = tgOffset;
    srt.workItemCount                   = workItemCount;
}

#endif

#endif /* ZSTDGPU_SRT_GENERATED_FinaliseSequenceOffsets_H */
