/**
 * Copyright (c) Microsoft. All rights reserved.
 * This code is licensed under the MIT License (MIT).
 * THIS CODE IS PROVIDED *AS IS* WITHOUT WARRANTY OF
 * ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING ANY
 * IMPLIED WARRANTIES OF FITNESS FOR A PARTICULAR
 * PURPOSE, MERCHANTABILITY, OR NON-INFRINGEMENT.
 *
 * Advanced Technology Group (ATG)
 *
 * AUTO-GENERATED by zstdgpu_srt_tool.exe. DO NOT EDIT.
 * Source of truth: zstdgpu_srt_decl.h
 */

#ifndef ZSTDGPU_SRT_GENERATED_RS_BIND_GROUP_FseInit_H
#define ZSTDGPU_SRT_GENERATED_RS_BIND_GROUP_FseInit_H

#ifdef __hlsl_dx_compiler

#define ZSTDGPU_SRT_RS_BIND_GROUP_FseInit "DescriptorTable(SRV(t0, space=12, numDescriptors=1), UAV(u0, space=12, numDescriptors=3))"

ZSTDGPU_RO_TYPED_BUFFER(int32_t, int16_t)   ZstdInFseProbsDefault   : register(t0, space12);
ZSTDGPU_RW_TYPED_BUFFER(int32_t, int16_t)   ZstdInOutFseProbs       : register(u0, space12);
ZSTDGPU_RW_BUFFER(zstdgpu_FseInfo)          ZstdInOutFseInfos       : register(u1, space12);
ZSTDGPU_RW_BUFFER(uint32_t)                 ZstdInOutFseElems       : register(u2, space12);

template<typename T>
static void zstdgpu_Srt_FillBindGroup_FseInit(ZSTDGPU_PARAM_INOUT(T) srt)
{
    srt.inFseProbsDefault   = ZstdInFseProbsDefault;
    srt.inoutFseProbs       = ZstdInOutFseProbs;
    srt.inoutFseInfos       = ZstdInOutFseInfos;
    srt.inoutFseElems       = ZstdInOutFseElems;
}

#else

template<typename T>
static void zstdgpu_Srt_FillBindGroup_FseInit(T &srt, const zstdgpu_ResourceDataCpu &cpuRes)
{
    srt.inFseProbsDefault   = cpuRes.FseProbsDefault;
    srt.inoutFseProbs       = cpuRes.FseProbs;
    srt.inoutFseInfos       = cpuRes.FseInfos;
    srt.inoutFseElems       = cpuRes.FseElems;
}

#endif /* #ifdef __hlsl_dx_compiler */
#endif /* ZSTDGPU_SRT_GENERATED_RS_BIND_GROUP_FseInit_H */
