/**
 * Copyright (c) Microsoft. All rights reserved.
 * This code is licensed under the MIT License (MIT).
 * THIS CODE IS PROVIDED *AS IS* WITHOUT WARRANTY OF
 * ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING ANY
 * IMPLIED WARRANTIES OF FITNESS FOR A PARTICULAR
 * PURPOSE, MERCHANTABILITY, OR NON-INFRINGEMENT.
 *
 * Advanced Technology Group (ATG)
 *
 * AUTO-GENERATED by zstdgpu_srt_tool.exe. DO NOT EDIT.
 * Source of truth: zstdgpu_srt_decl.h
 */

#ifndef ZSTDGPU_SRT_GENERATED_ParseFrames_H
#define ZSTDGPU_SRT_GENERATED_ParseFrames_H

#include "ZstdGpuSrt_BindGroup_ParseFrames.h"

#ifdef __hlsl_dx_compiler

typedef struct zstdgpu_ParseFrames_Consts
{
    uint32_t    frameCount;
    uint32_t    compressedBufferSizeInBytes;
    uint32_t    countBlocksOnly;
} zstdgpu_ParseFrames_Consts;

ConstantBuffer<zstdgpu_ParseFrames_Consts> ZstdConstants_ParseFrames : register(b0);

#define ZSTDGPU_SRT_RS_ParseFrames ZSTDGPU_SRT_RS_BIND_GROUP_ParseFrames ", RootConstants(b0, num32BitConstants=3)"

static void zstdgpu_Srt_Fill(ZSTDGPU_PARAM_INOUT(zstdgpu_ParseFrames_SRT) srt)
{
    zstdgpu_Srt_FillBindGroup_ParseFrames(srt);

    srt.frameCount                  = ZstdConstants_ParseFrames.frameCount;
    srt.compressedBufferSizeInBytes = ZstdConstants_ParseFrames.compressedBufferSizeInBytes;
    srt.countBlocksOnly             = ZstdConstants_ParseFrames.countBlocksOnly;
}

#else

static void zstdgpu_Srt_Fill(zstdgpu_ParseFrames_SRT &srt, const zstdgpu_ResourceDataCpu &cpuRes,
                             uint32_t     frameCount,
                             uint32_t     compressedBufferSizeInBytes,
                             uint32_t     countBlocksOnly)
{
    zstdgpu_Srt_FillBindGroup_ParseFrames(srt, cpuRes);
    srt.frameCount                  = frameCount;
    srt.compressedBufferSizeInBytes = compressedBufferSizeInBytes;
    srt.countBlocksOnly             = countBlocksOnly;
}

#endif

#endif /* ZSTDGPU_SRT_GENERATED_ParseFrames_H */
