/**
 * Copyright (c) Microsoft. All rights reserved.
 * This code is licensed under the MIT License (MIT).
 * THIS CODE IS PROVIDED *AS IS* WITHOUT WARRANTY OF
 * ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING ANY
 * IMPLIED WARRANTIES OF FITNESS FOR A PARTICULAR
 * PURPOSE, MERCHANTABILITY, OR NON-INFRINGEMENT.
 *
 * Advanced Technology Group (ATG)
 *
 * AUTO-GENERATED by zstdgpu_srt_tool.exe. DO NOT EDIT.
 * Source of truth: zstdgpu_srt_decl.h
 */

#ifndef ZSTDGPU_SRT_GENERATED_DecompressLiterals_H
#define ZSTDGPU_SRT_GENERATED_DecompressLiterals_H

#include "ZstdGpuSrt_BindGroup_LiteralStreams.h"
#include "ZstdGpuSrt_BindGroup_HuffmanTable.h"
#include "ZstdGpuSrt_BindGroup_LiteralDwords.h"

#ifdef __hlsl_dx_compiler

typedef struct zstdgpu_DecompressLiterals_Consts
{
    uint32_t    tgOffset;
    uint32_t    workItemCount;
} zstdgpu_DecompressLiterals_Consts;

ConstantBuffer<zstdgpu_DecompressLiterals_Consts> ZstdConstants_DecompressLiterals : register(b0);

#define ZSTDGPU_SRT_RS_DecompressLiterals ZSTDGPU_SRT_RS_BIND_GROUP_LiteralStreams ", " ZSTDGPU_SRT_RS_BIND_GROUP_HuffmanTable ", " ZSTDGPU_SRT_RS_BIND_GROUP_LiteralDwords ", RootConstants(b0, num32BitConstants=2)"

static void zstdgpu_Srt_Fill(ZSTDGPU_PARAM_INOUT(zstdgpu_DecompressLiterals_SRT) srt)
{
    zstdgpu_Srt_FillBindGroup_LiteralStreams(srt);
    zstdgpu_Srt_FillBindGroup_HuffmanTable(srt);
    zstdgpu_Srt_FillBindGroup_LiteralDwords(srt);

    srt.tgOffset        = ZstdConstants_DecompressLiterals.tgOffset;
    srt.workItemCount   = ZstdConstants_DecompressLiterals.workItemCount;
}

#else

static void zstdgpu_Srt_Fill(zstdgpu_DecompressLiterals_SRT &srt, const zstdgpu_ResourceDataCpu &cpuRes,
                             uint32_t     tgOffset,
                             uint32_t     workItemCount)
{
    zstdgpu_Srt_FillBindGroup_LiteralStreams(srt, cpuRes);
    zstdgpu_Srt_FillBindGroup_HuffmanTable(srt, cpuRes);
    zstdgpu_Srt_FillBindGroup_LiteralDwords(srt, cpuRes);
    srt.tgOffset        = tgOffset;
    srt.workItemCount   = workItemCount;
}

#endif

#endif /* ZSTDGPU_SRT_GENERATED_DecompressLiterals_H */
