/**
 * Copyright (c) Microsoft. All rights reserved.
 * This code is licensed under the MIT License (MIT).
 * THIS CODE IS PROVIDED *AS IS* WITHOUT WARRANTY OF
 * ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING ANY
 * IMPLIED WARRANTIES OF FITNESS FOR A PARTICULAR
 * PURPOSE, MERCHANTABILITY, OR NON-INFRINGEMENT.
 *
 * Advanced Technology Group (ATG)
 *
 * AUTO-GENERATED by zstdgpu_srt_tool.exe. DO NOT EDIT.
 * Source of truth: zstdgpu_srt_decl.h
 */

#ifndef ZSTDGPU_SRT_GENERATED_RS_BIND_GROUP_HuffmanWeightsWrite_H
#define ZSTDGPU_SRT_GENERATED_RS_BIND_GROUP_HuffmanWeightsWrite_H

#ifdef __hlsl_dx_compiler

#define ZSTDGPU_SRT_RS_BIND_GROUP_HuffmanWeightsWrite "DescriptorTable(UAV(u0, space=6, numDescriptors=2))"

ZSTDGPU_RW_TYPED_BUFFER(uint32_t, uint8_t)  ZstdInOutDecompressedHuffmanWeights     : register(u0, space6);
ZSTDGPU_RW_TYPED_BUFFER(uint32_t, uint8_t)  ZstdInOutDecompressedHuffmanWeightCount : register(u1, space6);

template<typename T>
static void zstdgpu_Srt_FillBindGroup_HuffmanWeightsWrite(ZSTDGPU_PARAM_INOUT(T) srt)
{
    srt.inoutDecompressedHuffmanWeights     = ZstdInOutDecompressedHuffmanWeights;
    srt.inoutDecompressedHuffmanWeightCount = ZstdInOutDecompressedHuffmanWeightCount;
}

#else

template<typename T>
static void zstdgpu_Srt_FillBindGroup_HuffmanWeightsWrite(T &srt, const zstdgpu_ResourceDataCpu &cpuRes)
{
    srt.inoutDecompressedHuffmanWeights     = cpuRes.DecompressedHuffmanWeights;
    srt.inoutDecompressedHuffmanWeightCount = cpuRes.DecompressedHuffmanWeightCount;
}

#endif /* #ifdef __hlsl_dx_compiler */
#endif /* ZSTDGPU_SRT_GENERATED_RS_BIND_GROUP_HuffmanWeightsWrite_H */
