/**
 * Copyright (c) Microsoft. All rights reserved.
 * This code is licensed under the MIT License (MIT).
 * THIS CODE IS PROVIDED *AS IS* WITHOUT WARRANTY OF
 * ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING ANY
 * IMPLIED WARRANTIES OF FITNESS FOR A PARTICULAR
 * PURPOSE, MERCHANTABILITY, OR NON-INFRINGEMENT.
 *
 * Advanced Technology Group (ATG)
 *
 * AUTO-GENERATED by zstdgpu_srt_tool.exe. DO NOT EDIT.
 * Source of truth: zstdgpu_srt_decl.h
 */

#ifndef ZSTDGPU_SRT_GENERATED_ExecuteSequences_H
#define ZSTDGPU_SRT_GENERATED_ExecuteSequences_H

#include "ZstdGpuSrt_BindGroup_LiteralBytes.h"
#include "ZstdGpuSrt_BindGroup_FrameOutput.h"

#ifdef __hlsl_dx_compiler

ZSTDGPU_RO_BUFFER(zstdgpu_Counters)             ZstdInCounters                      : register(t0);
ZSTDGPU_RO_BUFFER(uint32_t)                     ZstdInPerFrameBlockCountCMP         : register(t1);
ZSTDGPU_RO_BUFFER(uint32_t)                     ZstdInBlockSizePrefix               : register(t2);
ZSTDGPU_RO_BUFFER(uint32_t)                     ZstdInBlockDestOffs                 : register(t3);
ZSTDGPU_RO_BUFFER(uint32_t)                     ZstdInDecompressedSequenceLLen      : register(t4);
ZSTDGPU_RO_BUFFER(uint32_t)                     ZstdInDecompressedSequenceMLen      : register(t5);
ZSTDGPU_RO_BUFFER(uint32_t)                     ZstdInDecompressedSequenceOffs      : register(t6);
ZSTDGPU_RO_BUFFER(uint32_t)                     ZstdInGlobalBlockIndexPerCmpBlock   : register(t7);
ZSTDGPU_RO_BUFFER(uint32_t)                     ZstdInPerSeqStreamSeqStart          : register(t8);
ZSTDGPU_RO_BUFFER(zstdgpu_CompressedBlockData)  ZstdInCompressedBlocks              : register(t9);

#define ZSTDGPU_SRT_RS_ExecuteSequences ZSTDGPU_SRT_RS_BIND_GROUP_LiteralBytes ", " ZSTDGPU_SRT_RS_BIND_GROUP_FrameOutput ", SRV(t0)" ", SRV(t1)" ", SRV(t2)" ", SRV(t3)" ", SRV(t4)" ", SRV(t5)" ", SRV(t6)" ", SRV(t7)" ", SRV(t8)" ", SRV(t9)"

static void zstdgpu_Srt_Fill(ZSTDGPU_PARAM_INOUT(zstdgpu_ExecuteSequences_SRT) srt)
{
    zstdgpu_Srt_FillBindGroup_LiteralBytes(srt);
    zstdgpu_Srt_FillBindGroup_FrameOutput(srt);

    srt.inCounters                      = ZstdInCounters;
    srt.inPerFrameBlockCountCMP         = ZstdInPerFrameBlockCountCMP;
    srt.inBlockSizePrefix               = ZstdInBlockSizePrefix;
    srt.inBlockDestOffs                 = ZstdInBlockDestOffs;
    srt.inDecompressedSequenceLLen      = ZstdInDecompressedSequenceLLen;
    srt.inDecompressedSequenceMLen      = ZstdInDecompressedSequenceMLen;
    srt.inDecompressedSequenceOffs      = ZstdInDecompressedSequenceOffs;
    srt.inGlobalBlockIndexPerCmpBlock   = ZstdInGlobalBlockIndexPerCmpBlock;
    srt.inPerSeqStreamSeqStart          = ZstdInPerSeqStreamSeqStart;
    srt.inCompressedBlocks              = ZstdInCompressedBlocks;
}

#else

static void zstdgpu_Srt_Fill(zstdgpu_ExecuteSequences_SRT &srt, const zstdgpu_ResourceDataCpu &cpuRes)
{
    zstdgpu_Srt_FillBindGroup_LiteralBytes(srt, cpuRes);
    zstdgpu_Srt_FillBindGroup_FrameOutput(srt, cpuRes);

    srt.inCounters                      = cpuRes.Counters;
    srt.inPerFrameBlockCountCMP         = cpuRes.PerFrameBlockCountCMP;
    srt.inBlockSizePrefix               = cpuRes.BlockSizePrefix;
    srt.inBlockDestOffs                 = cpuRes.BlockDestOffs;
    srt.inDecompressedSequenceLLen      = cpuRes.DecompressedSequenceLLen;
    srt.inDecompressedSequenceMLen      = cpuRes.DecompressedSequenceMLen;
    srt.inDecompressedSequenceOffs      = cpuRes.DecompressedSequenceOffs;
    srt.inGlobalBlockIndexPerCmpBlock   = cpuRes.GlobalBlockIndexPerCmpBlock;
    srt.inPerSeqStreamSeqStart          = cpuRes.PerSeqStreamSeqStart;
    srt.inCompressedBlocks              = cpuRes.CompressedBlocks;
}

#endif

#endif /* ZSTDGPU_SRT_GENERATED_ExecuteSequences_H */
