/**
 * Copyright (c) Microsoft. All rights reserved.
 * This code is licensed under the MIT License (MIT).
 * THIS CODE IS PROVIDED *AS IS* WITHOUT WARRANTY OF
 * ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING ANY
 * IMPLIED WARRANTIES OF FITNESS FOR A PARTICULAR
 * PURPOSE, MERCHANTABILITY, OR NON-INFRINGEMENT.
 *
 * Advanced Technology Group (ATG)
 *
 * AUTO-GENERATED by zstdgpu_srt_tool.exe. DO NOT EDIT.
 * Source of truth: zstdgpu_srt_decl.h
 */

#ifndef ZSTDGPU_SRT_GENERATED_RS_BIND_GROUP_LiteralStreams_H
#define ZSTDGPU_SRT_GENERATED_RS_BIND_GROUP_LiteralStreams_H

#ifdef __hlsl_dx_compiler

#define ZSTDGPU_SRT_RS_BIND_GROUP_LiteralStreams "DescriptorTable(SRV(t0, space=2, numDescriptors=6), UAV(u0, space=2, numDescriptors=1))"

ZSTDGPU_RO_BUFFER(uint32_t)                 ZstdInLitGroupEndPerHuffmanTable    : register(t0, space2);
ZSTDGPU_RO_BUFFER(zstdgpu_Counters)         ZstdInCounters                      : register(t1, space2);
ZSTDGPU_RO_BUFFER(zstdgpu_LitStreamInfo)    ZstdInLitRefs                       : register(t2, space2);
ZSTDGPU_RO_RAW_BUFFER(uint32_t)             ZstdInCompressedData                : register(t3, space2);
ZSTDGPU_RO_BUFFER(uint32_t)                 ZstdInHufWIdToHufLitId              : register(t4, space2);
ZSTDGPU_RO_BUFFER(uint32_t)                 ZstdInHufLitIdToLitStreamId         : register(t5, space2);
ZSTDGPU_RW_TYPED_BUFFER(uint32_t, uint8_t)  ZstdInOutDecompressedLiterals       : register(u0, space2);

template<typename T>
static void zstdgpu_Srt_FillBindGroup_LiteralStreams(ZSTDGPU_PARAM_INOUT(T) srt)
{
    srt.inLitGroupEndPerHuffmanTable    = ZstdInLitGroupEndPerHuffmanTable;
    srt.inCounters                      = ZstdInCounters;
    srt.inLitRefs                       = ZstdInLitRefs;
    srt.inCompressedData                = ZstdInCompressedData;
    srt.inHufWIdToHufLitId              = ZstdInHufWIdToHufLitId;
    srt.inHufLitIdToLitStreamId         = ZstdInHufLitIdToLitStreamId;
    srt.inoutDecompressedLiterals       = ZstdInOutDecompressedLiterals;
}

#else

template<typename T>
static void zstdgpu_Srt_FillBindGroup_LiteralStreams(T &srt, const zstdgpu_ResourceDataCpu &cpuRes)
{
    srt.inLitGroupEndPerHuffmanTable    = cpuRes.LitGroupEndPerHuffmanTable;
    srt.inCounters                      = cpuRes.Counters;
    srt.inLitRefs                       = cpuRes.LitRefs;
    srt.inCompressedData                = cpuRes.CompressedData;
    srt.inHufWIdToHufLitId              = cpuRes.HufWIdToHufLitId;
    srt.inHufLitIdToLitStreamId         = cpuRes.HufLitIdToLitStreamId;
    srt.inoutDecompressedLiterals       = cpuRes.DecompressedLiterals;
}

#endif /* #ifdef __hlsl_dx_compiler */
#endif /* ZSTDGPU_SRT_GENERATED_RS_BIND_GROUP_LiteralStreams_H */
