/**
 * Copyright (c) Microsoft. All rights reserved.
 * This code is licensed under the MIT License (MIT).
 * THIS CODE IS PROVIDED *AS IS* WITHOUT WARRANTY OF
 * ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING ANY
 * IMPLIED WARRANTIES OF FITNESS FOR A PARTICULAR
 * PURPOSE, MERCHANTABILITY, OR NON-INFRINGEMENT.
 *
 * Advanced Technology Group (ATG)
 *
 * AUTO-GENERATED by zstdgpu_srt_tool.exe. DO NOT EDIT.
 * Source of truth: zstdgpu_srt_decl.h
 */

#ifndef ZSTDGPU_SRT_GENERATED_ParseCompressedBlocks_H
#define ZSTDGPU_SRT_GENERATED_ParseCompressedBlocks_H

#include "ZstdGpuSrt_BindGroup_ParseBlocksWrite.h"

#ifdef __hlsl_dx_compiler

ZSTDGPU_RO_BUFFER(uint32_t)                 ZstdInCompressedData                : register(t0);
ZSTDGPU_RO_BUFFER(zstdgpu_OffsetAndSize)    ZstdInBlocksCMPRefs                 : register(t1);
ZSTDGPU_RO_BUFFER(uint32_t)                 ZstdInPerFrameBlockCountCMP         : register(t2);
ZSTDGPU_RO_BUFFER(uint32_t)                 ZstdInGlobalBlockIndexPerCmpBlock   : register(t3);

typedef struct zstdgpu_ParseCompressedBlocks_Consts
{
    uint32_t    tgOffset;
    uint32_t    workItemCount;
    uint32_t    compressedBufferSizeInBytes;
    uint32_t    frameCount;
} zstdgpu_ParseCompressedBlocks_Consts;

ConstantBuffer<zstdgpu_ParseCompressedBlocks_Consts> ZstdConstants_ParseCompressedBlocks : register(b0);

#define ZSTDGPU_SRT_RS_ParseCompressedBlocks ZSTDGPU_SRT_RS_BIND_GROUP_ParseBlocksWrite ", SRV(t0)" ", SRV(t1)" ", SRV(t2)" ", SRV(t3)" ", RootConstants(b0, num32BitConstants=4)"

static void zstdgpu_Srt_Fill(ZSTDGPU_PARAM_INOUT(zstdgpu_ParseCompressedBlocks_SRT) srt)
{
    zstdgpu_Srt_FillBindGroup_ParseBlocksWrite(srt);

    srt.inCompressedData                = ZstdInCompressedData;
    srt.inBlocksCMPRefs                 = ZstdInBlocksCMPRefs;
    srt.inPerFrameBlockCountCMP         = ZstdInPerFrameBlockCountCMP;
    srt.inGlobalBlockIndexPerCmpBlock   = ZstdInGlobalBlockIndexPerCmpBlock;
    srt.tgOffset                        = ZstdConstants_ParseCompressedBlocks.tgOffset;
    srt.workItemCount                   = ZstdConstants_ParseCompressedBlocks.workItemCount;
    srt.compressedBufferSizeInBytes     = ZstdConstants_ParseCompressedBlocks.compressedBufferSizeInBytes;
    srt.frameCount                      = ZstdConstants_ParseCompressedBlocks.frameCount;
}

#else

static void zstdgpu_Srt_Fill(zstdgpu_ParseCompressedBlocks_SRT &srt, const zstdgpu_ResourceDataCpu &cpuRes,
                             uint32_t     tgOffset,
                             uint32_t     workItemCount,
                             uint32_t     compressedBufferSizeInBytes,
                             uint32_t     frameCount)
{
    zstdgpu_Srt_FillBindGroup_ParseBlocksWrite(srt, cpuRes);

    srt.inCompressedData                = cpuRes.CompressedData;
    srt.inBlocksCMPRefs                 = cpuRes.BlocksCMPRefs;
    srt.inPerFrameBlockCountCMP         = cpuRes.PerFrameBlockCountCMP;
    srt.inGlobalBlockIndexPerCmpBlock   = cpuRes.GlobalBlockIndexPerCmpBlock;
    srt.tgOffset                        = tgOffset;
    srt.workItemCount                   = workItemCount;
    srt.compressedBufferSizeInBytes     = compressedBufferSizeInBytes;
    srt.frameCount                      = frameCount;
}

#endif

static void zstdgpu_Srt_FillInline(ZSTDGPU_PARAM_INOUT(zstdgpu_ParseCompressedBlocks_SRT) srt, uint32_t compressedBlockCount)
{
    srt.compressedBlockCount                            = compressedBlockCount;
}

#endif /* ZSTDGPU_SRT_GENERATED_ParseCompressedBlocks_H */
