/**
 * Copyright (c) Microsoft. All rights reserved.
 * This code is licensed under the MIT License (MIT).
 * THIS CODE IS PROVIDED *AS IS* WITHOUT WARRANTY OF
 * ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING ANY
 * IMPLIED WARRANTIES OF FITNESS FOR A PARTICULAR
 * PURPOSE, MERCHANTABILITY, OR NON-INFRINGEMENT.
 *
 * Advanced Technology Group (ATG)
 *
 * AUTO-GENERATED by zstdgpu_srt_tool.exe. DO NOT EDIT.
 * Source of truth: zstdgpu_srt_decl.h
 */

#ifndef ZSTDGPU_SRT_GENERATED_DecompressSequences_H
#define ZSTDGPU_SRT_GENERATED_DecompressSequences_H

#include "ZstdGpuSrt_BindGroup_SequenceOutputs.h"

#ifdef __hlsl_dx_compiler

ZSTDGPU_RO_BUFFER(zstdgpu_Counters)         ZstdInCounters              : register(t0);
ZSTDGPU_RO_RAW_BUFFER(uint32_t)             ZstdInCompressedData        : register(t1);
ZSTDGPU_RO_BUFFER(zstdgpu_OffsetAndSize)    ZstdInSeqStreamToRef        : register(t2);
ZSTDGPU_RO_BUFFER(uint32_t)                 ZstdInSeqStreamToLLenFseId  : register(t3);
ZSTDGPU_RO_BUFFER(uint32_t)                 ZstdInSeqStreamToOffsFseId  : register(t4);
ZSTDGPU_RO_BUFFER(uint32_t)                 ZstdInSeqStreamToMLenFseId  : register(t5);
ZSTDGPU_RO_BUFFER(uint32_t)                 ZstdInSeqStreamToBlockId    : register(t6);
ZSTDGPU_RO_BUFFER(zstdgpu_FseInfo)          ZstdInFseInfos              : register(t7);
ZSTDGPU_RO_BUFFER(uint32_t)                 ZstdInPerSeqStreamSeqStart  : register(t8);
ZSTDGPU_RO_BUFFER(uint32_t)                 ZstdInFseElems              : register(t9);

typedef struct zstdgpu_DecompressSequences_Consts
{
    uint32_t    tgOffset;
    uint32_t    workItemCount;
} zstdgpu_DecompressSequences_Consts;

ConstantBuffer<zstdgpu_DecompressSequences_Consts> ZstdConstants_DecompressSequences : register(b0);

#define ZSTDGPU_SRT_RS_DecompressSequences ZSTDGPU_SRT_RS_BIND_GROUP_SequenceOutputs ", SRV(t0)" ", SRV(t1)" ", SRV(t2)" ", SRV(t3)" ", SRV(t4)" ", SRV(t5)" ", SRV(t6)" ", SRV(t7)" ", SRV(t8)" ", SRV(t9)" ", RootConstants(b0, num32BitConstants=2)"

static void zstdgpu_Srt_Fill(ZSTDGPU_PARAM_INOUT(zstdgpu_DecompressSequences_SRT) srt)
{
    zstdgpu_Srt_FillBindGroup_SequenceOutputs(srt);

    srt.inCounters              = ZstdInCounters;
    srt.inCompressedData        = ZstdInCompressedData;
    srt.inSeqStreamToRef        = ZstdInSeqStreamToRef;
    srt.inSeqStreamToLLenFseId  = ZstdInSeqStreamToLLenFseId;
    srt.inSeqStreamToOffsFseId  = ZstdInSeqStreamToOffsFseId;
    srt.inSeqStreamToMLenFseId  = ZstdInSeqStreamToMLenFseId;
    srt.inSeqStreamToBlockId    = ZstdInSeqStreamToBlockId;
    srt.inFseInfos              = ZstdInFseInfos;
    srt.inPerSeqStreamSeqStart  = ZstdInPerSeqStreamSeqStart;
    srt.inFseElems              = ZstdInFseElems;
    srt.tgOffset                = ZstdConstants_DecompressSequences.tgOffset;
    srt.workItemCount           = ZstdConstants_DecompressSequences.workItemCount;
}

#else

static void zstdgpu_Srt_Fill(zstdgpu_DecompressSequences_SRT &srt, const zstdgpu_ResourceDataCpu &cpuRes,
                             uint32_t     tgOffset,
                             uint32_t     workItemCount)
{
    zstdgpu_Srt_FillBindGroup_SequenceOutputs(srt, cpuRes);

    srt.inCounters              = cpuRes.Counters;
    srt.inCompressedData        = cpuRes.CompressedData;
    srt.inSeqStreamToRef        = cpuRes.SeqStreamToRef;
    srt.inSeqStreamToLLenFseId  = cpuRes.SeqStreamToLLenFseId;
    srt.inSeqStreamToOffsFseId  = cpuRes.SeqStreamToOffsFseId;
    srt.inSeqStreamToMLenFseId  = cpuRes.SeqStreamToMLenFseId;
    srt.inSeqStreamToBlockId    = cpuRes.SeqStreamToBlockId;
    srt.inFseInfos              = cpuRes.FseInfos;
    srt.inPerSeqStreamSeqStart  = cpuRes.PerSeqStreamSeqStart;
    srt.inFseElems              = cpuRes.FseElems;
    srt.tgOffset                = tgOffset;
    srt.workItemCount           = workItemCount;
}

#endif

#endif /* ZSTDGPU_SRT_GENERATED_DecompressSequences_H */
