/**
 * Copyright (c) Microsoft. All rights reserved.
 * This code is licensed under the MIT License (MIT).
 * THIS CODE IS PROVIDED *AS IS* WITHOUT WARRANTY OF
 * ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING ANY
 * IMPLIED WARRANTIES OF FITNESS FOR A PARTICULAR
 * PURPOSE, MERCHANTABILITY, OR NON-INFRINGEMENT.
 *
 * Advanced Technology Group (ATG)
 *
 * AUTO-GENERATED by zstdgpu_srt_tool.exe. DO NOT EDIT.
 * Source of truth: zstdgpu_srt_decl.h
 */

#ifndef ZSTDGPU_SRT_GENERATED_RS_BIND_GROUP_ParseFrames_H
#define ZSTDGPU_SRT_GENERATED_RS_BIND_GROUP_ParseFrames_H

#ifdef __hlsl_dx_compiler

#define ZSTDGPU_SRT_RS_BIND_GROUP_ParseFrames "DescriptorTable(SRV(t0, space=1, numDescriptors=2), UAV(u0, space=1, numDescriptors=14))"

ZSTDGPU_RO_BUFFER(uint32_t)                 ZstdInCompressedData                    : register(t0, space1);
ZSTDGPU_RO_BUFFER(zstdgpu_OffsetAndSize)    ZstdInFramesRefs                        : register(t1, space1);
ZSTDGPU_RW_BUFFER(zstdgpu_Counters)         ZstdInOutCounters                       : register(u0, space1);
ZSTDGPU_RW_BUFFER(uint32_t)                 ZstdInOutPerFrameBlockCountRAW          : register(u1, space1);
ZSTDGPU_RW_BUFFER(uint32_t)                 ZstdInOutPerFrameBlockCountRLE          : register(u2, space1);
ZSTDGPU_RW_BUFFER(uint32_t)                 ZstdInOutPerFrameBlockCountCMP          : register(u3, space1);
ZSTDGPU_RW_BUFFER(uint32_t)                 ZstdInOutPerFrameBlockCountAll          : register(u4, space1);
ZSTDGPU_RW_BUFFER(uint32_t)                 ZstdInOutRawBlockSizePrefix             : register(u5, space1);
ZSTDGPU_RW_BUFFER(uint32_t)                 ZstdInOutRleBlockSizePrefix             : register(u6, space1);
ZSTDGPU_RW_BUFFER(zstdgpu_OffsetAndSize)    ZstdInOutBlocksRAWRefs                  : register(u7, space1);
ZSTDGPU_RW_BUFFER(zstdgpu_OffsetAndSize)    ZstdInOutBlocksRLERefs                  : register(u8, space1);
ZSTDGPU_RW_BUFFER(zstdgpu_OffsetAndSize)    ZstdInOutBlocksCMPRefs                  : register(u9, space1);
ZSTDGPU_RW_BUFFER(uint32_t)                 ZstdInOutBlockSizePrefix                : register(u10, space1);
ZSTDGPU_RW_BUFFER(uint32_t)                 ZstdInOutGlobalBlockIndexPerRawBlock    : register(u11, space1);
ZSTDGPU_RW_BUFFER(uint32_t)                 ZstdInOutGlobalBlockIndexPerRleBlock    : register(u12, space1);
ZSTDGPU_RW_BUFFER(uint32_t)                 ZstdInOutGlobalBlockIndexPerCmpBlock    : register(u13, space1);

template<typename T>
static void zstdgpu_Srt_FillBindGroup_ParseFrames(ZSTDGPU_PARAM_INOUT(T) srt)
{
    srt.inCompressedData                    = ZstdInCompressedData;
    srt.inFramesRefs                        = ZstdInFramesRefs;
    srt.inoutCounters                       = ZstdInOutCounters;
    srt.inoutPerFrameBlockCountRAW          = ZstdInOutPerFrameBlockCountRAW;
    srt.inoutPerFrameBlockCountRLE          = ZstdInOutPerFrameBlockCountRLE;
    srt.inoutPerFrameBlockCountCMP          = ZstdInOutPerFrameBlockCountCMP;
    srt.inoutPerFrameBlockCountAll          = ZstdInOutPerFrameBlockCountAll;
    srt.inoutRawBlockSizePrefix             = ZstdInOutRawBlockSizePrefix;
    srt.inoutRleBlockSizePrefix             = ZstdInOutRleBlockSizePrefix;
    srt.inoutBlocksRAWRefs                  = ZstdInOutBlocksRAWRefs;
    srt.inoutBlocksRLERefs                  = ZstdInOutBlocksRLERefs;
    srt.inoutBlocksCMPRefs                  = ZstdInOutBlocksCMPRefs;
    srt.inoutBlockSizePrefix                = ZstdInOutBlockSizePrefix;
    srt.inoutGlobalBlockIndexPerRawBlock    = ZstdInOutGlobalBlockIndexPerRawBlock;
    srt.inoutGlobalBlockIndexPerRleBlock    = ZstdInOutGlobalBlockIndexPerRleBlock;
    srt.inoutGlobalBlockIndexPerCmpBlock    = ZstdInOutGlobalBlockIndexPerCmpBlock;
}

#else

template<typename T>
static void zstdgpu_Srt_FillBindGroup_ParseFrames(T &srt, const zstdgpu_ResourceDataCpu &cpuRes)
{
    srt.inCompressedData                    = cpuRes.CompressedData;
    srt.inFramesRefs                        = cpuRes.FramesRefs;
    srt.inoutCounters                       = cpuRes.Counters;
    srt.inoutPerFrameBlockCountRAW          = cpuRes.PerFrameBlockCountRAW;
    srt.inoutPerFrameBlockCountRLE          = cpuRes.PerFrameBlockCountRLE;
    srt.inoutPerFrameBlockCountCMP          = cpuRes.PerFrameBlockCountCMP;
    srt.inoutPerFrameBlockCountAll          = cpuRes.PerFrameBlockCountAll;
    srt.inoutRawBlockSizePrefix             = cpuRes.RawBlockSizePrefix;
    srt.inoutRleBlockSizePrefix             = cpuRes.RleBlockSizePrefix;
    srt.inoutBlocksRAWRefs                  = cpuRes.BlocksRAWRefs;
    srt.inoutBlocksRLERefs                  = cpuRes.BlocksRLERefs;
    srt.inoutBlocksCMPRefs                  = cpuRes.BlocksCMPRefs;
    srt.inoutBlockSizePrefix                = cpuRes.BlockSizePrefix;
    srt.inoutGlobalBlockIndexPerRawBlock    = cpuRes.GlobalBlockIndexPerRawBlock;
    srt.inoutGlobalBlockIndexPerRleBlock    = cpuRes.GlobalBlockIndexPerRleBlock;
    srt.inoutGlobalBlockIndexPerCmpBlock    = cpuRes.GlobalBlockIndexPerCmpBlock;
}

#endif /* #ifdef __hlsl_dx_compiler */
#endif /* ZSTDGPU_SRT_GENERATED_RS_BIND_GROUP_ParseFrames_H */
