/**
 * Copyright (c) Microsoft. All rights reserved.
 * This code is licensed under the MIT License (MIT).
 * THIS CODE IS PROVIDED *AS IS* WITHOUT WARRANTY OF
 * ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING ANY
 * IMPLIED WARRANTIES OF FITNESS FOR A PARTICULAR
 * PURPOSE, MERCHANTABILITY, OR NON-INFRINGEMENT.
 *
 * Advanced Technology Group (ATG)
 *
 * AUTO-GENERATED by zstdgpu_srt_tool.exe. DO NOT EDIT.
 * Source of truth: zstdgpu_srt_decl.h
 */

#ifndef ZSTDGPU_SRT_GENERATED_Memset_H
#define ZSTDGPU_SRT_GENERATED_Memset_H

#ifdef __hlsl_dx_compiler

ZSTDGPU_RW_BUFFER(uint32_t) ZstdInOutDest   : register(u0);

typedef struct zstdgpu_Memset_Consts
{
    uint32_t    tgOffset;
    uint32_t    workItemCount;
    uint32_t    value;
} zstdgpu_Memset_Consts;

ConstantBuffer<zstdgpu_Memset_Consts> ZstdConstants_Memset : register(b0);

#define ZSTDGPU_SRT_RS_Memset "UAV(u0)" ", RootConstants(b0, num32BitConstants=3)"

static void zstdgpu_Srt_Fill(ZSTDGPU_PARAM_INOUT(zstdgpu_Memset_SRT) srt)
{
    srt.inoutDest       = ZstdInOutDest;
    srt.tgOffset        = ZstdConstants_Memset.tgOffset;
    srt.workItemCount   = ZstdConstants_Memset.workItemCount;
    srt.value           = ZstdConstants_Memset.value;
}

#else

static void zstdgpu_Srt_Fill(zstdgpu_Memset_SRT &srt, const zstdgpu_ResourceDataCpu &,
                             ZSTDGPU_RW_BUFFER(uint32_t)  inoutDest,
                             uint32_t                     tgOffset,
                             uint32_t                     workItemCount,
                             uint32_t                     value)
{
    srt.inoutDest       = inoutDest;
    srt.tgOffset        = tgOffset;
    srt.workItemCount   = workItemCount;
    srt.value           = value;
}

static void zstdgpu_Srt_Fill_SeqStreamMinIdx(zstdgpu_Memset_SRT &srt, const zstdgpu_ResourceDataCpu &cpuRes, uint32_t tgOffset, uint32_t workItemCount, uint32_t value)
{
    zstdgpu_Srt_Fill(srt, cpuRes, cpuRes.PerFrameSeqStreamMinIdx, tgOffset, workItemCount, value);
}

static void zstdgpu_Srt_Fill_BlockCountRawLookback(zstdgpu_Memset_SRT &srt, const zstdgpu_ResourceDataCpu &cpuRes, uint32_t tgOffset, uint32_t workItemCount, uint32_t value)
{
    zstdgpu_Srt_Fill(srt, cpuRes, cpuRes.PerFrameBlockCountRAWLookback, tgOffset, workItemCount, value);
}

static void zstdgpu_Srt_Fill_BlockCountRleLookback(zstdgpu_Memset_SRT &srt, const zstdgpu_ResourceDataCpu &cpuRes, uint32_t tgOffset, uint32_t workItemCount, uint32_t value)
{
    zstdgpu_Srt_Fill(srt, cpuRes, cpuRes.PerFrameBlockCountRLELookback, tgOffset, workItemCount, value);
}

static void zstdgpu_Srt_Fill_BlockCountCmpLookback(zstdgpu_Memset_SRT &srt, const zstdgpu_ResourceDataCpu &cpuRes, uint32_t tgOffset, uint32_t workItemCount, uint32_t value)
{
    zstdgpu_Srt_Fill(srt, cpuRes, cpuRes.PerFrameBlockCountCMPLookback, tgOffset, workItemCount, value);
}

static void zstdgpu_Srt_Fill_BlockCountAllLookback(zstdgpu_Memset_SRT &srt, const zstdgpu_ResourceDataCpu &cpuRes, uint32_t tgOffset, uint32_t workItemCount, uint32_t value)
{
    zstdgpu_Srt_Fill(srt, cpuRes, cpuRes.PerFrameBlockCountAllLookback, tgOffset, workItemCount, value);
}

static void zstdgpu_Srt_Fill_RawBlockSizePrefixLookback(zstdgpu_Memset_SRT &srt, const zstdgpu_ResourceDataCpu &cpuRes, uint32_t tgOffset, uint32_t workItemCount, uint32_t value)
{
    zstdgpu_Srt_Fill(srt, cpuRes, cpuRes.RawBlockSizePrefixLookback, tgOffset, workItemCount, value);
}

static void zstdgpu_Srt_Fill_RleBlockSizePrefixLookback(zstdgpu_Memset_SRT &srt, const zstdgpu_ResourceDataCpu &cpuRes, uint32_t tgOffset, uint32_t workItemCount, uint32_t value)
{
    zstdgpu_Srt_Fill(srt, cpuRes, cpuRes.RleBlockSizePrefixLookback, tgOffset, workItemCount, value);
}

static void zstdgpu_Srt_Fill_LitGroupEndPerHuffmanTableLookback(zstdgpu_Memset_SRT &srt, const zstdgpu_ResourceDataCpu &cpuRes, uint32_t tgOffset, uint32_t workItemCount, uint32_t value)
{
    zstdgpu_Srt_Fill(srt, cpuRes, cpuRes.LitGroupEndPerHuffmanTableLookback, tgOffset, workItemCount, value);
}

static void zstdgpu_Srt_Fill_PerSeqStreamFinalOffset1Lookback(zstdgpu_Memset_SRT &srt, const zstdgpu_ResourceDataCpu &cpuRes, uint32_t tgOffset, uint32_t workItemCount, uint32_t value)
{
    zstdgpu_Srt_Fill(srt, cpuRes, cpuRes.PerSeqStreamFinalOffset1Lookback, tgOffset, workItemCount, value);
}

static void zstdgpu_Srt_Fill_PerSeqStreamFinalOffset2Lookback(zstdgpu_Memset_SRT &srt, const zstdgpu_ResourceDataCpu &cpuRes, uint32_t tgOffset, uint32_t workItemCount, uint32_t value)
{
    zstdgpu_Srt_Fill(srt, cpuRes, cpuRes.PerSeqStreamFinalOffset2Lookback, tgOffset, workItemCount, value);
}

static void zstdgpu_Srt_Fill_PerSeqStreamFinalOffset3Lookback(zstdgpu_Memset_SRT &srt, const zstdgpu_ResourceDataCpu &cpuRes, uint32_t tgOffset, uint32_t workItemCount, uint32_t value)
{
    zstdgpu_Srt_Fill(srt, cpuRes, cpuRes.PerSeqStreamFinalOffset3Lookback, tgOffset, workItemCount, value);
}

static void zstdgpu_Srt_Fill_SeqCountPrefixLookback(zstdgpu_Memset_SRT &srt, const zstdgpu_ResourceDataCpu &cpuRes, uint32_t tgOffset, uint32_t workItemCount, uint32_t value)
{
    zstdgpu_Srt_Fill(srt, cpuRes, cpuRes.SeqCountPrefixLookback, tgOffset, workItemCount, value);
}

static void zstdgpu_Srt_Fill_BlockSeqCountPrefixLookback(zstdgpu_Memset_SRT &srt, const zstdgpu_ResourceDataCpu &cpuRes, uint32_t tgOffset, uint32_t workItemCount, uint32_t value)
{
    zstdgpu_Srt_Fill(srt, cpuRes, cpuRes.BlockSeqCountPrefixLookback, tgOffset, workItemCount, value);
}

static void zstdgpu_Srt_Fill_LitStreamCountPrefixLookback(zstdgpu_Memset_SRT &srt, const zstdgpu_ResourceDataCpu &cpuRes, uint32_t tgOffset, uint32_t workItemCount, uint32_t value)
{
    zstdgpu_Srt_Fill(srt, cpuRes, cpuRes.LitStreamCountPrefixLookback, tgOffset, workItemCount, value);
}

static void zstdgpu_Srt_Fill_HufLitCompactionLookback(zstdgpu_Memset_SRT &srt, const zstdgpu_ResourceDataCpu &cpuRes, uint32_t tgOffset, uint32_t workItemCount, uint32_t value)
{
    zstdgpu_Srt_Fill(srt, cpuRes, cpuRes.HufLitCompactionLookback, tgOffset, workItemCount, value);
}

static void zstdgpu_Srt_Fill_FseIndexLookbackLLen(zstdgpu_Memset_SRT &srt, const zstdgpu_ResourceDataCpu &cpuRes, uint32_t tgOffset, uint32_t workItemCount, uint32_t value)
{
    zstdgpu_Srt_Fill(srt, cpuRes, cpuRes.FseIndexLookbackLLen, tgOffset, workItemCount, value);
}

static void zstdgpu_Srt_Fill_FseIndexLookbackOffs(zstdgpu_Memset_SRT &srt, const zstdgpu_ResourceDataCpu &cpuRes, uint32_t tgOffset, uint32_t workItemCount, uint32_t value)
{
    zstdgpu_Srt_Fill(srt, cpuRes, cpuRes.FseIndexLookbackOffs, tgOffset, workItemCount, value);
}

static void zstdgpu_Srt_Fill_FseIndexLookbackMLen(zstdgpu_Memset_SRT &srt, const zstdgpu_ResourceDataCpu &cpuRes, uint32_t tgOffset, uint32_t workItemCount, uint32_t value)
{
    zstdgpu_Srt_Fill(srt, cpuRes, cpuRes.FseIndexLookbackMLen, tgOffset, workItemCount, value);
}

static void zstdgpu_Srt_Fill_HufWIdToHufLitId(zstdgpu_Memset_SRT &srt, const zstdgpu_ResourceDataCpu &cpuRes, uint32_t tgOffset, uint32_t workItemCount, uint32_t value)
{
    zstdgpu_Srt_Fill(srt, cpuRes, cpuRes.HufWIdToHufLitId, tgOffset, workItemCount, value);
}

static void zstdgpu_Srt_Fill_BlockSizePrefixLookback(zstdgpu_Memset_SRT &srt, const zstdgpu_ResourceDataCpu &cpuRes, uint32_t tgOffset, uint32_t workItemCount, uint32_t value)
{
    zstdgpu_Srt_Fill(srt, cpuRes, cpuRes.BlockSizePrefixLookback, tgOffset, workItemCount, value);
}

#endif

#endif /* ZSTDGPU_SRT_GENERATED_Memset_H */
