/**
 * Copyright (c) Microsoft. All rights reserved.
 * This code is licensed under the MIT License (MIT).
 * THIS CODE IS PROVIDED *AS IS* WITHOUT WARRANTY OF
 * ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING ANY
 * IMPLIED WARRANTIES OF FITNESS FOR A PARTICULAR
 * PURPOSE, MERCHANTABILITY, OR NON-INFRINGEMENT.
 *
 * Advanced Technology Group (ATG)
 *
 * AUTO-GENERATED by zstdgpu_srt_tool.exe. DO NOT EDIT.
 * Source of truth: zstdgpu_srt_decl.h
 */

#ifndef ZSTDGPU_SRT_GENERATED_InitHuffmanTable_H
#define ZSTDGPU_SRT_GENERATED_InitHuffmanTable_H

#include "ZstdGpuSrt_BindGroup_HuffmanWeights.h"
#include "ZstdGpuSrt_BindGroup_HuffmanTableWrite.h"

#ifdef __hlsl_dx_compiler

ZSTDGPU_RO_BUFFER(zstdgpu_Counters) ZstdInCounters      : register(t0);
ZSTDGPU_RO_BUFFER(uint32_t)         ZstdInDispatchArgs  : register(t1);

typedef struct zstdgpu_InitHuffmanTable_Consts
{
    uint32_t    tgOffset;
    uint32_t    workItemCount;
    uint32_t    fseCompressed;
} zstdgpu_InitHuffmanTable_Consts;

ConstantBuffer<zstdgpu_InitHuffmanTable_Consts> ZstdConstants_InitHuffmanTable : register(b0);

#define ZSTDGPU_SRT_RS_InitHuffmanTable ZSTDGPU_SRT_RS_BIND_GROUP_HuffmanWeights ", " ZSTDGPU_SRT_RS_BIND_GROUP_HuffmanTableWrite ", SRV(t0)" ", SRV(t1)" ", RootConstants(b0, num32BitConstants=3)"

static void zstdgpu_Srt_Fill(ZSTDGPU_PARAM_INOUT(zstdgpu_InitHuffmanTable_SRT) srt)
{
    zstdgpu_Srt_FillBindGroup_HuffmanWeights(srt);
    zstdgpu_Srt_FillBindGroup_HuffmanTableWrite(srt);

    srt.inCounters      = ZstdInCounters;
    srt.inDispatchArgs  = ZstdInDispatchArgs;
    srt.tgOffset        = ZstdConstants_InitHuffmanTable.tgOffset;
    srt.workItemCount   = ZstdConstants_InitHuffmanTable.workItemCount;
    srt.fseCompressed   = ZstdConstants_InitHuffmanTable.fseCompressed;
    // fixup code for executeIndirectWorkaround
    ZSTDGPU_BRANCH if (int32_t(srt.workItemCount) < 0)
    {
        const uint32_t slot = ~srt.workItemCount;
        const uint32_t baseIdx = slot * kzstdgpu_DispatchSlot_StrideInUInt32;
        srt.workItemCount = ZstdInDispatchArgs[baseIdx + 1];
    }
}

#else

static void zstdgpu_Srt_Fill(zstdgpu_InitHuffmanTable_SRT &srt, const zstdgpu_ResourceDataCpu &cpuRes,
                             uint32_t     tgOffset,
                             uint32_t     workItemCount,
                             uint32_t     fseCompressed)
{
    zstdgpu_Srt_FillBindGroup_HuffmanWeights(srt, cpuRes);
    zstdgpu_Srt_FillBindGroup_HuffmanTableWrite(srt, cpuRes);

    srt.inCounters      = cpuRes.Counters;
    srt.inDispatchArgs  = cpuRes.DispatchArgs;
    srt.tgOffset        = tgOffset;
    srt.workItemCount   = workItemCount;
    srt.fseCompressed   = fseCompressed;
}

#endif

#endif /* ZSTDGPU_SRT_GENERATED_InitHuffmanTable_H */
