/**
 * Copyright (c) Microsoft. All rights reserved.
 * This code is licensed under the MIT License (MIT).
 * THIS CODE IS PROVIDED *AS IS* WITHOUT WARRANTY OF
 * ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING ANY
 * IMPLIED WARRANTIES OF FITNESS FOR A PARTICULAR
 * PURPOSE, MERCHANTABILITY, OR NON-INFRINGEMENT.
 *
 * Advanced Technology Group (ATG)
 *
 * AUTO-GENERATED by zstdgpu_srt_tool.exe. DO NOT EDIT.
 * Source of truth: zstdgpu_srt_decl.h
 */

#ifndef ZSTDGPU_SRT_GENERATED_BIND_H
#define ZSTDGPU_SRT_GENERATED_BIND_H

/** Stable resource ids -- the barrier tracker indexes its state array with these. */
enum
{
    kzstdgpu_SrtRes_CompressedData                      = 0,
    kzstdgpu_SrtRes_FramesRefs                          = 1,
    kzstdgpu_SrtRes_Counters                            = 2,
    kzstdgpu_SrtRes_PerFrameBlockCountRAW               = 3,
    kzstdgpu_SrtRes_PerFrameBlockCountRLE               = 4,
    kzstdgpu_SrtRes_PerFrameBlockCountCMP               = 5,
    kzstdgpu_SrtRes_PerFrameBlockCountAll               = 6,
    kzstdgpu_SrtRes_RawBlockSizePrefix                  = 7,
    kzstdgpu_SrtRes_RleBlockSizePrefix                  = 8,
    kzstdgpu_SrtRes_BlocksRAWRefs                       = 9,
    kzstdgpu_SrtRes_BlocksRLERefs                       = 10,
    kzstdgpu_SrtRes_BlocksCMPRefs                       = 11,
    kzstdgpu_SrtRes_BlockSizePrefix                     = 12,
    kzstdgpu_SrtRes_GlobalBlockIndexPerRawBlock         = 13,
    kzstdgpu_SrtRes_GlobalBlockIndexPerRleBlock         = 14,
    kzstdgpu_SrtRes_GlobalBlockIndexPerCmpBlock         = 15,
    kzstdgpu_SrtRes_FrameStatus                         = 16,
    kzstdgpu_SrtRes_LitGroupEndPerHuffmanTable          = 17,
    kzstdgpu_SrtRes_LitRefs                             = 18,
    kzstdgpu_SrtRes_HufWIdToHufLitId                    = 19,
    kzstdgpu_SrtRes_HufLitIdToLitStreamId               = 20,
    kzstdgpu_SrtRes_DecompressedLiterals                = 21,
    kzstdgpu_SrtRes_HuffmanTableInfo                    = 22,
    kzstdgpu_SrtRes_HuffmanTableCodeAndSymbol           = 23,
    kzstdgpu_SrtRes_HuffmanTableRankIndex               = 24,
    kzstdgpu_SrtRes_DecompressedHuffmanWeights          = 25,
    kzstdgpu_SrtRes_DecompressedHuffmanWeightCount      = 26,
    kzstdgpu_SrtRes_DecompressedSequenceLLen            = 27,
    kzstdgpu_SrtRes_DecompressedSequenceMLen            = 28,
    kzstdgpu_SrtRes_DecompressedSequenceOffs            = 29,
    kzstdgpu_SrtRes_PerSeqStreamFinalOffset1            = 30,
    kzstdgpu_SrtRes_PerSeqStreamFinalOffset2            = 31,
    kzstdgpu_SrtRes_PerSeqStreamFinalOffset3            = 32,
    kzstdgpu_SrtRes_FseProbs                            = 33,
    kzstdgpu_SrtRes_UnCompressedFramesData              = 34,
    kzstdgpu_SrtRes_FseProbsDefault                     = 35,
    kzstdgpu_SrtRes_FseInfos                            = 36,
    kzstdgpu_SrtRes_FseElems                            = 37,
    kzstdgpu_SrtRes_CompressedBlocks                    = 38,
    kzstdgpu_SrtRes_HufRefs                             = 39,
    kzstdgpu_SrtRes_SeqStreamToRef                      = 40,
    kzstdgpu_SrtRes_SeqStreamToLLenFseId                = 41,
    kzstdgpu_SrtRes_SeqStreamToOffsFseId                = 42,
    kzstdgpu_SrtRes_SeqStreamToMLenFseId                = 43,
    kzstdgpu_SrtRes_SeqStreamToBlockId                  = 44,
    kzstdgpu_SrtRes_PerFrameSeqStreamMinIdx             = 45,
    kzstdgpu_SrtRes_PerSeqStreamSeqStart                = 46,
    kzstdgpu_SrtRes_SeqCountPrefixLookback              = 47,
    kzstdgpu_SrtRes_BlockSeqCountPrefixLookback         = 48,
    kzstdgpu_SrtRes_LitStreamCountPrefixLookback        = 49,
    kzstdgpu_SrtRes_HufLitIdToHufWId_DBG                = 50,
    kzstdgpu_SrtRes_HufLitCompactionLookback            = 51,
    kzstdgpu_SrtRes_PerFrameBlockCountRAWLookback       = 52,
    kzstdgpu_SrtRes_PerFrameBlockCountRLELookback       = 53,
    kzstdgpu_SrtRes_PerFrameBlockCountCMPLookback       = 54,
    kzstdgpu_SrtRes_PerFrameBlockCountAllLookback       = 55,
    kzstdgpu_SrtRes_RawBlockSizePrefixLookback          = 56,
    kzstdgpu_SrtRes_RleBlockSizePrefixLookback          = 57,
    kzstdgpu_SrtRes_LitGroupEndPerHuffmanTableLookback  = 58,
    kzstdgpu_SrtRes_PerSeqStreamFinalOffset1Lookback    = 59,
    kzstdgpu_SrtRes_PerSeqStreamFinalOffset2Lookback    = 60,
    kzstdgpu_SrtRes_PerSeqStreamFinalOffset3Lookback    = 61,
    kzstdgpu_SrtRes_FseIndexLookbackLLen                = 62,
    kzstdgpu_SrtRes_FseIndexLookbackOffs                = 63,
    kzstdgpu_SrtRes_FseIndexLookbackMLen                = 64,
    kzstdgpu_SrtRes_BlockSizePrefixLookback             = 65,
    kzstdgpu_SrtRes_BlockDestOffs                       = 66,
    kzstdgpu_SrtRes_DispatchArgs                        = 67,
    kzstdgpu_SrtRes_DispatchCnts                        = 68,
    kzstdgpu_SrtRes_Predicate                           = 69,
    kzstdgpu_SrtRes_UnCompressedFramesRefs              = 70,
    kzstdgpu_SrtRes_DestSequenceOffsets                 = 71,
    kzstdgpu_SrtRes_Count                               = 72
};

/**
 * Root parameter index of an SRT's constants block bound that must be set by Indirect arguments
 * Pass this to ZSTDGPU_DISPATCH32_CMD_SIG or zstdgpu_Dispatch32Bit instead of a hand-written number.
 */
static const uint32_t kzstdgpu_SrtConstsRootSlot_ParseFrames              = 1;
static const uint32_t kzstdgpu_SrtConstsRootSlot_Memset                   = 1;
static const uint32_t kzstdgpu_SrtConstsRootSlot_DecompressLiterals       = 3;
static const uint32_t kzstdgpu_SrtConstsRootSlot_InitHuffmanTableAndDecompressLiterals = 2;
static const uint32_t kzstdgpu_SrtConstsRootSlot_PrefixSum                = 2;
static const uint32_t kzstdgpu_SrtConstsRootSlot_PropagateFseIndex        = 2;
static const uint32_t kzstdgpu_SrtConstsRootSlot_ComputePrefixSum         = 5;
static const uint32_t kzstdgpu_SrtConstsRootSlot_PrefixSequenceOffsets    = 10;
static const uint32_t kzstdgpu_SrtConstsRootSlot_UpdateDispatchArgs       = 4;
static const uint32_t kzstdgpu_SrtConstsRootSlot_DecompressHuffmanWeights = 6;
static const uint32_t kzstdgpu_SrtConstsRootSlot_DecodeHuffmanWeights     = 4;
static const uint32_t kzstdgpu_SrtConstsRootSlot_InitHuffmanTable         = 3;
static const uint32_t kzstdgpu_SrtConstsRootSlot_DecompressSequences      = 11;
static const uint32_t kzstdgpu_SrtConstsRootSlot_FinaliseSequenceOffsets  = 9;
static const uint32_t kzstdgpu_SrtConstsRootSlot_InitFseTable             = 4;
static const uint32_t kzstdgpu_SrtConstsRootSlot_ComputeDestBlockOffsets  = 4;
static const uint32_t kzstdgpu_SrtConstsRootSlot_ComputeDestSequenceOffsets = 6;
static const uint32_t kzstdgpu_SrtConstsRootSlot_MemsetMemcpy             = 7;
static const uint32_t kzstdgpu_SrtConstsRootSlot_InitResources            = 2;
static const uint32_t kzstdgpu_SrtConstsRootSlot_ParseCompressedBlocks    = 5;

/**
 * Descriptors each stage's bind groups occupy in the shader-visible heap.
 * Known at generation time; heap sizing needs it before any descriptor exists.
 */
static const uint32_t zstdgpu_kSrtStageDescCount[] = { 21, 43, 29 };

/** GPU descriptor table handles of the bind groups that live in stage 0. */
struct zstdgpu_Srt_BindGroups_Stage0
{
    D3D12_GPU_DESCRIPTOR_HANDLE ParseFrames;
    D3D12_GPU_DESCRIPTOR_HANDLE FseInit;
};

/** GPU descriptor table handles of the bind groups that live in stage 1. */
struct zstdgpu_Srt_BindGroups_Stage1
{
    D3D12_GPU_DESCRIPTOR_HANDLE ParseFrames;
    D3D12_GPU_DESCRIPTOR_HANDLE FseInit;
    D3D12_GPU_DESCRIPTOR_HANDLE ParseBlocksWrite;
};

/** GPU descriptor table handles of the bind groups that live in stage 2. */
struct zstdgpu_Srt_BindGroups_Stage2
{
    D3D12_GPU_DESCRIPTOR_HANDLE LiteralStreams;
    D3D12_GPU_DESCRIPTOR_HANDLE HuffmanTable;
    D3D12_GPU_DESCRIPTOR_HANDLE LiteralDwords;
    D3D12_GPU_DESCRIPTOR_HANDLE HuffmanWeights;
    D3D12_GPU_DESCRIPTOR_HANDLE HuffmanWeightsWrite;
    D3D12_GPU_DESCRIPTOR_HANDLE HuffmanTableWrite;
    D3D12_GPU_DESCRIPTOR_HANDLE SequenceOutputs;
    D3D12_GPU_DESCRIPTOR_HANDLE LiteralBytes;
    D3D12_GPU_DESCRIPTOR_HANDLE FseProbsRead;
    D3D12_GPU_DESCRIPTOR_HANDLE FrameOutput;
};

/**
 * Everything a generated binder needs: the shader-visible descriptor heap, the compute
 * PSO/root-signature pair of every SRT, and the per-stage bind group handles.
 */
struct zstdgpu_Srts
{
    ID3D12DescriptorHeap         *heap;
    uint32_t                      heapOffset;

    d3d12aid_ComputeRsPs          ParseFrames;
    d3d12aid_ComputeRsPs          Memset;
    d3d12aid_ComputeRsPs          DecompressLiterals;
    d3d12aid_ComputeRsPs          InitHuffmanTableAndDecompressLiterals;
    d3d12aid_ComputeRsPs          PrefixSum;
    d3d12aid_ComputeRsPs          PropagateFseIndex;
    d3d12aid_ComputeRsPs          ComputePrefixSum;
    d3d12aid_ComputeRsPs          PrefixSequenceOffsets;
    d3d12aid_ComputeRsPs          UpdateDispatchArgs;
    d3d12aid_ComputeRsPs          DecompressHuffmanWeights;
    d3d12aid_ComputeRsPs          DecodeHuffmanWeights;
    d3d12aid_ComputeRsPs          InitHuffmanTable;
    d3d12aid_ComputeRsPs          DecompressSequences;
    d3d12aid_ComputeRsPs          FinaliseSequenceOffsets;
    d3d12aid_ComputeRsPs          InitFseTable;
    d3d12aid_ComputeRsPs          ComputeDestBlockOffsets;
    d3d12aid_ComputeRsPs          ExecuteSequences;
    d3d12aid_ComputeRsPs          ComputeDestSequenceOffsets;
    d3d12aid_ComputeRsPs          MemsetMemcpy;
    d3d12aid_ComputeRsPs          InitResources;
    d3d12aid_ComputeRsPs          ParseCompressedBlocks;

    zstdgpu_Srt_BindGroups_Stage0 stage0;
    zstdgpu_Srt_BindGroups_Stage1 stage1;
    zstdgpu_Srt_BindGroups_Stage2 stage2;
};

static D3D12_SHADER_RESOURCE_VIEW_DESC *zstdgpu_SRV_InitAsInvalidBuffer(D3D12_SHADER_RESOURCE_VIEW_DESC *outDesc, uint64_t sizeInBytes, uint32_t strideSizeInBytes)
{
    ZSTDGPU_ASSERT(0 == sizeInBytes % strideSizeInBytes);
    UINT elemCount = (UINT)(sizeInBytes / strideSizeInBytes);
    outDesc->Format                     = DXGI_FORMAT_UNKNOWN;
    outDesc->ViewDimension              = D3D12_SRV_DIMENSION_BUFFER;
    outDesc->Shader4ComponentMapping    = D3D12_DEFAULT_SHADER_4_COMPONENT_MAPPING;
    outDesc->Buffer.FirstElement        = 0/*elemStart*/;
    outDesc->Buffer.NumElements         = elemCount;
    outDesc->Buffer.StructureByteStride = 0;
    outDesc->Buffer.Flags               = D3D12_BUFFER_SRV_FLAG_NONE;
    return outDesc;
}
static D3D12_UNORDERED_ACCESS_VIEW_DESC *zstdgpu_UAV_InitAsInvalidBuffer(D3D12_UNORDERED_ACCESS_VIEW_DESC *outDesc, uint64_t sizeInBytes, uint32_t strideSizeInBytes)
{
    ZSTDGPU_ASSERT(0 == sizeInBytes % strideSizeInBytes);
    UINT elemCount = (UINT)(sizeInBytes / strideSizeInBytes);
    outDesc->Format                     = DXGI_FORMAT_UNKNOWN;
    outDesc->ViewDimension              = D3D12_UAV_DIMENSION_BUFFER;
    outDesc->Buffer.FirstElement        = 0/*elemStart*/;
    outDesc->Buffer.NumElements         = elemCount;
    outDesc->Buffer.StructureByteStride = 0;
    outDesc->Buffer.CounterOffsetInBytes= 0;
    outDesc->Buffer.Flags               = D3D12_BUFFER_UAV_FLAG_NONE;
    return outDesc;
}
static D3D12_SHADER_RESOURCE_VIEW_DESC *zstdgpu_SRV_InitAsRawBuffer(D3D12_SHADER_RESOURCE_VIEW_DESC *outDesc, uint64_t sizeInBytes)
{
    zstdgpu_SRV_InitAsInvalidBuffer(outDesc, sizeInBytes, sizeof(uint32_t));
    outDesc->Format = DXGI_FORMAT_R32_TYPELESS;
    outDesc->Buffer.Flags = D3D12_BUFFER_SRV_FLAG_RAW;
    return outDesc;
}
static D3D12_UNORDERED_ACCESS_VIEW_DESC *zstdgpu_UAV_InitAsRawBuffer(D3D12_UNORDERED_ACCESS_VIEW_DESC *outDesc, uint64_t sizeInBytes)
{
    zstdgpu_UAV_InitAsInvalidBuffer(outDesc, sizeInBytes, sizeof(uint32_t));
    outDesc->Format = DXGI_FORMAT_R32_TYPELESS;
    outDesc->Buffer.Flags = D3D12_BUFFER_UAV_FLAG_RAW;
    return outDesc;
}
static D3D12_SHADER_RESOURCE_VIEW_DESC *zstdgpu_SRV_InitAsStructBuffer(D3D12_SHADER_RESOURCE_VIEW_DESC *outDesc, uint64_t sizeInBytes, uint32_t structSizeInBytes)
{
    zstdgpu_SRV_InitAsInvalidBuffer(outDesc, sizeInBytes, structSizeInBytes);
    outDesc->Buffer.StructureByteStride = structSizeInBytes;
    return outDesc;
}
static D3D12_UNORDERED_ACCESS_VIEW_DESC *zstdgpu_UAV_InitAsStructBuffer(D3D12_UNORDERED_ACCESS_VIEW_DESC *outDesc, uint64_t sizeInBytes, uint32_t structSizeInBytes)
{
    zstdgpu_UAV_InitAsInvalidBuffer(outDesc, sizeInBytes, structSizeInBytes);
    outDesc->Buffer.StructureByteStride = structSizeInBytes;
    return outDesc;
}
static D3D12_SHADER_RESOURCE_VIEW_DESC *zstdgpu_SRV_InitAsTypedBuffer(D3D12_SHADER_RESOURCE_VIEW_DESC *outDesc, uint64_t sizeInBytes, DXGI_FORMAT format, uint32_t elemSizeInBytes)
{
    zstdgpu_SRV_InitAsInvalidBuffer(outDesc, sizeInBytes, elemSizeInBytes);
    outDesc->Format = format;
    return outDesc;
}
static D3D12_UNORDERED_ACCESS_VIEW_DESC *zstdgpu_UAV_InitAsTypedBuffer(D3D12_UNORDERED_ACCESS_VIEW_DESC *outDesc, uint64_t sizeInBytes, DXGI_FORMAT format, uint32_t elemSizeInBytes)
{
    zstdgpu_UAV_InitAsInvalidBuffer(outDesc, sizeInBytes, elemSizeInBytes);
    outDesc->Format = format;
    return outDesc;
}
/** Descriptor writers. Each advances `cpuDest` by exactly one descriptor. */
static void zstdgpu_Srt_PushRawBufferSrv(D3D12_CPU_DESCRIPTOR_HANDLE &cpuDest, uint32_t descSize, ID3D12Device *device, ID3D12Resource *resource, uint32_t byteSize)
{
    D3D12_SHADER_RESOURCE_VIEW_DESC SRV;
    device->CreateShaderResourceView(resource, zstdgpu_SRV_InitAsRawBuffer(&SRV, byteSize), cpuDest);
    cpuDest.ptr += descSize;
}

static void zstdgpu_Srt_PushRawBufferUav(D3D12_CPU_DESCRIPTOR_HANDLE &cpuDest, uint32_t descSize, ID3D12Device *device, ID3D12Resource *resource, uint32_t byteSize)
{
    D3D12_UNORDERED_ACCESS_VIEW_DESC UAV;
    device->CreateUnorderedAccessView(resource, NULL, zstdgpu_UAV_InitAsRawBuffer(&UAV, byteSize), cpuDest);
    cpuDest.ptr += descSize;
}

static void zstdgpu_Srt_PushStructBufferSrv(D3D12_CPU_DESCRIPTOR_HANDLE &cpuDest, uint32_t descSize, ID3D12Device *device, ID3D12Resource *resource, uint32_t byteSize, uint32_t stride)
{
    D3D12_SHADER_RESOURCE_VIEW_DESC SRV;
    device->CreateShaderResourceView(resource, zstdgpu_SRV_InitAsStructBuffer(&SRV, byteSize, stride), cpuDest);
    cpuDest.ptr += descSize;
}

static void zstdgpu_Srt_PushStructBufferUav(D3D12_CPU_DESCRIPTOR_HANDLE &cpuDest, uint32_t descSize, ID3D12Device *device, ID3D12Resource *resource, uint32_t byteSize, uint32_t stride)
{
    D3D12_UNORDERED_ACCESS_VIEW_DESC UAV;
    device->CreateUnorderedAccessView(resource, NULL, zstdgpu_UAV_InitAsStructBuffer(&UAV, byteSize, stride), cpuDest);
    cpuDest.ptr += descSize;
}

static void zstdgpu_Srt_PushTypedBufferSrv(D3D12_CPU_DESCRIPTOR_HANDLE &cpuDest, uint32_t descSize, ID3D12Device *device, ID3D12Resource *resource, uint32_t byteSize, DXGI_FORMAT format, uint32_t stride)
{
    D3D12_SHADER_RESOURCE_VIEW_DESC SRV;
    device->CreateShaderResourceView(resource, zstdgpu_SRV_InitAsTypedBuffer(&SRV, byteSize, format, stride), cpuDest);
    cpuDest.ptr += descSize;
}

static void zstdgpu_Srt_PushTypedBufferUav(D3D12_CPU_DESCRIPTOR_HANDLE &cpuDest, uint32_t descSize, ID3D12Device *device, ID3D12Resource *resource, uint32_t byteSize, DXGI_FORMAT format, uint32_t stride)
{
    D3D12_UNORDERED_ACCESS_VIEW_DESC UAV;
    device->CreateUnorderedAccessView(resource, NULL, zstdgpu_UAV_InitAsTypedBuffer(&UAV, byteSize, format, stride), cpuDest);
    cpuDest.ptr += descSize;
}

static D3D12_GPU_DESCRIPTOR_HANDLE zstdgpu_Srt_InitBindGroup_ParseFrames(zstdgpu_Srts &srts, ID3D12Device *device, const zstdgpu_ResourceInfo &resInfo, const zstdgpu_GpuOnlyBuffers &b)
{
    const uint32_t descSize = device->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV);
    const D3D12_CPU_DESCRIPTOR_HANDLE cpuStart = d3d12aid_DescriptorHeap_GetCpuStart(srts.heap);
    const D3D12_GPU_DESCRIPTOR_HANDLE gpuStart = d3d12aid_DescriptorHeap_GetGpuStart(srts.heap);
    const D3D12_GPU_DESCRIPTOR_HANDLE gpuDest  = { gpuStart.ptr + (UINT64)srts.heapOffset * descSize };
    D3D12_CPU_DESCRIPTOR_HANDLE       cpuDest  = { cpuStart.ptr + (SIZE_T)srts.heapOffset * descSize };

    zstdgpu_Srt_PushStructBufferSrv(cpuDest, descSize, device, b.CompressedData, resInfo.CompressedData_ByteSize, sizeof(uint32_t));
    zstdgpu_Srt_PushStructBufferSrv(cpuDest, descSize, device, b.FramesRefs, resInfo.FramesRefs_ByteSize, sizeof(zstdgpu_OffsetAndSize));
    zstdgpu_Srt_PushStructBufferUav(cpuDest, descSize, device, b.Counters, resInfo.Counters_ByteSize, sizeof(zstdgpu_Counters));
    zstdgpu_Srt_PushStructBufferUav(cpuDest, descSize, device, b.PerFrameBlockCountRAW, resInfo.PerFrameBlockCountRAW_ByteSize, sizeof(uint32_t));
    zstdgpu_Srt_PushStructBufferUav(cpuDest, descSize, device, b.PerFrameBlockCountRLE, resInfo.PerFrameBlockCountRLE_ByteSize, sizeof(uint32_t));
    zstdgpu_Srt_PushStructBufferUav(cpuDest, descSize, device, b.PerFrameBlockCountCMP, resInfo.PerFrameBlockCountCMP_ByteSize, sizeof(uint32_t));
    zstdgpu_Srt_PushStructBufferUav(cpuDest, descSize, device, b.PerFrameBlockCountAll, resInfo.PerFrameBlockCountAll_ByteSize, sizeof(uint32_t));
    zstdgpu_Srt_PushStructBufferUav(cpuDest, descSize, device, b.RawBlockSizePrefix, resInfo.RawBlockSizePrefix_ByteSize, sizeof(uint32_t));
    zstdgpu_Srt_PushStructBufferUav(cpuDest, descSize, device, b.RleBlockSizePrefix, resInfo.RleBlockSizePrefix_ByteSize, sizeof(uint32_t));
    zstdgpu_Srt_PushStructBufferUav(cpuDest, descSize, device, b.BlocksRAWRefs, resInfo.BlocksRAWRefs_ByteSize, sizeof(zstdgpu_OffsetAndSize));
    zstdgpu_Srt_PushStructBufferUav(cpuDest, descSize, device, b.BlocksRLERefs, resInfo.BlocksRLERefs_ByteSize, sizeof(zstdgpu_OffsetAndSize));
    zstdgpu_Srt_PushStructBufferUav(cpuDest, descSize, device, b.BlocksCMPRefs, resInfo.BlocksCMPRefs_ByteSize, sizeof(zstdgpu_OffsetAndSize));
    zstdgpu_Srt_PushStructBufferUav(cpuDest, descSize, device, b.BlockSizePrefix, resInfo.BlockSizePrefix_ByteSize, sizeof(uint32_t));
    zstdgpu_Srt_PushStructBufferUav(cpuDest, descSize, device, b.GlobalBlockIndexPerRawBlock, resInfo.GlobalBlockIndexPerRawBlock_ByteSize, sizeof(uint32_t));
    zstdgpu_Srt_PushStructBufferUav(cpuDest, descSize, device, b.GlobalBlockIndexPerRleBlock, resInfo.GlobalBlockIndexPerRleBlock_ByteSize, sizeof(uint32_t));
    zstdgpu_Srt_PushStructBufferUav(cpuDest, descSize, device, b.GlobalBlockIndexPerCmpBlock, resInfo.GlobalBlockIndexPerCmpBlock_ByteSize, sizeof(uint32_t));
    zstdgpu_Srt_PushStructBufferUav(cpuDest, descSize, device, b.FrameStatus, resInfo.FrameStatus_ByteSize, sizeof(uint32_t));

    srts.heapOffset += 17;
    return gpuDest;
}

static D3D12_GPU_DESCRIPTOR_HANDLE zstdgpu_Srt_InitBindGroup_LiteralStreams(zstdgpu_Srts &srts, ID3D12Device *device, const zstdgpu_ResourceInfo &resInfo, const zstdgpu_GpuOnlyBuffers &b)
{
    const uint32_t descSize = device->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV);
    const D3D12_CPU_DESCRIPTOR_HANDLE cpuStart = d3d12aid_DescriptorHeap_GetCpuStart(srts.heap);
    const D3D12_GPU_DESCRIPTOR_HANDLE gpuStart = d3d12aid_DescriptorHeap_GetGpuStart(srts.heap);
    const D3D12_GPU_DESCRIPTOR_HANDLE gpuDest  = { gpuStart.ptr + (UINT64)srts.heapOffset * descSize };
    D3D12_CPU_DESCRIPTOR_HANDLE       cpuDest  = { cpuStart.ptr + (SIZE_T)srts.heapOffset * descSize };

    zstdgpu_Srt_PushStructBufferSrv(cpuDest, descSize, device, b.LitGroupEndPerHuffmanTable, resInfo.LitGroupEndPerHuffmanTable_ByteSize, sizeof(uint32_t));
    zstdgpu_Srt_PushStructBufferSrv(cpuDest, descSize, device, b.Counters, resInfo.Counters_ByteSize, sizeof(zstdgpu_Counters));
    zstdgpu_Srt_PushStructBufferSrv(cpuDest, descSize, device, b.LitRefs, resInfo.LitRefs_ByteSize, sizeof(zstdgpu_LitStreamInfo));
    zstdgpu_Srt_PushRawBufferSrv(cpuDest, descSize, device, b.CompressedData, resInfo.CompressedData_ByteSize);
    zstdgpu_Srt_PushStructBufferSrv(cpuDest, descSize, device, b.HufWIdToHufLitId, resInfo.HufWIdToHufLitId_ByteSize, sizeof(uint32_t));
    zstdgpu_Srt_PushStructBufferSrv(cpuDest, descSize, device, b.HufLitIdToLitStreamId, resInfo.HufLitIdToLitStreamId_ByteSize, sizeof(uint32_t));
    zstdgpu_Srt_PushTypedBufferUav(cpuDest, descSize, device, b.DecompressedLiterals, resInfo.DecompressedLiterals_ByteSize, DXGI_FORMAT_R8_UINT, sizeof(uint8_t));

    srts.heapOffset += 7;
    return gpuDest;
}

static D3D12_GPU_DESCRIPTOR_HANDLE zstdgpu_Srt_InitBindGroup_HuffmanTable(zstdgpu_Srts &srts, ID3D12Device *device, const zstdgpu_ResourceInfo &resInfo, const zstdgpu_GpuOnlyBuffers &b)
{
    const uint32_t descSize = device->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV);
    const D3D12_CPU_DESCRIPTOR_HANDLE cpuStart = d3d12aid_DescriptorHeap_GetCpuStart(srts.heap);
    const D3D12_GPU_DESCRIPTOR_HANDLE gpuStart = d3d12aid_DescriptorHeap_GetGpuStart(srts.heap);
    const D3D12_GPU_DESCRIPTOR_HANDLE gpuDest  = { gpuStart.ptr + (UINT64)srts.heapOffset * descSize };
    D3D12_CPU_DESCRIPTOR_HANDLE       cpuDest  = { cpuStart.ptr + (SIZE_T)srts.heapOffset * descSize };

    zstdgpu_Srt_PushStructBufferSrv(cpuDest, descSize, device, b.HuffmanTableInfo, resInfo.HuffmanTableInfo_ByteSize, sizeof(uint32_t));
    zstdgpu_Srt_PushStructBufferSrv(cpuDest, descSize, device, b.HuffmanTableCodeAndSymbol, resInfo.HuffmanTableCodeAndSymbol_ByteSize, sizeof(uint32_t));
    zstdgpu_Srt_PushStructBufferSrv(cpuDest, descSize, device, b.HuffmanTableRankIndex, resInfo.HuffmanTableRankIndex_ByteSize, sizeof(uint32_t));

    srts.heapOffset += 3;
    return gpuDest;
}

static D3D12_GPU_DESCRIPTOR_HANDLE zstdgpu_Srt_InitBindGroup_LiteralDwords(zstdgpu_Srts &srts, ID3D12Device *device, const zstdgpu_ResourceInfo &resInfo, const zstdgpu_GpuOnlyBuffers &b)
{
    const uint32_t descSize = device->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV);
    const D3D12_CPU_DESCRIPTOR_HANDLE cpuStart = d3d12aid_DescriptorHeap_GetCpuStart(srts.heap);
    const D3D12_GPU_DESCRIPTOR_HANDLE gpuStart = d3d12aid_DescriptorHeap_GetGpuStart(srts.heap);
    const D3D12_GPU_DESCRIPTOR_HANDLE gpuDest  = { gpuStart.ptr + (UINT64)srts.heapOffset * descSize };
    D3D12_CPU_DESCRIPTOR_HANDLE       cpuDest  = { cpuStart.ptr + (SIZE_T)srts.heapOffset * descSize };

    zstdgpu_Srt_PushStructBufferUav(cpuDest, descSize, device, b.DecompressedLiterals, resInfo.DecompressedLiterals_ByteSize, sizeof(uint32_t));

    srts.heapOffset += 1;
    return gpuDest;
}

static D3D12_GPU_DESCRIPTOR_HANDLE zstdgpu_Srt_InitBindGroup_HuffmanWeights(zstdgpu_Srts &srts, ID3D12Device *device, const zstdgpu_ResourceInfo &resInfo, const zstdgpu_GpuOnlyBuffers &b)
{
    const uint32_t descSize = device->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV);
    const D3D12_CPU_DESCRIPTOR_HANDLE cpuStart = d3d12aid_DescriptorHeap_GetCpuStart(srts.heap);
    const D3D12_GPU_DESCRIPTOR_HANDLE gpuStart = d3d12aid_DescriptorHeap_GetGpuStart(srts.heap);
    const D3D12_GPU_DESCRIPTOR_HANDLE gpuDest  = { gpuStart.ptr + (UINT64)srts.heapOffset * descSize };
    D3D12_CPU_DESCRIPTOR_HANDLE       cpuDest  = { cpuStart.ptr + (SIZE_T)srts.heapOffset * descSize };

    zstdgpu_Srt_PushTypedBufferSrv(cpuDest, descSize, device, b.DecompressedHuffmanWeights, resInfo.DecompressedHuffmanWeights_ByteSize, DXGI_FORMAT_R8_UINT, sizeof(uint8_t));
    zstdgpu_Srt_PushTypedBufferSrv(cpuDest, descSize, device, b.DecompressedHuffmanWeightCount, resInfo.DecompressedHuffmanWeightCount_ByteSize, DXGI_FORMAT_R8_UINT, sizeof(uint8_t));

    srts.heapOffset += 2;
    return gpuDest;
}

static D3D12_GPU_DESCRIPTOR_HANDLE zstdgpu_Srt_InitBindGroup_HuffmanWeightsWrite(zstdgpu_Srts &srts, ID3D12Device *device, const zstdgpu_ResourceInfo &resInfo, const zstdgpu_GpuOnlyBuffers &b)
{
    const uint32_t descSize = device->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV);
    const D3D12_CPU_DESCRIPTOR_HANDLE cpuStart = d3d12aid_DescriptorHeap_GetCpuStart(srts.heap);
    const D3D12_GPU_DESCRIPTOR_HANDLE gpuStart = d3d12aid_DescriptorHeap_GetGpuStart(srts.heap);
    const D3D12_GPU_DESCRIPTOR_HANDLE gpuDest  = { gpuStart.ptr + (UINT64)srts.heapOffset * descSize };
    D3D12_CPU_DESCRIPTOR_HANDLE       cpuDest  = { cpuStart.ptr + (SIZE_T)srts.heapOffset * descSize };

    zstdgpu_Srt_PushTypedBufferUav(cpuDest, descSize, device, b.DecompressedHuffmanWeights, resInfo.DecompressedHuffmanWeights_ByteSize, DXGI_FORMAT_R8_UINT, sizeof(uint8_t));
    zstdgpu_Srt_PushTypedBufferUav(cpuDest, descSize, device, b.DecompressedHuffmanWeightCount, resInfo.DecompressedHuffmanWeightCount_ByteSize, DXGI_FORMAT_R8_UINT, sizeof(uint8_t));

    srts.heapOffset += 2;
    return gpuDest;
}

static D3D12_GPU_DESCRIPTOR_HANDLE zstdgpu_Srt_InitBindGroup_HuffmanTableWrite(zstdgpu_Srts &srts, ID3D12Device *device, const zstdgpu_ResourceInfo &resInfo, const zstdgpu_GpuOnlyBuffers &b)
{
    const uint32_t descSize = device->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV);
    const D3D12_CPU_DESCRIPTOR_HANDLE cpuStart = d3d12aid_DescriptorHeap_GetCpuStart(srts.heap);
    const D3D12_GPU_DESCRIPTOR_HANDLE gpuStart = d3d12aid_DescriptorHeap_GetGpuStart(srts.heap);
    const D3D12_GPU_DESCRIPTOR_HANDLE gpuDest  = { gpuStart.ptr + (UINT64)srts.heapOffset * descSize };
    D3D12_CPU_DESCRIPTOR_HANDLE       cpuDest  = { cpuStart.ptr + (SIZE_T)srts.heapOffset * descSize };

    zstdgpu_Srt_PushStructBufferUav(cpuDest, descSize, device, b.HuffmanTableInfo, resInfo.HuffmanTableInfo_ByteSize, sizeof(uint32_t));
    zstdgpu_Srt_PushStructBufferUav(cpuDest, descSize, device, b.HuffmanTableCodeAndSymbol, resInfo.HuffmanTableCodeAndSymbol_ByteSize, sizeof(uint32_t));
    zstdgpu_Srt_PushStructBufferUav(cpuDest, descSize, device, b.HuffmanTableRankIndex, resInfo.HuffmanTableRankIndex_ByteSize, sizeof(uint32_t));

    srts.heapOffset += 3;
    return gpuDest;
}

static D3D12_GPU_DESCRIPTOR_HANDLE zstdgpu_Srt_InitBindGroup_SequenceOutputs(zstdgpu_Srts &srts, ID3D12Device *device, const zstdgpu_ResourceInfo &resInfo, const zstdgpu_GpuOnlyBuffers &b)
{
    const uint32_t descSize = device->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV);
    const D3D12_CPU_DESCRIPTOR_HANDLE cpuStart = d3d12aid_DescriptorHeap_GetCpuStart(srts.heap);
    const D3D12_GPU_DESCRIPTOR_HANDLE gpuStart = d3d12aid_DescriptorHeap_GetGpuStart(srts.heap);
    const D3D12_GPU_DESCRIPTOR_HANDLE gpuDest  = { gpuStart.ptr + (UINT64)srts.heapOffset * descSize };
    D3D12_CPU_DESCRIPTOR_HANDLE       cpuDest  = { cpuStart.ptr + (SIZE_T)srts.heapOffset * descSize };

    zstdgpu_Srt_PushStructBufferUav(cpuDest, descSize, device, b.DecompressedSequenceLLen, resInfo.DecompressedSequenceLLen_ByteSize, sizeof(uint32_t));
    zstdgpu_Srt_PushStructBufferUav(cpuDest, descSize, device, b.DecompressedSequenceMLen, resInfo.DecompressedSequenceMLen_ByteSize, sizeof(uint32_t));
    zstdgpu_Srt_PushStructBufferUav(cpuDest, descSize, device, b.DecompressedSequenceOffs, resInfo.DecompressedSequenceOffs_ByteSize, sizeof(uint32_t));
    zstdgpu_Srt_PushStructBufferUav(cpuDest, descSize, device, b.BlockSizePrefix, resInfo.BlockSizePrefix_ByteSize, sizeof(uint32_t));
    zstdgpu_Srt_PushStructBufferUav(cpuDest, descSize, device, b.PerSeqStreamFinalOffset1, resInfo.PerSeqStreamFinalOffset1_ByteSize, sizeof(uint32_t));
    zstdgpu_Srt_PushStructBufferUav(cpuDest, descSize, device, b.PerSeqStreamFinalOffset2, resInfo.PerSeqStreamFinalOffset2_ByteSize, sizeof(uint32_t));
    zstdgpu_Srt_PushStructBufferUav(cpuDest, descSize, device, b.PerSeqStreamFinalOffset3, resInfo.PerSeqStreamFinalOffset3_ByteSize, sizeof(uint32_t));

    srts.heapOffset += 7;
    return gpuDest;
}

static D3D12_GPU_DESCRIPTOR_HANDLE zstdgpu_Srt_InitBindGroup_LiteralBytes(zstdgpu_Srts &srts, ID3D12Device *device, const zstdgpu_ResourceInfo &resInfo, const zstdgpu_GpuOnlyBuffers &b)
{
    const uint32_t descSize = device->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV);
    const D3D12_CPU_DESCRIPTOR_HANDLE cpuStart = d3d12aid_DescriptorHeap_GetCpuStart(srts.heap);
    const D3D12_GPU_DESCRIPTOR_HANDLE gpuStart = d3d12aid_DescriptorHeap_GetGpuStart(srts.heap);
    const D3D12_GPU_DESCRIPTOR_HANDLE gpuDest  = { gpuStart.ptr + (UINT64)srts.heapOffset * descSize };
    D3D12_CPU_DESCRIPTOR_HANDLE       cpuDest  = { cpuStart.ptr + (SIZE_T)srts.heapOffset * descSize };

    zstdgpu_Srt_PushTypedBufferSrv(cpuDest, descSize, device, b.CompressedData, resInfo.CompressedData_ByteSize, DXGI_FORMAT_R8_UINT, sizeof(uint8_t));
    zstdgpu_Srt_PushTypedBufferSrv(cpuDest, descSize, device, b.DecompressedLiterals, resInfo.DecompressedLiterals_ByteSize, DXGI_FORMAT_R8_UINT, sizeof(uint8_t));

    srts.heapOffset += 2;
    return gpuDest;
}

static D3D12_GPU_DESCRIPTOR_HANDLE zstdgpu_Srt_InitBindGroup_FseProbsRead(zstdgpu_Srts &srts, ID3D12Device *device, const zstdgpu_ResourceInfo &resInfo, const zstdgpu_GpuOnlyBuffers &b)
{
    const uint32_t descSize = device->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV);
    const D3D12_CPU_DESCRIPTOR_HANDLE cpuStart = d3d12aid_DescriptorHeap_GetCpuStart(srts.heap);
    const D3D12_GPU_DESCRIPTOR_HANDLE gpuStart = d3d12aid_DescriptorHeap_GetGpuStart(srts.heap);
    const D3D12_GPU_DESCRIPTOR_HANDLE gpuDest  = { gpuStart.ptr + (UINT64)srts.heapOffset * descSize };
    D3D12_CPU_DESCRIPTOR_HANDLE       cpuDest  = { cpuStart.ptr + (SIZE_T)srts.heapOffset * descSize };

    zstdgpu_Srt_PushTypedBufferSrv(cpuDest, descSize, device, b.FseProbs, resInfo.FseProbs_ByteSize, DXGI_FORMAT_R16_SINT, sizeof(int16_t));

    srts.heapOffset += 1;
    return gpuDest;
}

static D3D12_GPU_DESCRIPTOR_HANDLE zstdgpu_Srt_InitBindGroup_FrameOutput(zstdgpu_Srts &srts, ID3D12Device *device, const zstdgpu_ResourceInfo &resInfo, const zstdgpu_GpuOnlyBuffers &b)
{
    const uint32_t descSize = device->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV);
    const D3D12_CPU_DESCRIPTOR_HANDLE cpuStart = d3d12aid_DescriptorHeap_GetCpuStart(srts.heap);
    const D3D12_GPU_DESCRIPTOR_HANDLE gpuStart = d3d12aid_DescriptorHeap_GetGpuStart(srts.heap);
    const D3D12_GPU_DESCRIPTOR_HANDLE gpuDest  = { gpuStart.ptr + (UINT64)srts.heapOffset * descSize };
    D3D12_CPU_DESCRIPTOR_HANDLE       cpuDest  = { cpuStart.ptr + (SIZE_T)srts.heapOffset * descSize };

    zstdgpu_Srt_PushTypedBufferUav(cpuDest, descSize, device, b.UnCompressedFramesData, resInfo.UnCompressedFramesData_ByteSize, DXGI_FORMAT_R8_UINT, sizeof(uint8_t));

    srts.heapOffset += 1;
    return gpuDest;
}

static D3D12_GPU_DESCRIPTOR_HANDLE zstdgpu_Srt_InitBindGroup_FseInit(zstdgpu_Srts &srts, ID3D12Device *device, const zstdgpu_ResourceInfo &resInfo, const zstdgpu_GpuOnlyBuffers &b)
{
    const uint32_t descSize = device->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV);
    const D3D12_CPU_DESCRIPTOR_HANDLE cpuStart = d3d12aid_DescriptorHeap_GetCpuStart(srts.heap);
    const D3D12_GPU_DESCRIPTOR_HANDLE gpuStart = d3d12aid_DescriptorHeap_GetGpuStart(srts.heap);
    const D3D12_GPU_DESCRIPTOR_HANDLE gpuDest  = { gpuStart.ptr + (UINT64)srts.heapOffset * descSize };
    D3D12_CPU_DESCRIPTOR_HANDLE       cpuDest  = { cpuStart.ptr + (SIZE_T)srts.heapOffset * descSize };

    zstdgpu_Srt_PushTypedBufferSrv(cpuDest, descSize, device, b.FseProbsDefault, resInfo.FseProbsDefault_ByteSize, DXGI_FORMAT_R16_SINT, sizeof(int16_t));
    zstdgpu_Srt_PushTypedBufferUav(cpuDest, descSize, device, b.FseProbs, resInfo.FseProbs_ByteSize, DXGI_FORMAT_R16_SINT, sizeof(int16_t));
    zstdgpu_Srt_PushStructBufferUav(cpuDest, descSize, device, b.FseInfos, resInfo.FseInfos_ByteSize, sizeof(zstdgpu_FseInfo));
    zstdgpu_Srt_PushStructBufferUav(cpuDest, descSize, device, b.FseElems, resInfo.FseElems_ByteSize, sizeof(uint32_t));

    srts.heapOffset += 4;
    return gpuDest;
}

static D3D12_GPU_DESCRIPTOR_HANDLE zstdgpu_Srt_InitBindGroup_ParseBlocksWrite(zstdgpu_Srts &srts, ID3D12Device *device, const zstdgpu_ResourceInfo &resInfo, const zstdgpu_GpuOnlyBuffers &b)
{
    const uint32_t descSize = device->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV);
    const D3D12_CPU_DESCRIPTOR_HANDLE cpuStart = d3d12aid_DescriptorHeap_GetCpuStart(srts.heap);
    const D3D12_GPU_DESCRIPTOR_HANDLE gpuStart = d3d12aid_DescriptorHeap_GetGpuStart(srts.heap);
    const D3D12_GPU_DESCRIPTOR_HANDLE gpuDest  = { gpuStart.ptr + (UINT64)srts.heapOffset * descSize };
    D3D12_CPU_DESCRIPTOR_HANDLE       cpuDest  = { cpuStart.ptr + (SIZE_T)srts.heapOffset * descSize };

    zstdgpu_Srt_PushStructBufferUav(cpuDest, descSize, device, b.Counters, resInfo.Counters_ByteSize, sizeof(zstdgpu_Counters));
    zstdgpu_Srt_PushStructBufferUav(cpuDest, descSize, device, b.FseInfos, resInfo.FseInfos_ByteSize, sizeof(zstdgpu_FseInfo));
    zstdgpu_Srt_PushStructBufferUav(cpuDest, descSize, device, b.CompressedBlocks, resInfo.CompressedBlocks_ByteSize, sizeof(zstdgpu_CompressedBlockData));
    zstdgpu_Srt_PushStructBufferUav(cpuDest, descSize, device, b.HufRefs, resInfo.HufRefs_ByteSize, sizeof(zstdgpu_OffsetAndSize));
    zstdgpu_Srt_PushStructBufferUav(cpuDest, descSize, device, b.LitRefs, resInfo.LitRefs_ByteSize, sizeof(zstdgpu_LitStreamInfo));
    zstdgpu_Srt_PushStructBufferUav(cpuDest, descSize, device, b.SeqStreamToRef, resInfo.SeqStreamToRef_ByteSize, sizeof(zstdgpu_OffsetAndSize));
    zstdgpu_Srt_PushStructBufferUav(cpuDest, descSize, device, b.SeqStreamToLLenFseId, resInfo.SeqStreamToLLenFseId_ByteSize, sizeof(uint32_t));
    zstdgpu_Srt_PushStructBufferUav(cpuDest, descSize, device, b.SeqStreamToOffsFseId, resInfo.SeqStreamToOffsFseId_ByteSize, sizeof(uint32_t));
    zstdgpu_Srt_PushStructBufferUav(cpuDest, descSize, device, b.SeqStreamToMLenFseId, resInfo.SeqStreamToMLenFseId_ByteSize, sizeof(uint32_t));
    zstdgpu_Srt_PushStructBufferUav(cpuDest, descSize, device, b.SeqStreamToBlockId, resInfo.SeqStreamToBlockId_ByteSize, sizeof(uint32_t));
    zstdgpu_Srt_PushStructBufferUav(cpuDest, descSize, device, b.BlockSizePrefix, resInfo.BlockSizePrefix_ByteSize, sizeof(uint32_t));
    zstdgpu_Srt_PushStructBufferUav(cpuDest, descSize, device, b.PerFrameSeqStreamMinIdx, resInfo.PerFrameSeqStreamMinIdx_ByteSize, sizeof(uint32_t));
    zstdgpu_Srt_PushStructBufferUav(cpuDest, descSize, device, b.PerSeqStreamSeqStart, resInfo.PerSeqStreamSeqStart_ByteSize, sizeof(uint32_t));
    zstdgpu_Srt_PushStructBufferUav(cpuDest, descSize, device, b.SeqCountPrefixLookback, resInfo.SeqCountPrefixLookback_ByteSize, sizeof(uint32_t));
    zstdgpu_Srt_PushStructBufferUav(cpuDest, descSize, device, b.BlockSeqCountPrefixLookback, resInfo.BlockSeqCountPrefixLookback_ByteSize, sizeof(uint32_t));
    zstdgpu_Srt_PushTypedBufferUav(cpuDest, descSize, device, b.FseProbs, resInfo.FseProbs_ByteSize, DXGI_FORMAT_R16_SINT, sizeof(int16_t));
    zstdgpu_Srt_PushTypedBufferUav(cpuDest, descSize, device, b.DecompressedHuffmanWeightCount, resInfo.DecompressedHuffmanWeightCount_ByteSize, DXGI_FORMAT_R8_UINT, sizeof(uint8_t));
    zstdgpu_Srt_PushStructBufferUav(cpuDest, descSize, device, b.LitStreamCountPrefixLookback, resInfo.LitStreamCountPrefixLookback_ByteSize, sizeof(uint32_t));
    zstdgpu_Srt_PushStructBufferUav(cpuDest, descSize, device, b.HufWIdToHufLitId, resInfo.HufWIdToHufLitId_ByteSize, sizeof(uint32_t));
    zstdgpu_Srt_PushStructBufferUav(cpuDest, descSize, device, b.HufLitIdToLitStreamId, resInfo.HufLitIdToLitStreamId_ByteSize, sizeof(uint32_t));
    zstdgpu_Srt_PushStructBufferUav(cpuDest, descSize, device, b.HufLitIdToHufWId_DBG, resInfo.HufLitIdToHufWId_DBG_ByteSize, sizeof(uint32_t));
    zstdgpu_Srt_PushStructBufferUav(cpuDest, descSize, device, b.HufLitCompactionLookback, resInfo.HufLitCompactionLookback_ByteSize, sizeof(uint32_t));

    srts.heapOffset += 22;
    return gpuDest;
}

static void zstdgpu_Srt_InitBindGroups_Stage0(zstdgpu_Srts &srts, ID3D12Device *device, const zstdgpu_ResourceInfo &resInfo, const zstdgpu_GpuOnlyBuffers &b)
{
    srts.stage0.ParseFrames = zstdgpu_Srt_InitBindGroup_ParseFrames(srts, device, resInfo, b);
    srts.stage0.FseInit = zstdgpu_Srt_InitBindGroup_FseInit(srts, device, resInfo, b);
}

static void zstdgpu_Srt_InitBindGroups_Stage1(zstdgpu_Srts &srts, ID3D12Device *device, const zstdgpu_ResourceInfo &resInfo, const zstdgpu_GpuOnlyBuffers &b)
{
    srts.stage1.ParseFrames = zstdgpu_Srt_InitBindGroup_ParseFrames(srts, device, resInfo, b);
    srts.stage1.FseInit = zstdgpu_Srt_InitBindGroup_FseInit(srts, device, resInfo, b);
    srts.stage1.ParseBlocksWrite = zstdgpu_Srt_InitBindGroup_ParseBlocksWrite(srts, device, resInfo, b);
}

static void zstdgpu_Srt_InitBindGroups_Stage2(zstdgpu_Srts &srts, ID3D12Device *device, const zstdgpu_ResourceInfo &resInfo, const zstdgpu_GpuOnlyBuffers &b)
{
    srts.stage2.LiteralStreams = zstdgpu_Srt_InitBindGroup_LiteralStreams(srts, device, resInfo, b);
    srts.stage2.HuffmanTable = zstdgpu_Srt_InitBindGroup_HuffmanTable(srts, device, resInfo, b);
    srts.stage2.LiteralDwords = zstdgpu_Srt_InitBindGroup_LiteralDwords(srts, device, resInfo, b);
    srts.stage2.HuffmanWeights = zstdgpu_Srt_InitBindGroup_HuffmanWeights(srts, device, resInfo, b);
    srts.stage2.HuffmanWeightsWrite = zstdgpu_Srt_InitBindGroup_HuffmanWeightsWrite(srts, device, resInfo, b);
    srts.stage2.HuffmanTableWrite = zstdgpu_Srt_InitBindGroup_HuffmanTableWrite(srts, device, resInfo, b);
    srts.stage2.SequenceOutputs = zstdgpu_Srt_InitBindGroup_SequenceOutputs(srts, device, resInfo, b);
    srts.stage2.LiteralBytes = zstdgpu_Srt_InitBindGroup_LiteralBytes(srts, device, resInfo, b);
    srts.stage2.FseProbsRead = zstdgpu_Srt_InitBindGroup_FseProbsRead(srts, device, resInfo, b);
    srts.stage2.FrameOutput = zstdgpu_Srt_InitBindGroup_FrameOutput(srts, device, resInfo, b);
}

static void zstdgpu_Srt_InitBindGroups_Stage(zstdgpu_Srts &srts, ID3D12Device *device, const zstdgpu_ResourceInfo &resInfo, const zstdgpu_GpuOnlyBuffers &b, uint32_t stageIndex)
{
    switch (stageIndex)
    {
    case 0: zstdgpu_Srt_InitBindGroups_Stage0(srts, device, resInfo, b); break;
    case 1: zstdgpu_Srt_InitBindGroups_Stage1(srts, device, resInfo, b); break;
    case 2: zstdgpu_Srt_InitBindGroups_Stage2(srts, device, resInfo, b); break;
    default: ZSTDGPU_ASSERT(0); break;
    }
}

static void zstdgpu_Bind_Memset_SeqStreamMinIdx(ID3D12GraphicsCommandList *cmdList, const zstdgpu_Srts &srts, const zstdgpu_GpuOnlyBuffers &b, uint32_t tgOffset, uint32_t workItemCount, uint32_t value)
{
    d3d12aid_ComputeRsPs_Set(&srts.Memset, cmdList);
    cmdList->SetComputeRootUnorderedAccessView(0 /* Dest */, b.PerFrameSeqStreamMinIdx->GetGPUVirtualAddress());
    cmdList->SetComputeRoot32BitConstant(1 /* Consts */, tgOffset, 0 /* tgOffset */);
    cmdList->SetComputeRoot32BitConstant(1 /* Consts */, workItemCount, 1 /* workItemCount */);
    cmdList->SetComputeRoot32BitConstant(1 /* Consts */, value, 2 /* value */);
}

static void zstdgpu_Bind_Memset_BlockCountRawLookback(ID3D12GraphicsCommandList *cmdList, const zstdgpu_Srts &srts, const zstdgpu_GpuOnlyBuffers &b, uint32_t tgOffset, uint32_t workItemCount, uint32_t value)
{
    d3d12aid_ComputeRsPs_Set(&srts.Memset, cmdList);
    cmdList->SetComputeRootUnorderedAccessView(0 /* Dest */, b.PerFrameBlockCountRAWLookback->GetGPUVirtualAddress());
    cmdList->SetComputeRoot32BitConstant(1 /* Consts */, tgOffset, 0 /* tgOffset */);
    cmdList->SetComputeRoot32BitConstant(1 /* Consts */, workItemCount, 1 /* workItemCount */);
    cmdList->SetComputeRoot32BitConstant(1 /* Consts */, value, 2 /* value */);
}

static void zstdgpu_Bind_Memset_BlockCountRleLookback(ID3D12GraphicsCommandList *cmdList, const zstdgpu_Srts &srts, const zstdgpu_GpuOnlyBuffers &b, uint32_t tgOffset, uint32_t workItemCount, uint32_t value)
{
    d3d12aid_ComputeRsPs_Set(&srts.Memset, cmdList);
    cmdList->SetComputeRootUnorderedAccessView(0 /* Dest */, b.PerFrameBlockCountRLELookback->GetGPUVirtualAddress());
    cmdList->SetComputeRoot32BitConstant(1 /* Consts */, tgOffset, 0 /* tgOffset */);
    cmdList->SetComputeRoot32BitConstant(1 /* Consts */, workItemCount, 1 /* workItemCount */);
    cmdList->SetComputeRoot32BitConstant(1 /* Consts */, value, 2 /* value */);
}

static void zstdgpu_Bind_Memset_BlockCountCmpLookback(ID3D12GraphicsCommandList *cmdList, const zstdgpu_Srts &srts, const zstdgpu_GpuOnlyBuffers &b, uint32_t tgOffset, uint32_t workItemCount, uint32_t value)
{
    d3d12aid_ComputeRsPs_Set(&srts.Memset, cmdList);
    cmdList->SetComputeRootUnorderedAccessView(0 /* Dest */, b.PerFrameBlockCountCMPLookback->GetGPUVirtualAddress());
    cmdList->SetComputeRoot32BitConstant(1 /* Consts */, tgOffset, 0 /* tgOffset */);
    cmdList->SetComputeRoot32BitConstant(1 /* Consts */, workItemCount, 1 /* workItemCount */);
    cmdList->SetComputeRoot32BitConstant(1 /* Consts */, value, 2 /* value */);
}

static void zstdgpu_Bind_Memset_BlockCountAllLookback(ID3D12GraphicsCommandList *cmdList, const zstdgpu_Srts &srts, const zstdgpu_GpuOnlyBuffers &b, uint32_t tgOffset, uint32_t workItemCount, uint32_t value)
{
    d3d12aid_ComputeRsPs_Set(&srts.Memset, cmdList);
    cmdList->SetComputeRootUnorderedAccessView(0 /* Dest */, b.PerFrameBlockCountAllLookback->GetGPUVirtualAddress());
    cmdList->SetComputeRoot32BitConstant(1 /* Consts */, tgOffset, 0 /* tgOffset */);
    cmdList->SetComputeRoot32BitConstant(1 /* Consts */, workItemCount, 1 /* workItemCount */);
    cmdList->SetComputeRoot32BitConstant(1 /* Consts */, value, 2 /* value */);
}

static void zstdgpu_Bind_Memset_RawBlockSizePrefixLookback(ID3D12GraphicsCommandList *cmdList, const zstdgpu_Srts &srts, const zstdgpu_GpuOnlyBuffers &b, uint32_t value)
{
    d3d12aid_ComputeRsPs_Set(&srts.Memset, cmdList);
    cmdList->SetComputeRootUnorderedAccessView(0 /* Dest */, b.RawBlockSizePrefixLookback->GetGPUVirtualAddress());
    cmdList->SetComputeRoot32BitConstant(1 /* Consts */, value, 2 /* value */);
}

static void zstdgpu_Bind_Memset_RleBlockSizePrefixLookback(ID3D12GraphicsCommandList *cmdList, const zstdgpu_Srts &srts, const zstdgpu_GpuOnlyBuffers &b, uint32_t value)
{
    d3d12aid_ComputeRsPs_Set(&srts.Memset, cmdList);
    cmdList->SetComputeRootUnorderedAccessView(0 /* Dest */, b.RleBlockSizePrefixLookback->GetGPUVirtualAddress());
    cmdList->SetComputeRoot32BitConstant(1 /* Consts */, value, 2 /* value */);
}

static void zstdgpu_Bind_Memset_LitGroupEndPerHuffmanTableLookback(ID3D12GraphicsCommandList *cmdList, const zstdgpu_Srts &srts, const zstdgpu_GpuOnlyBuffers &b, uint32_t value)
{
    d3d12aid_ComputeRsPs_Set(&srts.Memset, cmdList);
    cmdList->SetComputeRootUnorderedAccessView(0 /* Dest */, b.LitGroupEndPerHuffmanTableLookback->GetGPUVirtualAddress());
    cmdList->SetComputeRoot32BitConstant(1 /* Consts */, value, 2 /* value */);
}

static void zstdgpu_Bind_Memset_PerSeqStreamFinalOffset1Lookback(ID3D12GraphicsCommandList *cmdList, const zstdgpu_Srts &srts, const zstdgpu_GpuOnlyBuffers &b, uint32_t value)
{
    d3d12aid_ComputeRsPs_Set(&srts.Memset, cmdList);
    cmdList->SetComputeRootUnorderedAccessView(0 /* Dest */, b.PerSeqStreamFinalOffset1Lookback->GetGPUVirtualAddress());
    cmdList->SetComputeRoot32BitConstant(1 /* Consts */, value, 2 /* value */);
}

static void zstdgpu_Bind_Memset_PerSeqStreamFinalOffset2Lookback(ID3D12GraphicsCommandList *cmdList, const zstdgpu_Srts &srts, const zstdgpu_GpuOnlyBuffers &b, uint32_t value)
{
    d3d12aid_ComputeRsPs_Set(&srts.Memset, cmdList);
    cmdList->SetComputeRootUnorderedAccessView(0 /* Dest */, b.PerSeqStreamFinalOffset2Lookback->GetGPUVirtualAddress());
    cmdList->SetComputeRoot32BitConstant(1 /* Consts */, value, 2 /* value */);
}

static void zstdgpu_Bind_Memset_PerSeqStreamFinalOffset3Lookback(ID3D12GraphicsCommandList *cmdList, const zstdgpu_Srts &srts, const zstdgpu_GpuOnlyBuffers &b, uint32_t value)
{
    d3d12aid_ComputeRsPs_Set(&srts.Memset, cmdList);
    cmdList->SetComputeRootUnorderedAccessView(0 /* Dest */, b.PerSeqStreamFinalOffset3Lookback->GetGPUVirtualAddress());
    cmdList->SetComputeRoot32BitConstant(1 /* Consts */, value, 2 /* value */);
}

static void zstdgpu_Bind_Memset_SeqCountPrefixLookback(ID3D12GraphicsCommandList *cmdList, const zstdgpu_Srts &srts, const zstdgpu_GpuOnlyBuffers &b, uint32_t value)
{
    d3d12aid_ComputeRsPs_Set(&srts.Memset, cmdList);
    cmdList->SetComputeRootUnorderedAccessView(0 /* Dest */, b.SeqCountPrefixLookback->GetGPUVirtualAddress());
    cmdList->SetComputeRoot32BitConstant(1 /* Consts */, value, 2 /* value */);
}

static void zstdgpu_Bind_Memset_BlockSeqCountPrefixLookback(ID3D12GraphicsCommandList *cmdList, const zstdgpu_Srts &srts, const zstdgpu_GpuOnlyBuffers &b, uint32_t value)
{
    d3d12aid_ComputeRsPs_Set(&srts.Memset, cmdList);
    cmdList->SetComputeRootUnorderedAccessView(0 /* Dest */, b.BlockSeqCountPrefixLookback->GetGPUVirtualAddress());
    cmdList->SetComputeRoot32BitConstant(1 /* Consts */, value, 2 /* value */);
}

static void zstdgpu_Bind_Memset_LitStreamCountPrefixLookback(ID3D12GraphicsCommandList *cmdList, const zstdgpu_Srts &srts, const zstdgpu_GpuOnlyBuffers &b, uint32_t value)
{
    d3d12aid_ComputeRsPs_Set(&srts.Memset, cmdList);
    cmdList->SetComputeRootUnorderedAccessView(0 /* Dest */, b.LitStreamCountPrefixLookback->GetGPUVirtualAddress());
    cmdList->SetComputeRoot32BitConstant(1 /* Consts */, value, 2 /* value */);
}

static void zstdgpu_Bind_Memset_HufLitCompactionLookback(ID3D12GraphicsCommandList *cmdList, const zstdgpu_Srts &srts, const zstdgpu_GpuOnlyBuffers &b, uint32_t value)
{
    d3d12aid_ComputeRsPs_Set(&srts.Memset, cmdList);
    cmdList->SetComputeRootUnorderedAccessView(0 /* Dest */, b.HufLitCompactionLookback->GetGPUVirtualAddress());
    cmdList->SetComputeRoot32BitConstant(1 /* Consts */, value, 2 /* value */);
}

static void zstdgpu_Bind_Memset_FseIndexLookbackLLen(ID3D12GraphicsCommandList *cmdList, const zstdgpu_Srts &srts, const zstdgpu_GpuOnlyBuffers &b, uint32_t value)
{
    d3d12aid_ComputeRsPs_Set(&srts.Memset, cmdList);
    cmdList->SetComputeRootUnorderedAccessView(0 /* Dest */, b.FseIndexLookbackLLen->GetGPUVirtualAddress());
    cmdList->SetComputeRoot32BitConstant(1 /* Consts */, value, 2 /* value */);
}

static void zstdgpu_Bind_Memset_FseIndexLookbackOffs(ID3D12GraphicsCommandList *cmdList, const zstdgpu_Srts &srts, const zstdgpu_GpuOnlyBuffers &b, uint32_t value)
{
    d3d12aid_ComputeRsPs_Set(&srts.Memset, cmdList);
    cmdList->SetComputeRootUnorderedAccessView(0 /* Dest */, b.FseIndexLookbackOffs->GetGPUVirtualAddress());
    cmdList->SetComputeRoot32BitConstant(1 /* Consts */, value, 2 /* value */);
}

static void zstdgpu_Bind_Memset_FseIndexLookbackMLen(ID3D12GraphicsCommandList *cmdList, const zstdgpu_Srts &srts, const zstdgpu_GpuOnlyBuffers &b, uint32_t value)
{
    d3d12aid_ComputeRsPs_Set(&srts.Memset, cmdList);
    cmdList->SetComputeRootUnorderedAccessView(0 /* Dest */, b.FseIndexLookbackMLen->GetGPUVirtualAddress());
    cmdList->SetComputeRoot32BitConstant(1 /* Consts */, value, 2 /* value */);
}

static void zstdgpu_Bind_Memset_HufWIdToHufLitId(ID3D12GraphicsCommandList *cmdList, const zstdgpu_Srts &srts, const zstdgpu_GpuOnlyBuffers &b, uint32_t value)
{
    d3d12aid_ComputeRsPs_Set(&srts.Memset, cmdList);
    cmdList->SetComputeRootUnorderedAccessView(0 /* Dest */, b.HufWIdToHufLitId->GetGPUVirtualAddress());
    cmdList->SetComputeRoot32BitConstant(1 /* Consts */, value, 2 /* value */);
}

static void zstdgpu_Bind_Memset_BlockSizePrefixLookback(ID3D12GraphicsCommandList *cmdList, const zstdgpu_Srts &srts, const zstdgpu_GpuOnlyBuffers &b, uint32_t value)
{
    d3d12aid_ComputeRsPs_Set(&srts.Memset, cmdList);
    cmdList->SetComputeRootUnorderedAccessView(0 /* Dest */, b.BlockSizePrefixLookback->GetGPUVirtualAddress());
    cmdList->SetComputeRoot32BitConstant(1 /* Consts */, value, 2 /* value */);
}

static void zstdgpu_Bind_PrefixSum_BlockCountRaw(ID3D12GraphicsCommandList *cmdList, const zstdgpu_Srts &srts, const zstdgpu_GpuOnlyBuffers &b, uint32_t tgOffset, uint32_t workItemCount, uint32_t outputInclusive)
{
    d3d12aid_ComputeRsPs_Set(&srts.PrefixSum, cmdList);
    cmdList->SetComputeRootUnorderedAccessView(0 /* InCountsOutPrefix */, b.PerFrameBlockCountRAW->GetGPUVirtualAddress());
    cmdList->SetComputeRootUnorderedAccessView(1 /* InCountsOutPrefixLookback */, b.PerFrameBlockCountRAWLookback->GetGPUVirtualAddress());
    cmdList->SetComputeRoot32BitConstant(2 /* Consts */, tgOffset, 0 /* tgOffset */);
    cmdList->SetComputeRoot32BitConstant(2 /* Consts */, workItemCount, 1 /* workItemCount */);
    cmdList->SetComputeRoot32BitConstant(2 /* Consts */, outputInclusive, 2 /* outputInclusive */);
}

static void zstdgpu_Bind_PrefixSum_BlockCountRle(ID3D12GraphicsCommandList *cmdList, const zstdgpu_Srts &srts, const zstdgpu_GpuOnlyBuffers &b, uint32_t tgOffset, uint32_t workItemCount, uint32_t outputInclusive)
{
    d3d12aid_ComputeRsPs_Set(&srts.PrefixSum, cmdList);
    cmdList->SetComputeRootUnorderedAccessView(0 /* InCountsOutPrefix */, b.PerFrameBlockCountRLE->GetGPUVirtualAddress());
    cmdList->SetComputeRootUnorderedAccessView(1 /* InCountsOutPrefixLookback */, b.PerFrameBlockCountRLELookback->GetGPUVirtualAddress());
    cmdList->SetComputeRoot32BitConstant(2 /* Consts */, tgOffset, 0 /* tgOffset */);
    cmdList->SetComputeRoot32BitConstant(2 /* Consts */, workItemCount, 1 /* workItemCount */);
    cmdList->SetComputeRoot32BitConstant(2 /* Consts */, outputInclusive, 2 /* outputInclusive */);
}

static void zstdgpu_Bind_PrefixSum_BlockCountCmp(ID3D12GraphicsCommandList *cmdList, const zstdgpu_Srts &srts, const zstdgpu_GpuOnlyBuffers &b, uint32_t tgOffset, uint32_t workItemCount, uint32_t outputInclusive)
{
    d3d12aid_ComputeRsPs_Set(&srts.PrefixSum, cmdList);
    cmdList->SetComputeRootUnorderedAccessView(0 /* InCountsOutPrefix */, b.PerFrameBlockCountCMP->GetGPUVirtualAddress());
    cmdList->SetComputeRootUnorderedAccessView(1 /* InCountsOutPrefixLookback */, b.PerFrameBlockCountCMPLookback->GetGPUVirtualAddress());
    cmdList->SetComputeRoot32BitConstant(2 /* Consts */, tgOffset, 0 /* tgOffset */);
    cmdList->SetComputeRoot32BitConstant(2 /* Consts */, workItemCount, 1 /* workItemCount */);
    cmdList->SetComputeRoot32BitConstant(2 /* Consts */, outputInclusive, 2 /* outputInclusive */);
}

static void zstdgpu_Bind_PrefixSum_BlockCountAll(ID3D12GraphicsCommandList *cmdList, const zstdgpu_Srts &srts, const zstdgpu_GpuOnlyBuffers &b, uint32_t tgOffset, uint32_t workItemCount, uint32_t outputInclusive)
{
    d3d12aid_ComputeRsPs_Set(&srts.PrefixSum, cmdList);
    cmdList->SetComputeRootUnorderedAccessView(0 /* InCountsOutPrefix */, b.PerFrameBlockCountAll->GetGPUVirtualAddress());
    cmdList->SetComputeRootUnorderedAccessView(1 /* InCountsOutPrefixLookback */, b.PerFrameBlockCountAllLookback->GetGPUVirtualAddress());
    cmdList->SetComputeRoot32BitConstant(2 /* Consts */, tgOffset, 0 /* tgOffset */);
    cmdList->SetComputeRoot32BitConstant(2 /* Consts */, workItemCount, 1 /* workItemCount */);
    cmdList->SetComputeRoot32BitConstant(2 /* Consts */, outputInclusive, 2 /* outputInclusive */);
}

static void zstdgpu_Bind_PrefixSum_BlockSizesRaw(ID3D12GraphicsCommandList *cmdList, const zstdgpu_Srts &srts, const zstdgpu_GpuOnlyBuffers &b, uint32_t outputInclusive)
{
    d3d12aid_ComputeRsPs_Set(&srts.PrefixSum, cmdList);
    cmdList->SetComputeRootUnorderedAccessView(0 /* InCountsOutPrefix */, b.RawBlockSizePrefix->GetGPUVirtualAddress());
    cmdList->SetComputeRootUnorderedAccessView(1 /* InCountsOutPrefixLookback */, b.RawBlockSizePrefixLookback->GetGPUVirtualAddress());
    cmdList->SetComputeRoot32BitConstant(2 /* Consts */, outputInclusive, 2 /* outputInclusive */);
}

static void zstdgpu_Bind_PrefixSum_BlockSizesRle(ID3D12GraphicsCommandList *cmdList, const zstdgpu_Srts &srts, const zstdgpu_GpuOnlyBuffers &b, uint32_t outputInclusive)
{
    d3d12aid_ComputeRsPs_Set(&srts.PrefixSum, cmdList);
    cmdList->SetComputeRootUnorderedAccessView(0 /* InCountsOutPrefix */, b.RleBlockSizePrefix->GetGPUVirtualAddress());
    cmdList->SetComputeRootUnorderedAccessView(1 /* InCountsOutPrefixLookback */, b.RleBlockSizePrefixLookback->GetGPUVirtualAddress());
    cmdList->SetComputeRoot32BitConstant(2 /* Consts */, outputInclusive, 2 /* outputInclusive */);
}

static void zstdgpu_Bind_PrefixSum_BlockSizesAll(ID3D12GraphicsCommandList *cmdList, const zstdgpu_Srts &srts, const zstdgpu_GpuOnlyBuffers &b, uint32_t outputInclusive)
{
    d3d12aid_ComputeRsPs_Set(&srts.PrefixSum, cmdList);
    cmdList->SetComputeRootUnorderedAccessView(0 /* InCountsOutPrefix */, b.BlockSizePrefix->GetGPUVirtualAddress());
    cmdList->SetComputeRootUnorderedAccessView(1 /* InCountsOutPrefixLookback */, b.BlockSizePrefixLookback->GetGPUVirtualAddress());
    cmdList->SetComputeRoot32BitConstant(2 /* Consts */, outputInclusive, 2 /* outputInclusive */);
}

static void zstdgpu_Bind_PropagateFseIndex_LLen(ID3D12GraphicsCommandList *cmdList, const zstdgpu_Srts &srts, const zstdgpu_GpuOnlyBuffers &b)
{
    d3d12aid_ComputeRsPs_Set(&srts.PropagateFseIndex, cmdList);
    cmdList->SetComputeRootUnorderedAccessView(0 /* FseIds */, b.SeqStreamToLLenFseId->GetGPUVirtualAddress());
    cmdList->SetComputeRootUnorderedAccessView(1 /* FseIndexLookback */, b.FseIndexLookbackLLen->GetGPUVirtualAddress());
}

static void zstdgpu_Bind_PropagateFseIndex_Offs(ID3D12GraphicsCommandList *cmdList, const zstdgpu_Srts &srts, const zstdgpu_GpuOnlyBuffers &b)
{
    d3d12aid_ComputeRsPs_Set(&srts.PropagateFseIndex, cmdList);
    cmdList->SetComputeRootUnorderedAccessView(0 /* FseIds */, b.SeqStreamToOffsFseId->GetGPUVirtualAddress());
    cmdList->SetComputeRootUnorderedAccessView(1 /* FseIndexLookback */, b.FseIndexLookbackOffs->GetGPUVirtualAddress());
}

static void zstdgpu_Bind_PropagateFseIndex_MLen(ID3D12GraphicsCommandList *cmdList, const zstdgpu_Srts &srts, const zstdgpu_GpuOnlyBuffers &b)
{
    d3d12aid_ComputeRsPs_Set(&srts.PropagateFseIndex, cmdList);
    cmdList->SetComputeRootUnorderedAccessView(0 /* FseIds */, b.SeqStreamToMLenFseId->GetGPUVirtualAddress());
    cmdList->SetComputeRootUnorderedAccessView(1 /* FseIndexLookback */, b.FseIndexLookbackMLen->GetGPUVirtualAddress());
}

static void zstdgpu_Bind_MemsetMemcpy_MemcpyRAW_Stage2(ID3D12GraphicsCommandList *cmdList, const zstdgpu_Srts &srts, const zstdgpu_GpuOnlyBuffers &b, uint32_t flags)
{
    d3d12aid_ComputeRsPs_Set(&srts.MemsetMemcpy, cmdList);
    cmdList->SetDescriptorHeaps(1, &srts.heap);
    cmdList->SetComputeRootDescriptorTable(0 /* FrameOutput */, srts.stage2.FrameOutput);
    cmdList->SetComputeRootShaderResourceView(1 /* Counters */, b.Counters->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(2 /* CompressedData */, b.CompressedData->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(3 /* BlockDestOffs */, b.BlockDestOffs->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(4 /* BlockSizePrefixTyped */, b.RawBlockSizePrefix->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(5 /* BlocksRefsTyped */, b.BlocksRAWRefs->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(6 /* GlobalBlockIndexTyped */, b.GlobalBlockIndexPerRawBlock->GetGPUVirtualAddress());
    cmdList->SetComputeRoot32BitConstant(7 /* Consts */, flags, 2 /* flags */);
}

static void zstdgpu_Bind_MemsetMemcpy_MemsetRLE_Stage2(ID3D12GraphicsCommandList *cmdList, const zstdgpu_Srts &srts, const zstdgpu_GpuOnlyBuffers &b, uint32_t flags)
{
    d3d12aid_ComputeRsPs_Set(&srts.MemsetMemcpy, cmdList);
    cmdList->SetDescriptorHeaps(1, &srts.heap);
    cmdList->SetComputeRootDescriptorTable(0 /* FrameOutput */, srts.stage2.FrameOutput);
    cmdList->SetComputeRootShaderResourceView(1 /* Counters */, b.Counters->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(2 /* CompressedData */, b.CompressedData->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(3 /* BlockDestOffs */, b.BlockDestOffs->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(4 /* BlockSizePrefixTyped */, b.RleBlockSizePrefix->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(5 /* BlocksRefsTyped */, b.BlocksRLERefs->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(6 /* GlobalBlockIndexTyped */, b.GlobalBlockIndexPerRleBlock->GetGPUVirtualAddress());
    cmdList->SetComputeRoot32BitConstant(7 /* Consts */, flags, 2 /* flags */);
}

static void zstdgpu_Bind_ParseFrames_Stage0(ID3D12GraphicsCommandList *cmdList, const zstdgpu_Srts &srts, const zstdgpu_GpuOnlyBuffers &, uint32_t frameCount, uint32_t compressedBufferSizeInBytes, uint32_t countBlocksOnly)
{
    d3d12aid_ComputeRsPs_Set(&srts.ParseFrames, cmdList);
    cmdList->SetDescriptorHeaps(1, &srts.heap);
    cmdList->SetComputeRootDescriptorTable(0 /* ParseFrames */, srts.stage0.ParseFrames);
    cmdList->SetComputeRoot32BitConstant(1 /* Consts */, frameCount, 0 /* frameCount */);
    cmdList->SetComputeRoot32BitConstant(1 /* Consts */, compressedBufferSizeInBytes, 1 /* compressedBufferSizeInBytes */);
    cmdList->SetComputeRoot32BitConstant(1 /* Consts */, countBlocksOnly, 2 /* countBlocksOnly */);
}

static void zstdgpu_Bind_ParseFrames_Stage1(ID3D12GraphicsCommandList *cmdList, const zstdgpu_Srts &srts, const zstdgpu_GpuOnlyBuffers &, uint32_t frameCount, uint32_t compressedBufferSizeInBytes, uint32_t countBlocksOnly)
{
    d3d12aid_ComputeRsPs_Set(&srts.ParseFrames, cmdList);
    cmdList->SetDescriptorHeaps(1, &srts.heap);
    cmdList->SetComputeRootDescriptorTable(0 /* ParseFrames */, srts.stage1.ParseFrames);
    cmdList->SetComputeRoot32BitConstant(1 /* Consts */, frameCount, 0 /* frameCount */);
    cmdList->SetComputeRoot32BitConstant(1 /* Consts */, compressedBufferSizeInBytes, 1 /* compressedBufferSizeInBytes */);
    cmdList->SetComputeRoot32BitConstant(1 /* Consts */, countBlocksOnly, 2 /* countBlocksOnly */);
}

static void zstdgpu_Bind_DecompressLiterals_Stage2(ID3D12GraphicsCommandList *cmdList, const zstdgpu_Srts &srts, const zstdgpu_GpuOnlyBuffers &)
{
    d3d12aid_ComputeRsPs_Set(&srts.DecompressLiterals, cmdList);
    cmdList->SetDescriptorHeaps(1, &srts.heap);
    cmdList->SetComputeRootDescriptorTable(0 /* LiteralStreams */, srts.stage2.LiteralStreams);
    cmdList->SetComputeRootDescriptorTable(1 /* HuffmanTable */, srts.stage2.HuffmanTable);
    cmdList->SetComputeRootDescriptorTable(2 /* LiteralDwords */, srts.stage2.LiteralDwords);
}

static void zstdgpu_Bind_InitHuffmanTableAndDecompressLiterals_Stage2(ID3D12GraphicsCommandList *cmdList, const zstdgpu_Srts &srts, const zstdgpu_GpuOnlyBuffers &)
{
    d3d12aid_ComputeRsPs_Set(&srts.InitHuffmanTableAndDecompressLiterals, cmdList);
    cmdList->SetDescriptorHeaps(1, &srts.heap);
    cmdList->SetComputeRootDescriptorTable(0 /* LiteralStreams */, srts.stage2.LiteralStreams);
    cmdList->SetComputeRootDescriptorTable(1 /* HuffmanWeights */, srts.stage2.HuffmanWeights);
}

static void zstdgpu_Bind_ComputePrefixSum(ID3D12GraphicsCommandList *cmdList, const zstdgpu_Srts &srts, const zstdgpu_GpuOnlyBuffers &b, uint32_t literalsPerGroup)
{
    d3d12aid_ComputeRsPs_Set(&srts.ComputePrefixSum, cmdList);
    cmdList->SetComputeRootShaderResourceView(0 /* HufWIdToHufLitId */, b.HufWIdToHufLitId->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(1 /* HufLitIdToLitStreamId */, b.HufLitIdToLitStreamId->GetGPUVirtualAddress());
    cmdList->SetComputeRootUnorderedAccessView(2 /* LitGroupEndPerHuffmanTable */, b.LitGroupEndPerHuffmanTable->GetGPUVirtualAddress());
    cmdList->SetComputeRootUnorderedAccessView(3 /* LitGroupEndPerHuffmanTableLookback */, b.LitGroupEndPerHuffmanTableLookback->GetGPUVirtualAddress());
    cmdList->SetComputeRootUnorderedAccessView(4 /* Counters */, b.Counters->GetGPUVirtualAddress());
    cmdList->SetComputeRoot32BitConstant(5 /* Consts */, literalsPerGroup, 2 /* literalsPerGroup */);
}

static void zstdgpu_Bind_PrefixSequenceOffsets(ID3D12GraphicsCommandList *cmdList, const zstdgpu_Srts &srts, const zstdgpu_GpuOnlyBuffers &b, uint32_t frameCount)
{
    d3d12aid_ComputeRsPs_Set(&srts.PrefixSequenceOffsets, cmdList);
    cmdList->SetComputeRootUnorderedAccessView(0 /* PerSeqStreamFinalOffset1 */, b.PerSeqStreamFinalOffset1->GetGPUVirtualAddress());
    cmdList->SetComputeRootUnorderedAccessView(1 /* PerSeqStreamFinalOffset2 */, b.PerSeqStreamFinalOffset2->GetGPUVirtualAddress());
    cmdList->SetComputeRootUnorderedAccessView(2 /* PerSeqStreamFinalOffset3 */, b.PerSeqStreamFinalOffset3->GetGPUVirtualAddress());
    cmdList->SetComputeRootUnorderedAccessView(3 /* PerSeqStreamFinalOffset1Lookback */, b.PerSeqStreamFinalOffset1Lookback->GetGPUVirtualAddress());
    cmdList->SetComputeRootUnorderedAccessView(4 /* PerSeqStreamFinalOffset2Lookback */, b.PerSeqStreamFinalOffset2Lookback->GetGPUVirtualAddress());
    cmdList->SetComputeRootUnorderedAccessView(5 /* PerSeqStreamFinalOffset3Lookback */, b.PerSeqStreamFinalOffset3Lookback->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(6 /* PerFrameSeqStreamMinIdx */, b.PerFrameSeqStreamMinIdx->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(7 /* PerFrameBlockCountAll */, b.PerFrameBlockCountAll->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(8 /* SeqStreamToBlockId */, b.SeqStreamToBlockId->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(9 /* Counters */, b.Counters->GetGPUVirtualAddress());
    cmdList->SetComputeRoot32BitConstant(10 /* Consts */, frameCount, 2 /* frameCount */);
}

static void zstdgpu_Bind_UpdateDispatchArgs(ID3D12GraphicsCommandList *cmdList, const zstdgpu_Srts &srts, const zstdgpu_GpuOnlyBuffers &b, uint32_t decompressSequences_StreamsPerTG, uint32_t stage, uint32_t cmpBlockCountMax, uint32_t rawBlockCountMax, uint32_t rleBlockCountMax, uint32_t litByteCountMax, uint32_t seqElemCountMax)
{
    d3d12aid_ComputeRsPs_Set(&srts.UpdateDispatchArgs, cmdList);
    cmdList->SetComputeRootUnorderedAccessView(0 /* Counters */, b.Counters->GetGPUVirtualAddress());
    cmdList->SetComputeRootUnorderedAccessView(1 /* DispatchArgs */, b.DispatchArgs->GetGPUVirtualAddress());
    cmdList->SetComputeRootUnorderedAccessView(2 /* DispatchCnts */, b.DispatchCnts->GetGPUVirtualAddress());
    cmdList->SetComputeRootUnorderedAccessView(3 /* Predicate */, b.Predicate->GetGPUVirtualAddress());
    cmdList->SetComputeRoot32BitConstant(4 /* Consts */, decompressSequences_StreamsPerTG, 0 /* decompressSequences_StreamsPerTG */);
    cmdList->SetComputeRoot32BitConstant(4 /* Consts */, stage, 1 /* stage */);
    cmdList->SetComputeRoot32BitConstant(4 /* Consts */, cmpBlockCountMax, 2 /* cmpBlockCountMax */);
    cmdList->SetComputeRoot32BitConstant(4 /* Consts */, rawBlockCountMax, 3 /* rawBlockCountMax */);
    cmdList->SetComputeRoot32BitConstant(4 /* Consts */, rleBlockCountMax, 4 /* rleBlockCountMax */);
    cmdList->SetComputeRoot32BitConstant(4 /* Consts */, litByteCountMax, 5 /* litByteCountMax */);
    cmdList->SetComputeRoot32BitConstant(4 /* Consts */, seqElemCountMax, 6 /* seqElemCountMax */);
}

static void zstdgpu_Bind_DecompressHuffmanWeights_Stage2(ID3D12GraphicsCommandList *cmdList, const zstdgpu_Srts &srts, const zstdgpu_GpuOnlyBuffers &b)
{
    d3d12aid_ComputeRsPs_Set(&srts.DecompressHuffmanWeights, cmdList);
    cmdList->SetDescriptorHeaps(1, &srts.heap);
    cmdList->SetComputeRootDescriptorTable(0 /* HuffmanWeightsWrite */, srts.stage2.HuffmanWeightsWrite);
    cmdList->SetComputeRootShaderResourceView(1 /* Counters */, b.Counters->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(2 /* CompressedData */, b.CompressedData->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(3 /* HufRefs */, b.HufRefs->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(4 /* FseInfos */, b.FseInfos->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(5 /* FseElems */, b.FseElems->GetGPUVirtualAddress());
}

static void zstdgpu_Bind_DecodeHuffmanWeights_Stage2(ID3D12GraphicsCommandList *cmdList, const zstdgpu_Srts &srts, const zstdgpu_GpuOnlyBuffers &b, uint32_t compressedBufferSizeInBytes)
{
    d3d12aid_ComputeRsPs_Set(&srts.DecodeHuffmanWeights, cmdList);
    cmdList->SetDescriptorHeaps(1, &srts.heap);
    cmdList->SetComputeRootDescriptorTable(0 /* HuffmanWeightsWrite */, srts.stage2.HuffmanWeightsWrite);
    cmdList->SetComputeRootShaderResourceView(1 /* Counters */, b.Counters->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(2 /* CompressedData */, b.CompressedData->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(3 /* HufRefs */, b.HufRefs->GetGPUVirtualAddress());
    cmdList->SetComputeRoot32BitConstant(4 /* Consts */, compressedBufferSizeInBytes, 2 /* compressedBufferSizeInBytes */);
}

static void zstdgpu_Bind_InitHuffmanTable_Stage2(ID3D12GraphicsCommandList *cmdList, const zstdgpu_Srts &srts, const zstdgpu_GpuOnlyBuffers &b, uint32_t fseCompressed)
{
    d3d12aid_ComputeRsPs_Set(&srts.InitHuffmanTable, cmdList);
    cmdList->SetDescriptorHeaps(1, &srts.heap);
    cmdList->SetComputeRootDescriptorTable(0 /* HuffmanWeights */, srts.stage2.HuffmanWeights);
    cmdList->SetComputeRootDescriptorTable(1 /* HuffmanTableWrite */, srts.stage2.HuffmanTableWrite);
    cmdList->SetComputeRootShaderResourceView(2 /* Counters */, b.Counters->GetGPUVirtualAddress());
    cmdList->SetComputeRoot32BitConstant(3 /* Consts */, fseCompressed, 2 /* fseCompressed */);
}

static void zstdgpu_Bind_DecompressSequences_Stage2(ID3D12GraphicsCommandList *cmdList, const zstdgpu_Srts &srts, const zstdgpu_GpuOnlyBuffers &b)
{
    d3d12aid_ComputeRsPs_Set(&srts.DecompressSequences, cmdList);
    cmdList->SetDescriptorHeaps(1, &srts.heap);
    cmdList->SetComputeRootDescriptorTable(0 /* SequenceOutputs */, srts.stage2.SequenceOutputs);
    cmdList->SetComputeRootShaderResourceView(1 /* Counters */, b.Counters->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(2 /* CompressedData */, b.CompressedData->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(3 /* SeqStreamToRef */, b.SeqStreamToRef->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(4 /* SeqStreamToLLenFseId */, b.SeqStreamToLLenFseId->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(5 /* SeqStreamToOffsFseId */, b.SeqStreamToOffsFseId->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(6 /* SeqStreamToMLenFseId */, b.SeqStreamToMLenFseId->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(7 /* SeqStreamToBlockId */, b.SeqStreamToBlockId->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(8 /* FseInfos */, b.FseInfos->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(9 /* PerSeqStreamSeqStart */, b.PerSeqStreamSeqStart->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(10 /* FseElems */, b.FseElems->GetGPUVirtualAddress());
}

static void zstdgpu_Bind_FinaliseSequenceOffsets(ID3D12GraphicsCommandList *cmdList, const zstdgpu_Srts &srts, const zstdgpu_GpuOnlyBuffers &b)
{
    d3d12aid_ComputeRsPs_Set(&srts.FinaliseSequenceOffsets, cmdList);
    cmdList->SetComputeRootUnorderedAccessView(0 /* DecompressedSequenceOffs */, b.DecompressedSequenceOffs->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(1 /* Counters */, b.Counters->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(2 /* PerSeqStreamFinalOffset1 */, b.PerSeqStreamFinalOffset1->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(3 /* PerSeqStreamFinalOffset2 */, b.PerSeqStreamFinalOffset2->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(4 /* PerSeqStreamFinalOffset3 */, b.PerSeqStreamFinalOffset3->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(5 /* PerSeqStreamSeqStart */, b.PerSeqStreamSeqStart->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(6 /* PerFrameBlockCountAll */, b.PerFrameBlockCountAll->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(7 /* PerFrameSeqStreamMinIdx */, b.PerFrameSeqStreamMinIdx->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(8 /* SeqStreamToBlockId */, b.SeqStreamToBlockId->GetGPUVirtualAddress());
}

static void zstdgpu_Bind_InitFseTable_Stage2(ID3D12GraphicsCommandList *cmdList, const zstdgpu_Srts &srts, const zstdgpu_GpuOnlyBuffers &b, uint32_t tableType)
{
    d3d12aid_ComputeRsPs_Set(&srts.InitFseTable, cmdList);
    cmdList->SetDescriptorHeaps(1, &srts.heap);
    cmdList->SetComputeRootDescriptorTable(0 /* FseProbsRead */, srts.stage2.FseProbsRead);
    cmdList->SetComputeRootUnorderedAccessView(1 /* FseElems */, b.FseElems->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(2 /* FseInfos */, b.FseInfos->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(3 /* Counters */, b.Counters->GetGPUVirtualAddress());
    cmdList->SetComputeRoot32BitConstant(4 /* Consts */, tableType, 2 /* tableType */);
}

static void zstdgpu_Bind_ComputeDestBlockOffsets(ID3D12GraphicsCommandList *cmdList, const zstdgpu_Srts &srts, const zstdgpu_GpuOnlyBuffers &b, uint32_t frameCount)
{
    d3d12aid_ComputeRsPs_Set(&srts.ComputeDestBlockOffsets, cmdList);
    cmdList->SetComputeRootUnorderedAccessView(0 /* BlockDestOffs */, b.BlockDestOffs->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(1 /* BlockSizePrefix */, b.BlockSizePrefix->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(2 /* PerFrameBlockCountAll */, b.PerFrameBlockCountAll->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(3 /* UnCompressedFramesRefs */, b.UnCompressedFramesRefs->GetGPUVirtualAddress());
    cmdList->SetComputeRoot32BitConstant(4 /* Consts */, frameCount, 2 /* frameCount */);
}

static void zstdgpu_Bind_ExecuteSequences_Stage2(ID3D12GraphicsCommandList *cmdList, const zstdgpu_Srts &srts, const zstdgpu_GpuOnlyBuffers &b)
{
    d3d12aid_ComputeRsPs_Set(&srts.ExecuteSequences, cmdList);
    cmdList->SetDescriptorHeaps(1, &srts.heap);
    cmdList->SetComputeRootDescriptorTable(0 /* LiteralBytes */, srts.stage2.LiteralBytes);
    cmdList->SetComputeRootDescriptorTable(1 /* FrameOutput */, srts.stage2.FrameOutput);
    cmdList->SetComputeRootShaderResourceView(2 /* Counters */, b.Counters->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(3 /* PerFrameBlockCountCMP */, b.PerFrameBlockCountCMP->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(4 /* BlockSizePrefix */, b.BlockSizePrefix->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(5 /* BlockDestOffs */, b.BlockDestOffs->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(6 /* DecompressedSequenceLLen */, b.DecompressedSequenceLLen->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(7 /* DecompressedSequenceMLen */, b.DecompressedSequenceMLen->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(8 /* DecompressedSequenceOffs */, b.DecompressedSequenceOffs->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(9 /* GlobalBlockIndexPerCmpBlock */, b.GlobalBlockIndexPerCmpBlock->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(10 /* PerSeqStreamSeqStart */, b.PerSeqStreamSeqStart->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(11 /* CompressedBlocks */, b.CompressedBlocks->GetGPUVirtualAddress());
}

static void zstdgpu_Bind_ComputeDestSequenceOffsets(ID3D12GraphicsCommandList *cmdList, const zstdgpu_Srts &srts, const zstdgpu_GpuOnlyBuffers &b, uint32_t tgOffset, uint32_t workItemCount)
{
    d3d12aid_ComputeRsPs_Set(&srts.ComputeDestSequenceOffsets, cmdList);
    cmdList->SetComputeRootUnorderedAccessView(0 /* DestSequenceOffsets */, b.DestSequenceOffsets->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(1 /* Counters */, b.Counters->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(2 /* BlockDestOffs */, b.BlockDestOffs->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(3 /* DecompressedSequenceMLen */, b.DecompressedSequenceMLen->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(4 /* PerSeqStreamSeqStart */, b.PerSeqStreamSeqStart->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(5 /* SeqStreamToBlockId */, b.SeqStreamToBlockId->GetGPUVirtualAddress());
    cmdList->SetComputeRoot32BitConstant(6 /* Consts */, tgOffset, 0 /* tgOffset */);
    cmdList->SetComputeRoot32BitConstant(6 /* Consts */, workItemCount, 1 /* workItemCount */);
}

static void zstdgpu_Bind_InitResources_Stage0(ID3D12GraphicsCommandList *cmdList, const zstdgpu_Srts &srts, const zstdgpu_GpuOnlyBuffers &b, uint32_t initResourcesStage)
{
    d3d12aid_ComputeRsPs_Set(&srts.InitResources, cmdList);
    cmdList->SetDescriptorHeaps(1, &srts.heap);
    cmdList->SetComputeRootDescriptorTable(0 /* FseInit */, srts.stage0.FseInit);
    cmdList->SetComputeRootUnorderedAccessView(1 /* Counters */, b.Counters->GetGPUVirtualAddress());
    cmdList->SetComputeRoot32BitConstant(2 /* Consts */, initResourcesStage, 0 /* initResourcesStage */);
}

static void zstdgpu_Bind_InitResources_Stage1(ID3D12GraphicsCommandList *cmdList, const zstdgpu_Srts &srts, const zstdgpu_GpuOnlyBuffers &b, uint32_t initResourcesStage)
{
    d3d12aid_ComputeRsPs_Set(&srts.InitResources, cmdList);
    cmdList->SetDescriptorHeaps(1, &srts.heap);
    cmdList->SetComputeRootDescriptorTable(0 /* FseInit */, srts.stage1.FseInit);
    cmdList->SetComputeRootUnorderedAccessView(1 /* Counters */, b.Counters->GetGPUVirtualAddress());
    cmdList->SetComputeRoot32BitConstant(2 /* Consts */, initResourcesStage, 0 /* initResourcesStage */);
}

static void zstdgpu_Bind_ParseCompressedBlocks_Stage1(ID3D12GraphicsCommandList *cmdList, const zstdgpu_Srts &srts, const zstdgpu_GpuOnlyBuffers &b, uint32_t compressedBufferSizeInBytes, uint32_t frameCount)
{
    d3d12aid_ComputeRsPs_Set(&srts.ParseCompressedBlocks, cmdList);
    cmdList->SetDescriptorHeaps(1, &srts.heap);
    cmdList->SetComputeRootDescriptorTable(0 /* ParseBlocksWrite */, srts.stage1.ParseBlocksWrite);
    cmdList->SetComputeRootShaderResourceView(1 /* CompressedData */, b.CompressedData->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(2 /* BlocksCMPRefs */, b.BlocksCMPRefs->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(3 /* PerFrameBlockCountCMP */, b.PerFrameBlockCountCMP->GetGPUVirtualAddress());
    cmdList->SetComputeRootShaderResourceView(4 /* GlobalBlockIndexPerCmpBlock */, b.GlobalBlockIndexPerCmpBlock->GetGPUVirtualAddress());
    cmdList->SetComputeRoot32BitConstant(5 /* Consts */, compressedBufferSizeInBytes, 2 /* compressedBufferSizeInBytes */);
    cmdList->SetComputeRoot32BitConstant(5 /* Consts */, frameCount, 3 /* frameCount */);
}

#endif /* ZSTDGPU_SRT_GENERATED_BIND_H */
