/**
 * Copyright (c) Microsoft. All rights reserved.
 * This code is licensed under the MIT License (MIT).
 * THIS CODE IS PROVIDED *AS IS* WITHOUT WARRANTY OF
 * ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING ANY
 * IMPLIED WARRANTIES OF FITNESS FOR A PARTICULAR
 * PURPOSE, MERCHANTABILITY, OR NON-INFRINGEMENT.
 *
 * Advanced Technology Group (ATG)
 *
 * AUTO-GENERATED by zstdgpu_srt_tool.exe. DO NOT EDIT.
 * Source of truth: zstdgpu_srt_decl.h
 */

#ifndef ZSTDGPU_SRT_GENERATED_RS_BIND_GROUP_ParseBlocksWrite_H
#define ZSTDGPU_SRT_GENERATED_RS_BIND_GROUP_ParseBlocksWrite_H

#ifdef __hlsl_dx_compiler

#define ZSTDGPU_SRT_RS_BIND_GROUP_ParseBlocksWrite "DescriptorTable(UAV(u0, space=13, numDescriptors=22))"

ZSTDGPU_RW_BUFFER(zstdgpu_Counters)             ZstdInOutCounters                       : register(u0, space13);
ZSTDGPU_RW_BUFFER(zstdgpu_FseInfo)              ZstdInOutFseInfos                       : register(u1, space13);
ZSTDGPU_RW_BUFFER(zstdgpu_CompressedBlockData)  ZstdInOutCompressedBlocks               : register(u2, space13);
ZSTDGPU_RW_BUFFER(zstdgpu_OffsetAndSize)        ZstdInOutHufRefs                        : register(u3, space13);
ZSTDGPU_RW_BUFFER(zstdgpu_LitStreamInfo)        ZstdInOutLitRefs                        : register(u4, space13);
ZSTDGPU_RW_BUFFER(zstdgpu_OffsetAndSize)        ZstdInOutSeqStreamToRef                 : register(u5, space13);
ZSTDGPU_RW_BUFFER(uint32_t)                     ZstdInOutSeqStreamToLLenFseId           : register(u6, space13);
ZSTDGPU_RW_BUFFER(uint32_t)                     ZstdInOutSeqStreamToOffsFseId           : register(u7, space13);
ZSTDGPU_RW_BUFFER(uint32_t)                     ZstdInOutSeqStreamToMLenFseId           : register(u8, space13);
ZSTDGPU_RW_BUFFER(uint32_t)                     ZstdInOutSeqStreamToBlockId             : register(u9, space13);
ZSTDGPU_RW_BUFFER(uint32_t)                     ZstdInOutBlockSizePrefix                : register(u10, space13);
ZSTDGPU_RW_BUFFER(uint32_t)                     ZstdInOutPerFrameSeqStreamMinIdx        : register(u11, space13);
ZSTDGPU_RW_BUFFER(uint32_t)                     ZstdInOutPerSeqStreamSeqStart           : register(u12, space13);
ZSTDGPU_RW_BUFFER_GLC(uint32_t)                 ZstdInOutSeqCountPrefixLookback         : register(u13, space13);
ZSTDGPU_RW_BUFFER_GLC(uint32_t)                 ZstdInOutBlockSeqCountPrefixLookback    : register(u14, space13);
ZSTDGPU_RW_TYPED_BUFFER(int32_t, int16_t)       ZstdInOutFseProbs                       : register(u15, space13);
ZSTDGPU_RW_TYPED_BUFFER(uint32_t, uint8_t)      ZstdInOutDecompressedHuffmanWeightCount : register(u16, space13);
ZSTDGPU_RW_BUFFER_GLC(uint32_t)                 ZstdInOutLitStreamCountPrefixLookback   : register(u17, space13);
ZSTDGPU_RW_BUFFER(uint32_t)                     ZstdInOutHufWIdToHufLitId               : register(u18, space13);
ZSTDGPU_RW_BUFFER(uint32_t)                     ZstdInOutHufLitIdToLitStreamId          : register(u19, space13);
ZSTDGPU_RW_BUFFER(uint32_t)                     ZstdInOutHufLitIdToHufWId_DBG           : register(u20, space13);
ZSTDGPU_RW_BUFFER_GLC(uint32_t)                 ZstdInOutHufLitCompactionLookback       : register(u21, space13);

template<typename T>
static void zstdgpu_Srt_FillBindGroup_ParseBlocksWrite(ZSTDGPU_PARAM_INOUT(T) srt)
{
    srt.inoutCounters                       = ZstdInOutCounters;
    srt.inoutFseInfos                       = ZstdInOutFseInfos;
    srt.inoutCompressedBlocks               = ZstdInOutCompressedBlocks;
    srt.inoutHufRefs                        = ZstdInOutHufRefs;
    srt.inoutLitRefs                        = ZstdInOutLitRefs;
    srt.inoutSeqStreamToRef                 = ZstdInOutSeqStreamToRef;
    srt.inoutSeqStreamToLLenFseId           = ZstdInOutSeqStreamToLLenFseId;
    srt.inoutSeqStreamToOffsFseId           = ZstdInOutSeqStreamToOffsFseId;
    srt.inoutSeqStreamToMLenFseId           = ZstdInOutSeqStreamToMLenFseId;
    srt.inoutSeqStreamToBlockId             = ZstdInOutSeqStreamToBlockId;
    srt.inoutBlockSizePrefix                = ZstdInOutBlockSizePrefix;
    srt.inoutPerFrameSeqStreamMinIdx        = ZstdInOutPerFrameSeqStreamMinIdx;
    srt.inoutPerSeqStreamSeqStart           = ZstdInOutPerSeqStreamSeqStart;
    srt.inoutSeqCountPrefixLookback         = ZstdInOutSeqCountPrefixLookback;
    srt.inoutBlockSeqCountPrefixLookback    = ZstdInOutBlockSeqCountPrefixLookback;
    srt.inoutFseProbs                       = ZstdInOutFseProbs;
    srt.inoutDecompressedHuffmanWeightCount = ZstdInOutDecompressedHuffmanWeightCount;
    srt.inoutLitStreamCountPrefixLookback   = ZstdInOutLitStreamCountPrefixLookback;
    srt.inoutHufWIdToHufLitId               = ZstdInOutHufWIdToHufLitId;
    srt.inoutHufLitIdToLitStreamId          = ZstdInOutHufLitIdToLitStreamId;
    srt.inoutHufLitIdToHufWId_DBG           = ZstdInOutHufLitIdToHufWId_DBG;
    srt.inoutHufLitCompactionLookback       = ZstdInOutHufLitCompactionLookback;
}

#else

template<typename T>
static void zstdgpu_Srt_FillBindGroup_ParseBlocksWrite(T &srt, const zstdgpu_ResourceDataCpu &cpuRes)
{
    srt.inoutCounters                       = cpuRes.Counters;
    srt.inoutFseInfos                       = cpuRes.FseInfos;
    srt.inoutCompressedBlocks               = cpuRes.CompressedBlocks;
    srt.inoutHufRefs                        = cpuRes.HufRefs;
    srt.inoutLitRefs                        = cpuRes.LitRefs;
    srt.inoutSeqStreamToRef                 = cpuRes.SeqStreamToRef;
    srt.inoutSeqStreamToLLenFseId           = cpuRes.SeqStreamToLLenFseId;
    srt.inoutSeqStreamToOffsFseId           = cpuRes.SeqStreamToOffsFseId;
    srt.inoutSeqStreamToMLenFseId           = cpuRes.SeqStreamToMLenFseId;
    srt.inoutSeqStreamToBlockId             = cpuRes.SeqStreamToBlockId;
    srt.inoutBlockSizePrefix                = cpuRes.BlockSizePrefix;
    srt.inoutPerFrameSeqStreamMinIdx        = cpuRes.PerFrameSeqStreamMinIdx;
    srt.inoutPerSeqStreamSeqStart           = cpuRes.PerSeqStreamSeqStart;
    srt.inoutSeqCountPrefixLookback         = cpuRes.SeqCountPrefixLookback;
    srt.inoutBlockSeqCountPrefixLookback    = cpuRes.BlockSeqCountPrefixLookback;
    srt.inoutFseProbs                       = cpuRes.FseProbs;
    srt.inoutDecompressedHuffmanWeightCount = cpuRes.DecompressedHuffmanWeightCount;
    srt.inoutLitStreamCountPrefixLookback   = cpuRes.LitStreamCountPrefixLookback;
    srt.inoutHufWIdToHufLitId               = cpuRes.HufWIdToHufLitId;
    srt.inoutHufLitIdToLitStreamId          = cpuRes.HufLitIdToLitStreamId;
    srt.inoutHufLitIdToHufWId_DBG           = cpuRes.HufLitIdToHufWId_DBG;
    srt.inoutHufLitCompactionLookback       = cpuRes.HufLitCompactionLookback;
}

#endif /* #ifdef __hlsl_dx_compiler */
#endif /* ZSTDGPU_SRT_GENERATED_RS_BIND_GROUP_ParseBlocksWrite_H */
