/**
 * Copyright (c) Microsoft. All rights reserved.
 * This code is licensed under the MIT License (MIT).
 * THIS CODE IS PROVIDED *AS IS* WITHOUT WARRANTY OF
 * ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING ANY
 * IMPLIED WARRANTIES OF FITNESS FOR A PARTICULAR
 * PURPOSE, MERCHANTABILITY, OR NON-INFRINGEMENT.
 *
 * Advanced Technology Group (ATG)
 *
 * AUTO-GENERATED by zstdgpu_srt_tool.exe. DO NOT EDIT.
 * Source of truth: zstdgpu_srt_decl.h
 */

#ifndef ZSTDGPU_SRT_GENERATED_RS_BIND_GROUP_LiteralDwords_H
#define ZSTDGPU_SRT_GENERATED_RS_BIND_GROUP_LiteralDwords_H

#ifdef __hlsl_dx_compiler

#define ZSTDGPU_SRT_RS_BIND_GROUP_LiteralDwords "DescriptorTable(UAV(u0, space=4, numDescriptors=1))"

ZSTDGPU_RW_BUFFER(uint32_t) ZstdInOutDecompressedLiterals_Dwords    : register(u0, space4);

template<typename T>
static void zstdgpu_Srt_FillBindGroup_LiteralDwords(ZSTDGPU_PARAM_INOUT(T) srt)
{
    srt.inoutDecompressedLiterals_Dwords    = ZstdInOutDecompressedLiterals_Dwords;
}

#else

template<typename T>
static void zstdgpu_Srt_FillBindGroup_LiteralDwords(T &srt, const zstdgpu_ResourceDataCpu &cpuRes)
{
    srt.inoutDecompressedLiterals_Dwords    = cpuRes.DecompressedLiterals;
}

#endif /* #ifdef __hlsl_dx_compiler */
#endif /* ZSTDGPU_SRT_GENERATED_RS_BIND_GROUP_LiteralDwords_H */
