/**
 * Copyright (c) Microsoft. All rights reserved.
 * This code is licensed under the MIT License (MIT).
 * THIS CODE IS PROVIDED *AS IS* WITHOUT WARRANTY OF
 * ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING ANY
 * IMPLIED WARRANTIES OF FITNESS FOR A PARTICULAR
 * PURPOSE, MERCHANTABILITY, OR NON-INFRINGEMENT.
 *
 * Advanced Technology Group (ATG)
 *
 * AUTO-GENERATED by zstdgpu_srt_tool.exe. DO NOT EDIT.
 * Source of truth: zstdgpu_srt_decl.h
 */

#ifndef ZSTDGPU_SRT_GENERATED_STRUCTS_H
#define ZSTDGPU_SRT_GENERATED_STRUCTS_H

typedef struct zstdgpu_ParseFrames_SRT
{
    ZSTDGPU_RO_BUFFER(uint32_t)                             inCompressedData;
    ZSTDGPU_RO_BUFFER(zstdgpu_OffsetAndSize)                inFramesRefs;
    ZSTDGPU_RW_BUFFER(zstdgpu_Counters)                     inoutCounters;
    ZSTDGPU_RW_BUFFER(uint32_t)                             inoutPerFrameBlockCountRAW;
    ZSTDGPU_RW_BUFFER(uint32_t)                             inoutPerFrameBlockCountRLE;
    ZSTDGPU_RW_BUFFER(uint32_t)                             inoutPerFrameBlockCountCMP;
    ZSTDGPU_RW_BUFFER(uint32_t)                             inoutPerFrameBlockCountAll;
    ZSTDGPU_RW_BUFFER(uint32_t)                             inoutRawBlockSizePrefix;
    ZSTDGPU_RW_BUFFER(uint32_t)                             inoutRleBlockSizePrefix;
    ZSTDGPU_RW_BUFFER(zstdgpu_OffsetAndSize)                inoutBlocksRAWRefs;
    ZSTDGPU_RW_BUFFER(zstdgpu_OffsetAndSize)                inoutBlocksRLERefs;
    ZSTDGPU_RW_BUFFER(zstdgpu_OffsetAndSize)                inoutBlocksCMPRefs;
    ZSTDGPU_RW_BUFFER(uint32_t)                             inoutBlockSizePrefix;
    ZSTDGPU_RW_BUFFER(uint32_t)                             inoutGlobalBlockIndexPerRawBlock;
    ZSTDGPU_RW_BUFFER(uint32_t)                             inoutGlobalBlockIndexPerRleBlock;
    ZSTDGPU_RW_BUFFER(uint32_t)                             inoutGlobalBlockIndexPerCmpBlock;
    ZSTDGPU_RW_BUFFER(uint32_t)                             inoutFrameStatus;
    uint32_t                                                frameCount;
    uint32_t                                                compressedBufferSizeInBytes;
    uint32_t                                                countBlocksOnly;
} zstdgpu_ParseFrames_SRT;

typedef struct zstdgpu_Memset_SRT
{
    ZSTDGPU_RW_BUFFER(uint32_t)                             inoutDest;
    uint32_t                                                tgOffset;
    uint32_t                                                workItemCount;
    uint32_t                                                value;
} zstdgpu_Memset_SRT;

typedef struct zstdgpu_DecompressLiterals_SRT
{
    ZSTDGPU_RO_BUFFER(uint32_t)                             inLitGroupEndPerHuffmanTable;
    ZSTDGPU_RO_BUFFER(zstdgpu_Counters)                     inCounters;
    ZSTDGPU_RO_BUFFER(zstdgpu_LitStreamInfo)                inLitRefs;
    ZSTDGPU_RO_RAW_BUFFER(uint32_t)                         inCompressedData;
    ZSTDGPU_RO_BUFFER(uint32_t)                             inHufWIdToHufLitId;
    ZSTDGPU_RO_BUFFER(uint32_t)                             inHufLitIdToLitStreamId;
    ZSTDGPU_RW_TYPED_BUFFER(uint32_t, uint8_t)              inoutDecompressedLiterals;
    ZSTDGPU_RO_BUFFER(uint32_t)                             inHuffmanTableInfo;
    ZSTDGPU_RO_BUFFER(uint32_t)                             inHuffmanTableCodeAndSymbol;
    ZSTDGPU_RO_BUFFER(uint32_t)                             inHuffmanTableRankIndex;
    ZSTDGPU_RW_BUFFER(uint32_t)                             inoutDecompressedLiterals_Dwords;
    uint32_t                                                tgOffset;
    uint32_t                                                workItemCount;
} zstdgpu_DecompressLiterals_SRT;

typedef struct zstdgpu_InitHuffmanTableAndDecompressLiterals_SRT
{
    ZSTDGPU_RO_BUFFER(uint32_t)                             inLitGroupEndPerHuffmanTable;
    ZSTDGPU_RO_BUFFER(zstdgpu_Counters)                     inCounters;
    ZSTDGPU_RO_BUFFER(zstdgpu_LitStreamInfo)                inLitRefs;
    ZSTDGPU_RO_RAW_BUFFER(uint32_t)                         inCompressedData;
    ZSTDGPU_RO_BUFFER(uint32_t)                             inHufWIdToHufLitId;
    ZSTDGPU_RO_BUFFER(uint32_t)                             inHufLitIdToLitStreamId;
    ZSTDGPU_RW_TYPED_BUFFER(uint32_t, uint8_t)              inoutDecompressedLiterals;
    ZSTDGPU_RO_TYPED_BUFFER(uint32_t, uint8_t)              inDecompressedHuffmanWeights;
    ZSTDGPU_RO_TYPED_BUFFER(uint32_t, uint8_t)              inDecompressedHuffmanWeightCount;
    uint32_t                                                tgOffset;
    uint32_t                                                workItemCount;
} zstdgpu_InitHuffmanTableAndDecompressLiterals_SRT;

typedef struct zstdgpu_PrefixSum_SRT
{
    ZSTDGPU_RW_BUFFER(uint32_t)                             inoutInCountsOutPrefix;
    ZSTDGPU_RW_BUFFER_GLC(uint32_t)                         inoutInCountsOutPrefixLookback;
    uint32_t                                                tgOffset;
    uint32_t                                                workItemCount;
    uint32_t                                                outputInclusive;
} zstdgpu_PrefixSum_SRT;

typedef struct zstdgpu_PropagateFseIndex_SRT
{
    ZSTDGPU_RW_BUFFER(uint32_t)                             inoutFseIds;
    ZSTDGPU_RW_BUFFER_GLC(uint32_t)                         inoutFseIndexLookback;
    uint32_t                                                tgOffset;
    uint32_t                                                workItemCount;
} zstdgpu_PropagateFseIndex_SRT;

typedef struct zstdgpu_ComputePrefixSum_SRT
{
    ZSTDGPU_RO_BUFFER(uint32_t)                             inHufWIdToHufLitId;
    ZSTDGPU_RO_BUFFER(uint32_t)                             inHufLitIdToLitStreamId;
    ZSTDGPU_RW_BUFFER(uint32_t)                             inoutLitGroupEndPerHuffmanTable;
    ZSTDGPU_RW_BUFFER_GLC(uint32_t)                         inoutLitGroupEndPerHuffmanTableLookback;
    ZSTDGPU_RW_BUFFER(zstdgpu_Counters)                     inoutCounters;
    uint32_t                                                tgOffset;
    uint32_t                                                workItemCount;
    uint32_t                                                literalsPerGroup;
} zstdgpu_ComputePrefixSum_SRT;

typedef struct zstdgpu_PrefixSequenceOffsets_SRT
{
    ZSTDGPU_RW_BUFFER(uint32_t)                             inoutPerSeqStreamFinalOffset1;
    ZSTDGPU_RW_BUFFER(uint32_t)                             inoutPerSeqStreamFinalOffset2;
    ZSTDGPU_RW_BUFFER(uint32_t)                             inoutPerSeqStreamFinalOffset3;
    ZSTDGPU_RW_BUFFER_GLC(uint32_t)                         inoutPerSeqStreamFinalOffset1Lookback;
    ZSTDGPU_RW_BUFFER_GLC(uint32_t)                         inoutPerSeqStreamFinalOffset2Lookback;
    ZSTDGPU_RW_BUFFER_GLC(uint32_t)                         inoutPerSeqStreamFinalOffset3Lookback;
    ZSTDGPU_RO_BUFFER(uint32_t)                             inPerFrameSeqStreamMinIdx;
    ZSTDGPU_RO_BUFFER(uint32_t)                             inPerFrameBlockCountAll;
    ZSTDGPU_RO_BUFFER(uint32_t)                             inSeqStreamToBlockId;
    ZSTDGPU_RO_BUFFER(zstdgpu_Counters)                     inCounters;
    uint32_t                                                tgOffset;
    uint32_t                                                workItemCount;
    uint32_t                                                frameCount;
} zstdgpu_PrefixSequenceOffsets_SRT;

typedef struct zstdgpu_UpdateDispatchArgs_SRT
{
    ZSTDGPU_RW_BUFFER(zstdgpu_Counters)                     inoutCounters;
    ZSTDGPU_RW_BUFFER(uint32_t)                             inoutDispatchArgs;
    ZSTDGPU_RW_BUFFER(uint32_t)                             inoutDispatchCnts;
    ZSTDGPU_RW_BUFFER(uint32_t)                             inoutPredicate;
    uint32_t                                                decompressSequences_StreamsPerTG;
    uint32_t                                                stage;
    uint32_t                                                cmpBlockCountMax;
    uint32_t                                                rawBlockCountMax;
    uint32_t                                                rleBlockCountMax;
    uint32_t                                                litByteCountMax;
    uint32_t                                                seqElemCountMax;
} zstdgpu_UpdateDispatchArgs_SRT;

typedef struct zstdgpu_DecompressHuffmanWeights_SRT
{
    ZSTDGPU_RW_TYPED_BUFFER(uint32_t, uint8_t)              inoutDecompressedHuffmanWeights;
    ZSTDGPU_RW_TYPED_BUFFER(uint32_t, uint8_t)              inoutDecompressedHuffmanWeightCount;
    ZSTDGPU_RO_BUFFER(zstdgpu_Counters)                     inCounters;
    ZSTDGPU_RO_RAW_BUFFER(uint32_t)                         inCompressedData;
    ZSTDGPU_RO_BUFFER(zstdgpu_OffsetAndSize)                inHufRefs;
    ZSTDGPU_RO_BUFFER(zstdgpu_FseInfo)                      inFseInfos;
    ZSTDGPU_RO_BUFFER(uint32_t)                             inFseElems;
    uint32_t                                                tgOffset;
    uint32_t                                                workItemCount;
} zstdgpu_DecompressHuffmanWeights_SRT;

typedef struct zstdgpu_DecodeHuffmanWeights_SRT
{
    ZSTDGPU_RW_TYPED_BUFFER(uint32_t, uint8_t)              inoutDecompressedHuffmanWeights;
    ZSTDGPU_RW_TYPED_BUFFER(uint32_t, uint8_t)              inoutDecompressedHuffmanWeightCount;
    ZSTDGPU_RO_BUFFER(zstdgpu_Counters)                     inCounters;
    ZSTDGPU_RO_BUFFER(uint32_t)                             inCompressedData;
    ZSTDGPU_RO_BUFFER(zstdgpu_OffsetAndSize)                inHufRefs;
    uint32_t                                                tgOffset;
    uint32_t                                                workItemCount;
    uint32_t                                                compressedBufferSizeInBytes;
} zstdgpu_DecodeHuffmanWeights_SRT;

typedef struct zstdgpu_InitHuffmanTable_SRT
{
    ZSTDGPU_RO_TYPED_BUFFER(uint32_t, uint8_t)              inDecompressedHuffmanWeights;
    ZSTDGPU_RO_TYPED_BUFFER(uint32_t, uint8_t)              inDecompressedHuffmanWeightCount;
    ZSTDGPU_RW_BUFFER(uint32_t)                             inoutHuffmanTableInfo;
    ZSTDGPU_RW_BUFFER(uint32_t)                             inoutHuffmanTableCodeAndSymbol;
    ZSTDGPU_RW_BUFFER(uint32_t)                             inoutHuffmanTableRankIndex;
    ZSTDGPU_RO_BUFFER(zstdgpu_Counters)                     inCounters;
    uint32_t                                                tgOffset;
    uint32_t                                                workItemCount;
    uint32_t                                                fseCompressed;
} zstdgpu_InitHuffmanTable_SRT;

typedef struct zstdgpu_DecompressSequences_SRT
{
    ZSTDGPU_RW_BUFFER(uint32_t)                             inoutDecompressedSequenceLLen;
    ZSTDGPU_RW_BUFFER(uint32_t)                             inoutDecompressedSequenceMLen;
    ZSTDGPU_RW_BUFFER(uint32_t)                             inoutDecompressedSequenceOffs;
    ZSTDGPU_RW_BUFFER(uint32_t)                             inoutBlockSizePrefix;
    ZSTDGPU_RW_BUFFER(uint32_t)                             inoutPerSeqStreamFinalOffset1;
    ZSTDGPU_RW_BUFFER(uint32_t)                             inoutPerSeqStreamFinalOffset2;
    ZSTDGPU_RW_BUFFER(uint32_t)                             inoutPerSeqStreamFinalOffset3;
    ZSTDGPU_RO_BUFFER(zstdgpu_Counters)                     inCounters;
    ZSTDGPU_RO_RAW_BUFFER(uint32_t)                         inCompressedData;
    ZSTDGPU_RO_BUFFER(zstdgpu_OffsetAndSize)                inSeqStreamToRef;
    ZSTDGPU_RO_BUFFER(uint32_t)                             inSeqStreamToLLenFseId;
    ZSTDGPU_RO_BUFFER(uint32_t)                             inSeqStreamToOffsFseId;
    ZSTDGPU_RO_BUFFER(uint32_t)                             inSeqStreamToMLenFseId;
    ZSTDGPU_RO_BUFFER(uint32_t)                             inSeqStreamToBlockId;
    ZSTDGPU_RO_BUFFER(zstdgpu_FseInfo)                      inFseInfos;
    ZSTDGPU_RO_BUFFER(uint32_t)                             inPerSeqStreamSeqStart;
    ZSTDGPU_RO_BUFFER(uint32_t)                             inFseElems;
    uint32_t                                                tgOffset;
    uint32_t                                                workItemCount;
} zstdgpu_DecompressSequences_SRT;

typedef struct zstdgpu_FinaliseSequenceOffsets_SRT
{
    ZSTDGPU_RW_BUFFER(uint32_t)                             inoutDecompressedSequenceOffs;
    ZSTDGPU_RO_BUFFER(zstdgpu_Counters)                     inCounters;
    ZSTDGPU_RO_BUFFER(uint32_t)                             inPerSeqStreamFinalOffset1;
    ZSTDGPU_RO_BUFFER(uint32_t)                             inPerSeqStreamFinalOffset2;
    ZSTDGPU_RO_BUFFER(uint32_t)                             inPerSeqStreamFinalOffset3;
    ZSTDGPU_RO_BUFFER(uint32_t)                             inPerSeqStreamSeqStart;
    ZSTDGPU_RO_BUFFER(uint32_t)                             inPerFrameBlockCountAll;
    ZSTDGPU_RO_BUFFER(uint32_t)                             inPerFrameSeqStreamMinIdx;
    ZSTDGPU_RO_BUFFER(uint32_t)                             inSeqStreamToBlockId;
    uint32_t                                                tgOffset;
    uint32_t                                                workItemCount;
} zstdgpu_FinaliseSequenceOffsets_SRT;

typedef struct zstdgpu_InitFseTable_SRT
{
    ZSTDGPU_RO_TYPED_BUFFER(int32_t, int16_t)               inFseProbs;
    ZSTDGPU_RW_BUFFER(uint32_t)                             inoutFseElems;
    ZSTDGPU_RO_BUFFER(zstdgpu_FseInfo)                      inFseInfos;
    ZSTDGPU_RO_BUFFER(zstdgpu_Counters)                     inCounters;
    uint32_t                                                tgOffset;
    uint32_t                                                workItemCount;
    uint32_t                                                tableType;
    uint32_t                                                tableStartIndex;
    uint32_t                                                tableDataStart;
    uint32_t                                                tableDataCount;
} zstdgpu_InitFseTable_SRT;

typedef struct zstdgpu_ComputeDestBlockOffsets_SRT
{
    ZSTDGPU_RW_BUFFER(uint32_t)                             inoutBlockDestOffs;
    ZSTDGPU_RO_BUFFER(uint32_t)                             inBlockSizePrefix;
    ZSTDGPU_RO_BUFFER(uint32_t)                             inPerFrameBlockCountAll;
    ZSTDGPU_RO_BUFFER(zstdgpu_OffsetAndSize)                inUnCompressedFramesRefs;
    uint32_t                                                tgOffset;
    uint32_t                                                workItemCount;
    uint32_t                                                frameCount;
} zstdgpu_ComputeDestBlockOffsets_SRT;

typedef struct zstdgpu_ExecuteSequences_SRT
{
    ZSTDGPU_RO_TYPED_BUFFER(uint32_t, uint8_t)              inCompressedData;
    ZSTDGPU_RO_TYPED_BUFFER(uint32_t, uint8_t)              inDecompressedLiterals;
    ZSTDGPU_RW_TYPED_BUFFER(uint32_t, uint8_t)              inoutUnCompressedFramesData;
    ZSTDGPU_RO_BUFFER(zstdgpu_Counters)                     inCounters;
    ZSTDGPU_RO_BUFFER(uint32_t)                             inPerFrameBlockCountCMP;
    ZSTDGPU_RO_BUFFER(uint32_t)                             inBlockSizePrefix;
    ZSTDGPU_RO_BUFFER(uint32_t)                             inBlockDestOffs;
    ZSTDGPU_RO_BUFFER(uint32_t)                             inDecompressedSequenceLLen;
    ZSTDGPU_RO_BUFFER(uint32_t)                             inDecompressedSequenceMLen;
    ZSTDGPU_RO_BUFFER(uint32_t)                             inDecompressedSequenceOffs;
    ZSTDGPU_RO_BUFFER(uint32_t)                             inGlobalBlockIndexPerCmpBlock;
    ZSTDGPU_RO_BUFFER(uint32_t)                             inPerSeqStreamSeqStart;
    ZSTDGPU_RO_BUFFER(zstdgpu_CompressedBlockData)          inCompressedBlocks;
} zstdgpu_ExecuteSequences_SRT;

typedef struct zstdgpu_ComputeDestSequenceOffsets_SRT
{
    ZSTDGPU_RW_BUFFER(uint32_t)                             inoutDestSequenceOffsets;
    ZSTDGPU_RO_BUFFER(zstdgpu_Counters)                     inCounters;
    ZSTDGPU_RO_BUFFER(uint32_t)                             inBlockDestOffs;
    ZSTDGPU_RO_BUFFER(uint32_t)                             inDecompressedSequenceMLen;
    ZSTDGPU_RO_BUFFER(uint32_t)                             inPerSeqStreamSeqStart;
    ZSTDGPU_RO_BUFFER(uint32_t)                             inSeqStreamToBlockId;
    uint32_t                                                tgOffset;
    uint32_t                                                workItemCount;
} zstdgpu_ComputeDestSequenceOffsets_SRT;

typedef struct zstdgpu_MemsetMemcpy_SRT
{
    ZSTDGPU_RW_TYPED_BUFFER(uint32_t, uint8_t)              inoutUnCompressedFramesData;
    ZSTDGPU_RO_BUFFER(zstdgpu_Counters)                     inCounters;
    ZSTDGPU_RO_BUFFER(uint32_t)                             inCompressedData;
    ZSTDGPU_RO_BUFFER(uint32_t)                             inBlockDestOffs;
    ZSTDGPU_RO_BUFFER(uint32_t)                             inBlockSizePrefixTyped;
    ZSTDGPU_RO_BUFFER(zstdgpu_OffsetAndSize)                inBlocksRefsTyped;
    ZSTDGPU_RO_BUFFER(uint32_t)                             inGlobalBlockIndexTyped;
    uint32_t                                                tgOffset;
    uint32_t                                                workItemCount;
    uint32_t                                                flags;
} zstdgpu_MemsetMemcpy_SRT;

typedef struct zstdgpu_InitResources_SRT
{
    ZSTDGPU_RO_TYPED_BUFFER(int32_t, int16_t)               inFseProbsDefault;
    ZSTDGPU_RW_TYPED_BUFFER(int32_t, int16_t)               inoutFseProbs;
    ZSTDGPU_RW_BUFFER(zstdgpu_FseInfo)                      inoutFseInfos;
    ZSTDGPU_RW_BUFFER(uint32_t)                             inoutFseElems;
    ZSTDGPU_RW_BUFFER(zstdgpu_Counters)                     inoutCounters;
    uint32_t                                                initResourcesStage;
} zstdgpu_InitResources_SRT;

typedef struct zstdgpu_ParseCompressedBlocks_SRT
{
    ZSTDGPU_RW_BUFFER(zstdgpu_Counters)                     inoutCounters;
    ZSTDGPU_RW_BUFFER(zstdgpu_FseInfo)                      inoutFseInfos;
    ZSTDGPU_RW_BUFFER(zstdgpu_CompressedBlockData)          inoutCompressedBlocks;
    ZSTDGPU_RW_BUFFER(zstdgpu_OffsetAndSize)                inoutHufRefs;
    ZSTDGPU_RW_BUFFER(zstdgpu_LitStreamInfo)                inoutLitRefs;
    ZSTDGPU_RW_BUFFER(zstdgpu_OffsetAndSize)                inoutSeqStreamToRef;
    ZSTDGPU_RW_BUFFER(uint32_t)                             inoutSeqStreamToLLenFseId;
    ZSTDGPU_RW_BUFFER(uint32_t)                             inoutSeqStreamToOffsFseId;
    ZSTDGPU_RW_BUFFER(uint32_t)                             inoutSeqStreamToMLenFseId;
    ZSTDGPU_RW_BUFFER(uint32_t)                             inoutSeqStreamToBlockId;
    ZSTDGPU_RW_BUFFER(uint32_t)                             inoutBlockSizePrefix;
    ZSTDGPU_RW_BUFFER(uint32_t)                             inoutPerFrameSeqStreamMinIdx;
    ZSTDGPU_RW_BUFFER(uint32_t)                             inoutPerSeqStreamSeqStart;
    ZSTDGPU_RW_BUFFER_GLC(uint32_t)                         inoutSeqCountPrefixLookback;
    ZSTDGPU_RW_BUFFER_GLC(uint32_t)                         inoutBlockSeqCountPrefixLookback;
    ZSTDGPU_RW_TYPED_BUFFER(int32_t, int16_t)               inoutFseProbs;
    ZSTDGPU_RW_TYPED_BUFFER(uint32_t, uint8_t)              inoutDecompressedHuffmanWeightCount;
    ZSTDGPU_RW_BUFFER_GLC(uint32_t)                         inoutLitStreamCountPrefixLookback;
    ZSTDGPU_RW_BUFFER(uint32_t)                             inoutHufWIdToHufLitId;
    ZSTDGPU_RW_BUFFER(uint32_t)                             inoutHufLitIdToLitStreamId;
    ZSTDGPU_RW_BUFFER(uint32_t)                             inoutHufLitIdToHufWId_DBG;
    ZSTDGPU_RW_BUFFER_GLC(uint32_t)                         inoutHufLitCompactionLookback;
    ZSTDGPU_RO_BUFFER(uint32_t)                             inCompressedData;
    ZSTDGPU_RO_BUFFER(zstdgpu_OffsetAndSize)                inBlocksCMPRefs;
    ZSTDGPU_RO_BUFFER(uint32_t)                             inPerFrameBlockCountCMP;
    ZSTDGPU_RO_BUFFER(uint32_t)                             inGlobalBlockIndexPerCmpBlock;
    uint32_t                                                tgOffset;
    uint32_t                                                workItemCount;
    uint32_t                                                compressedBufferSizeInBytes;
    uint32_t                                                frameCount;
    uint32_t                                                compressedBlockCount;
} zstdgpu_ParseCompressedBlocks_SRT;

#endif /* ZSTDGPU_SRT_GENERATED_STRUCTS_H */
