/**
 * Copyright (c) Microsoft. All rights reserved.
 * This code is licensed under the MIT License (MIT).
 * THIS CODE IS PROVIDED *AS IS* WITHOUT WARRANTY OF
 * ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING ANY
 * IMPLIED WARRANTIES OF FITNESS FOR A PARTICULAR
 * PURPOSE, MERCHANTABILITY, OR NON-INFRINGEMENT.
 *
 * Advanced Technology Group (ATG)
 *
 * AUTO-GENERATED by zstdgpu_srt_tool.exe. DO NOT EDIT.
 * Source of truth: zstdgpu_srt_decl.h
 */

#ifndef ZSTDGPU_SRT_GENERATED_InitResources_H
#define ZSTDGPU_SRT_GENERATED_InitResources_H

#include "ZstdGpuSrt_BindGroup_FseInit.h"

#ifdef __hlsl_dx_compiler

ZSTDGPU_RW_BUFFER(zstdgpu_Counters) ZstdInOutCounters   : register(u0);

typedef struct zstdgpu_InitResources_Consts
{
    uint32_t    initResourcesStage;
} zstdgpu_InitResources_Consts;

ConstantBuffer<zstdgpu_InitResources_Consts> ZstdConstants_InitResources : register(b0);

#define ZSTDGPU_SRT_RS_InitResources ZSTDGPU_SRT_RS_BIND_GROUP_FseInit ", UAV(u0)" ", RootConstants(b0, num32BitConstants=1)"

static void zstdgpu_Srt_Fill(ZSTDGPU_PARAM_INOUT(zstdgpu_InitResources_SRT) srt)
{
    zstdgpu_Srt_FillBindGroup_FseInit(srt);

    srt.inoutCounters       = ZstdInOutCounters;
    srt.initResourcesStage  = ZstdConstants_InitResources.initResourcesStage;
}

#else

static void zstdgpu_Srt_Fill(zstdgpu_InitResources_SRT &srt, const zstdgpu_ResourceDataCpu &cpuRes,
                             uint32_t     initResourcesStage)
{
    zstdgpu_Srt_FillBindGroup_FseInit(srt, cpuRes);

    srt.inoutCounters       = cpuRes.Counters;
    srt.initResourcesStage  = initResourcesStage;
}

#endif

#endif /* ZSTDGPU_SRT_GENERATED_InitResources_H */
