/**
 * Copyright (c) Microsoft. All rights reserved.
 * This code is licensed under the MIT License (MIT).
 * THIS CODE IS PROVIDED *AS IS* WITHOUT WARRANTY OF
 * ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING ANY
 * IMPLIED WARRANTIES OF FITNESS FOR A PARTICULAR
 * PURPOSE, MERCHANTABILITY, OR NON-INFRINGEMENT.
 *
 * Advanced Technology Group (ATG)
 *
 * AUTO-GENERATED by zstdgpu_srt_tool.exe. DO NOT EDIT.
 * Source of truth: zstdgpu_srt_decl.h
 */

#ifndef ZSTDGPU_SRT_GENERATED_PropagateFseIndex_H
#define ZSTDGPU_SRT_GENERATED_PropagateFseIndex_H

#ifdef __hlsl_dx_compiler

ZSTDGPU_RW_BUFFER(uint32_t)     ZstdInOutFseIds             : register(u0);
ZSTDGPU_RW_BUFFER_GLC(uint32_t) ZstdInOutFseIndexLookback   : register(u1);

typedef struct zstdgpu_PropagateFseIndex_Consts
{
    uint32_t    tgOffset;
    uint32_t    workItemCount;
} zstdgpu_PropagateFseIndex_Consts;

ConstantBuffer<zstdgpu_PropagateFseIndex_Consts> ZstdConstants_PropagateFseIndex : register(b0);

#define ZSTDGPU_SRT_RS_PropagateFseIndex "UAV(u0)" ", UAV(u1)" ", RootConstants(b0, num32BitConstants=2)"

static void zstdgpu_Srt_Fill(ZSTDGPU_PARAM_INOUT(zstdgpu_PropagateFseIndex_SRT) srt)
{
    srt.inoutFseIds             = ZstdInOutFseIds;
    srt.inoutFseIndexLookback   = ZstdInOutFseIndexLookback;
    srt.tgOffset                = ZstdConstants_PropagateFseIndex.tgOffset;
    srt.workItemCount           = ZstdConstants_PropagateFseIndex.workItemCount;
}

#else

static void zstdgpu_Srt_Fill(zstdgpu_PropagateFseIndex_SRT &srt, const zstdgpu_ResourceDataCpu &,
                             ZSTDGPU_RW_BUFFER(uint32_t)      inoutFseIds,
                             ZSTDGPU_RW_BUFFER_GLC(uint32_t)  inoutFseIndexLookback,
                             uint32_t                         tgOffset,
                             uint32_t                         workItemCount)
{
    srt.inoutFseIds             = inoutFseIds;
    srt.inoutFseIndexLookback   = inoutFseIndexLookback;
    srt.tgOffset                = tgOffset;
    srt.workItemCount           = workItemCount;
}

static void zstdgpu_Srt_Fill_LLen(zstdgpu_PropagateFseIndex_SRT &srt, const zstdgpu_ResourceDataCpu &cpuRes, uint32_t tgOffset, uint32_t workItemCount)
{
    zstdgpu_Srt_Fill(srt, cpuRes, cpuRes.SeqStreamToLLenFseId, cpuRes.FseIndexLookbackLLen, tgOffset, workItemCount);
}

static void zstdgpu_Srt_Fill_Offs(zstdgpu_PropagateFseIndex_SRT &srt, const zstdgpu_ResourceDataCpu &cpuRes, uint32_t tgOffset, uint32_t workItemCount)
{
    zstdgpu_Srt_Fill(srt, cpuRes, cpuRes.SeqStreamToOffsFseId, cpuRes.FseIndexLookbackOffs, tgOffset, workItemCount);
}

static void zstdgpu_Srt_Fill_MLen(zstdgpu_PropagateFseIndex_SRT &srt, const zstdgpu_ResourceDataCpu &cpuRes, uint32_t tgOffset, uint32_t workItemCount)
{
    zstdgpu_Srt_Fill(srt, cpuRes, cpuRes.SeqStreamToMLenFseId, cpuRes.FseIndexLookbackMLen, tgOffset, workItemCount);
}

#endif

#endif /* ZSTDGPU_SRT_GENERATED_PropagateFseIndex_H */
