/**
 * Copyright (c) Microsoft. All rights reserved.
 * This code is licensed under the MIT License (MIT).
 * THIS CODE IS PROVIDED *AS IS* WITHOUT WARRANTY OF
 * ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING ANY
 * IMPLIED WARRANTIES OF FITNESS FOR A PARTICULAR
 * PURPOSE, MERCHANTABILITY, OR NON-INFRINGEMENT.
 *
 * Advanced Technology Group (ATG)
 *
 * AUTO-GENERATED by zstdgpu_srt_tool.exe. DO NOT EDIT.
 * Source of truth: zstdgpu_srt_decl.h
 */

#ifndef ZSTDGPU_SRT_GENERATED_ComputeDestBlockOffsets_H
#define ZSTDGPU_SRT_GENERATED_ComputeDestBlockOffsets_H

#ifdef __hlsl_dx_compiler

ZSTDGPU_RW_BUFFER(uint32_t)                 ZstdInOutBlockDestOffs          : register(u0);
ZSTDGPU_RO_BUFFER(uint32_t)                 ZstdInBlockSizePrefix           : register(t0);
ZSTDGPU_RO_BUFFER(uint32_t)                 ZstdInPerFrameBlockCountAll     : register(t1);
ZSTDGPU_RO_BUFFER(zstdgpu_OffsetAndSize)    ZstdInUnCompressedFramesRefs    : register(t2);

typedef struct zstdgpu_ComputeDestBlockOffsets_Consts
{
    uint32_t    tgOffset;
    uint32_t    workItemCount;
    uint32_t    frameCount;
} zstdgpu_ComputeDestBlockOffsets_Consts;

ConstantBuffer<zstdgpu_ComputeDestBlockOffsets_Consts> ZstdConstants_ComputeDestBlockOffsets : register(b0);

#define ZSTDGPU_SRT_RS_ComputeDestBlockOffsets "UAV(u0)" ", SRV(t0)" ", SRV(t1)" ", SRV(t2)" ", RootConstants(b0, num32BitConstants=3)"

static void zstdgpu_Srt_Fill(ZSTDGPU_PARAM_INOUT(zstdgpu_ComputeDestBlockOffsets_SRT) srt)
{
    srt.inoutBlockDestOffs          = ZstdInOutBlockDestOffs;
    srt.inBlockSizePrefix           = ZstdInBlockSizePrefix;
    srt.inPerFrameBlockCountAll     = ZstdInPerFrameBlockCountAll;
    srt.inUnCompressedFramesRefs    = ZstdInUnCompressedFramesRefs;
    srt.tgOffset                    = ZstdConstants_ComputeDestBlockOffsets.tgOffset;
    srt.workItemCount               = ZstdConstants_ComputeDestBlockOffsets.workItemCount;
    srt.frameCount                  = ZstdConstants_ComputeDestBlockOffsets.frameCount;
}

#else

static void zstdgpu_Srt_Fill(zstdgpu_ComputeDestBlockOffsets_SRT &srt, const zstdgpu_ResourceDataCpu &cpuRes,
                             uint32_t     tgOffset,
                             uint32_t     workItemCount,
                             uint32_t     frameCount)
{
    srt.inoutBlockDestOffs          = cpuRes.BlockDestOffs;
    srt.inBlockSizePrefix           = cpuRes.BlockSizePrefix;
    srt.inPerFrameBlockCountAll     = cpuRes.PerFrameBlockCountAll;
    srt.inUnCompressedFramesRefs    = cpuRes.UnCompressedFramesRefs;
    srt.tgOffset                    = tgOffset;
    srt.workItemCount               = workItemCount;
    srt.frameCount                  = frameCount;
}

#endif

#endif /* ZSTDGPU_SRT_GENERATED_ComputeDestBlockOffsets_H */
