/**
 * Copyright (c) Microsoft. All rights reserved.
 * This code is licensed under the MIT License (MIT).
 * THIS CODE IS PROVIDED *AS IS* WITHOUT WARRANTY OF
 * ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING ANY
 * IMPLIED WARRANTIES OF FITNESS FOR A PARTICULAR
 * PURPOSE, MERCHANTABILITY, OR NON-INFRINGEMENT.
 *
 * Advanced Technology Group (ATG)
 *
 * AUTO-GENERATED by zstdgpu_srt_tool.exe. DO NOT EDIT.
 * Source of truth: zstdgpu_srt_decl.h
 */

#ifndef ZSTDGPU_SRT_GENERATED_RS_BIND_GROUP_HuffmanTable_H
#define ZSTDGPU_SRT_GENERATED_RS_BIND_GROUP_HuffmanTable_H

#ifdef __hlsl_dx_compiler

#define ZSTDGPU_SRT_RS_BIND_GROUP_HuffmanTable "DescriptorTable(SRV(t0, space=3, numDescriptors=3))"

ZSTDGPU_RO_BUFFER(uint32_t) ZstdInHuffmanTableInfo          : register(t0, space3);
ZSTDGPU_RO_BUFFER(uint32_t) ZstdInHuffmanTableCodeAndSymbol : register(t1, space3);
ZSTDGPU_RO_BUFFER(uint32_t) ZstdInHuffmanTableRankIndex     : register(t2, space3);

template<typename T>
static void zstdgpu_Srt_FillBindGroup_HuffmanTable(ZSTDGPU_PARAM_INOUT(T) srt)
{
    srt.inHuffmanTableInfo          = ZstdInHuffmanTableInfo;
    srt.inHuffmanTableCodeAndSymbol = ZstdInHuffmanTableCodeAndSymbol;
    srt.inHuffmanTableRankIndex     = ZstdInHuffmanTableRankIndex;
}

#else

template<typename T>
static void zstdgpu_Srt_FillBindGroup_HuffmanTable(T &srt, const zstdgpu_ResourceDataCpu &cpuRes)
{
    srt.inHuffmanTableInfo          = cpuRes.HuffmanTableInfo;
    srt.inHuffmanTableCodeAndSymbol = cpuRes.HuffmanTableCodeAndSymbol;
    srt.inHuffmanTableRankIndex     = cpuRes.HuffmanTableRankIndex;
}

#endif /* #ifdef __hlsl_dx_compiler */
#endif /* ZSTDGPU_SRT_GENERATED_RS_BIND_GROUP_HuffmanTable_H */
