/**
 * Copyright (c) Microsoft. All rights reserved.
 * This code is licensed under the MIT License (MIT).
 * THIS CODE IS PROVIDED *AS IS* WITHOUT WARRANTY OF
 * ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING ANY
 * IMPLIED WARRANTIES OF FITNESS FOR A PARTICULAR
 * PURPOSE, MERCHANTABILITY, OR NON-INFRINGEMENT.
 *
 * Advanced Technology Group (ATG)
 *
 * AUTO-GENERATED by zstdgpu_srt_tool.exe. DO NOT EDIT.
 * Source of truth: zstdgpu_srt_decl.h
 */

#ifndef ZSTDGPU_SRT_GENERATED_RS_BIND_GROUP_FrameOutput_H
#define ZSTDGPU_SRT_GENERATED_RS_BIND_GROUP_FrameOutput_H

#ifdef __hlsl_dx_compiler

#define ZSTDGPU_SRT_RS_BIND_GROUP_FrameOutput "DescriptorTable(UAV(u0, space=11, numDescriptors=1))"

ZSTDGPU_RW_TYPED_BUFFER(uint32_t, uint8_t)  ZstdInOutUnCompressedFramesData : register(u0, space11);

template<typename T>
static void zstdgpu_Srt_FillBindGroup_FrameOutput(ZSTDGPU_PARAM_INOUT(T) srt)
{
    srt.inoutUnCompressedFramesData = ZstdInOutUnCompressedFramesData;
}

#else

template<typename T>
static void zstdgpu_Srt_FillBindGroup_FrameOutput(T &srt, const zstdgpu_ResourceDataCpu &cpuRes)
{
    srt.inoutUnCompressedFramesData = cpuRes.UnCompressedFramesData;
}

#endif /* #ifdef __hlsl_dx_compiler */
#endif /* ZSTDGPU_SRT_GENERATED_RS_BIND_GROUP_FrameOutput_H */
