/**
 * Copyright (c) Microsoft. All rights reserved.
 * This code is licensed under the MIT License (MIT).
 * THIS CODE IS PROVIDED *AS IS* WITHOUT WARRANTY OF
 * ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING ANY
 * IMPLIED WARRANTIES OF FITNESS FOR A PARTICULAR
 * PURPOSE, MERCHANTABILITY, OR NON-INFRINGEMENT.
 *
 * Advanced Technology Group (ATG)
 *
 * AUTO-GENERATED by zstdgpu_srt_tool.exe. DO NOT EDIT.
 * Source of truth: zstdgpu_srt_decl.h
 */

#ifndef ZSTDGPU_SRT_GENERATED_PrefixSequenceOffsets_H
#define ZSTDGPU_SRT_GENERATED_PrefixSequenceOffsets_H

#ifdef __hlsl_dx_compiler

ZSTDGPU_RW_BUFFER(uint32_t)         ZstdInOutPerSeqStreamFinalOffset1           : register(u0);
ZSTDGPU_RW_BUFFER(uint32_t)         ZstdInOutPerSeqStreamFinalOffset2           : register(u1);
ZSTDGPU_RW_BUFFER(uint32_t)         ZstdInOutPerSeqStreamFinalOffset3           : register(u2);
ZSTDGPU_RW_BUFFER_GLC(uint32_t)     ZstdInOutPerSeqStreamFinalOffset1Lookback   : register(u3);
ZSTDGPU_RW_BUFFER_GLC(uint32_t)     ZstdInOutPerSeqStreamFinalOffset2Lookback   : register(u4);
ZSTDGPU_RW_BUFFER_GLC(uint32_t)     ZstdInOutPerSeqStreamFinalOffset3Lookback   : register(u5);
ZSTDGPU_RO_BUFFER(uint32_t)         ZstdInPerFrameSeqStreamMinIdx               : register(t0);
ZSTDGPU_RO_BUFFER(uint32_t)         ZstdInPerFrameBlockCountAll                 : register(t1);
ZSTDGPU_RO_BUFFER(uint32_t)         ZstdInSeqStreamToBlockId                    : register(t2);
ZSTDGPU_RO_BUFFER(zstdgpu_Counters) ZstdInCounters                              : register(t3);

typedef struct zstdgpu_PrefixSequenceOffsets_Consts
{
    uint32_t    tgOffset;
    uint32_t    workItemCount;
    uint32_t    frameCount;
} zstdgpu_PrefixSequenceOffsets_Consts;

ConstantBuffer<zstdgpu_PrefixSequenceOffsets_Consts> ZstdConstants_PrefixSequenceOffsets : register(b0);

#define ZSTDGPU_SRT_RS_PrefixSequenceOffsets "UAV(u0)" ", UAV(u1)" ", UAV(u2)" ", UAV(u3)" ", UAV(u4)" ", UAV(u5)" ", SRV(t0)" ", SRV(t1)" ", SRV(t2)" ", SRV(t3)" ", RootConstants(b0, num32BitConstants=3)"

static void zstdgpu_Srt_Fill(ZSTDGPU_PARAM_INOUT(zstdgpu_PrefixSequenceOffsets_SRT) srt)
{
    srt.inoutPerSeqStreamFinalOffset1           = ZstdInOutPerSeqStreamFinalOffset1;
    srt.inoutPerSeqStreamFinalOffset2           = ZstdInOutPerSeqStreamFinalOffset2;
    srt.inoutPerSeqStreamFinalOffset3           = ZstdInOutPerSeqStreamFinalOffset3;
    srt.inoutPerSeqStreamFinalOffset1Lookback   = ZstdInOutPerSeqStreamFinalOffset1Lookback;
    srt.inoutPerSeqStreamFinalOffset2Lookback   = ZstdInOutPerSeqStreamFinalOffset2Lookback;
    srt.inoutPerSeqStreamFinalOffset3Lookback   = ZstdInOutPerSeqStreamFinalOffset3Lookback;
    srt.inPerFrameSeqStreamMinIdx               = ZstdInPerFrameSeqStreamMinIdx;
    srt.inPerFrameBlockCountAll                 = ZstdInPerFrameBlockCountAll;
    srt.inSeqStreamToBlockId                    = ZstdInSeqStreamToBlockId;
    srt.inCounters                              = ZstdInCounters;
    srt.tgOffset                                = ZstdConstants_PrefixSequenceOffsets.tgOffset;
    srt.workItemCount                           = ZstdConstants_PrefixSequenceOffsets.workItemCount;
    srt.frameCount                              = ZstdConstants_PrefixSequenceOffsets.frameCount;
}

#else

static void zstdgpu_Srt_Fill(zstdgpu_PrefixSequenceOffsets_SRT &srt, const zstdgpu_ResourceDataCpu &cpuRes,
                             uint32_t     tgOffset,
                             uint32_t     workItemCount,
                             uint32_t     frameCount)
{
    srt.inoutPerSeqStreamFinalOffset1           = cpuRes.PerSeqStreamFinalOffset1;
    srt.inoutPerSeqStreamFinalOffset2           = cpuRes.PerSeqStreamFinalOffset2;
    srt.inoutPerSeqStreamFinalOffset3           = cpuRes.PerSeqStreamFinalOffset3;
    srt.inoutPerSeqStreamFinalOffset1Lookback   = cpuRes.PerSeqStreamFinalOffset1Lookback;
    srt.inoutPerSeqStreamFinalOffset2Lookback   = cpuRes.PerSeqStreamFinalOffset2Lookback;
    srt.inoutPerSeqStreamFinalOffset3Lookback   = cpuRes.PerSeqStreamFinalOffset3Lookback;
    srt.inPerFrameSeqStreamMinIdx               = cpuRes.PerFrameSeqStreamMinIdx;
    srt.inPerFrameBlockCountAll                 = cpuRes.PerFrameBlockCountAll;
    srt.inSeqStreamToBlockId                    = cpuRes.SeqStreamToBlockId;
    srt.inCounters                              = cpuRes.Counters;
    srt.tgOffset                                = tgOffset;
    srt.workItemCount                           = workItemCount;
    srt.frameCount                              = frameCount;
}

#endif

#endif /* ZSTDGPU_SRT_GENERATED_PrefixSequenceOffsets_H */
